import re
import streamlit as st

def update_celsis_page(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # We need to replace everything from `p1 = ...` down to `smart_phase1_part2 = ...`
    # Let's locate the start and end of this block
    start_marker = r'p1 = f"All analysts involved'
    end_marker = r'smart_phase1_part2 = "\\n\\n"\.join\(\[.*?\]\)'
    
    # We will use regex to find this entire block and replace it
    pattern = re.compile(f"({start_marker}.*?{end_marker})", re.DOTALL)
    
    replacement = """# Extract initials
        p_name = st.session_state.prepper_name.strip()
        a_name = st.session_state.analyst_name.strip()
        alq_name = st.session_state.aliquoting_name.strip()
        p_init = st.session_state.prepper_initial.strip()
        a_init = st.session_state.analyst_initial.strip()
        alq_init = st.session_state.aliquoting_initial.strip()
        is_same_prep = (p_name.lower() == a_name.lower()) or (p_init and a_init and p_init.lower() == a_init.lower())

        if is_same_prep:
            analyst_intro = f"{a_name} ({a_init}) and {alq_name} ({alq_init})"
            integrity_intro = f"the sample prepping and processing analyst - {a_init} -"
        else:
            analyst_intro = f"{p_name} ({p_init}), {a_name} ({a_init}) and {alq_name} ({alq_init})"
            integrity_intro = f"both the sample prepping analyst - {p_init} - and the processing analyst - {a_init} -"

        p1 = f"The analysts involved in the prepping, processing, aliquoting, and reading of the samples - {analyst_intro} - were interviewed comprehensively. Their answers are recorded throughout this document. This investigation was performed as per SOP 2.600.069 - Sterility Test Out-of-Specification (OOS) Investigation Procedure."
        p2 = f"Upon arrival, the {sample_noun} was stored in accordance with the Client's instructions. {integrity_intro.capitalize()} verified the {sample_noun}'s integrity throughout both the preparation and processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the {sample_noun}."
        p3 = "All reagents and supplies mentioned in the material section above were stored according to the suppliers' recommendations, and their integrity was visually verified before utilization. Moreover all reagents and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
        
        if t_suite == "L-Suite":
            airflow_text = f"The {sample_noun} was processed within the ISO 5 Biological Safety Cabinet (BSC), E00{st.session_state.bsc_id}, situated in the innermost cleanroom (CR 145), which connects to the intermediate ISO 7 buffer room (CR 144) and the ISO 7 anteroom (CR 143). This anteroom, in turn, leads to the outermost ISO 8 room (CR 142). Furthermore, a positive air pressure system is maintained between the suites, ensuring airflow from the innermost ISO 7 cleanroom outward."
            suite_inner = "Cleanroom 145"
            disinf_route = "the ISO 8 room (CR 142), where the vials underwent a second disinfection using acidified bleach, again with a 10-minute contact time. Subsequently, the vials were moved into the ISO 7 cleanroom (CR 145)."
            p11 = f"Monthly cleaning and disinfection of the outermost ISO 8 room, the ISO 8 anteroom, the ISO 7 buffer cleanroom, the innermost ISO 7 cleanroom, and its containing ISO 5 Biosafety Cabinets for {t_suite} and CR 114 was performed on {st.session_state.monthly_cleaning_date}. Cleaning was performed as per SOP 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology). Following the monthly cleaning, it was documented that all H₂O₂ indicators passed. thus, confirming efficient monthly cleaning of all four parts of Cleanroom {t_suite} and all three parts of Cleanroom 114."
        else:
            airflow_text = f"The {sample_noun} was processed within the ISO 5 Biological Safety Cabinet (BSC), E00{st.session_state.bsc_id}, situated in the innermost cleanroom (Suite {t_suite}B), which connects to the intermediate ISO 7 buffer room (Suite {t_suite}A). This buffer room, in turn, leads to the outermost ISO 8 Anteroom (Suite {t_suite}). Furthermore, a positive air pressure system is maintained between the suites, ensuring airflow from the innermost ISO 7 cleanroom to the intermediate ISO 7 buffer room and finally to the outermost ISO 8 Anteroom."
            suite_inner = f"Cleanroom Suite {t_suite}B"
            disinf_route = f"the ISO 8 anteroom (Suite {t_suite}), where the vials underwent a second disinfection using acidified bleach, again with a 10-minute contact time. Subsequently, the vials were moved into the ISO 7 cleanroom (Suite {t_suite}B)."
            p11 = f"Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 cleanroom, and its containing ISO 5 Biosafety Cabinets for CR{t_suite} and CR114 was performed on {st.session_state.monthly_cleaning_date}. Cleaning was performed as per SOP 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology). Following the monthly cleaning, it was documented that all H₂O₂ indicators passed. thus, confirming efficient monthly cleaning of all three parts of Cleanroom {t_suite} and 114."

        p4 = airflow_text
        p5 = f"The innermost ISO 7 {suite_inner}, and the ISO 5 BSC E00{st.session_state.bsc_id} within the {suite_inner} were thoroughly cleaned and prepared before initiating the testing by analyst {a_init} as per SOP 2.600.002 (Environmental Monitoring of the Clean Room Facility), and SOP 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology). Similarly, for Celsis aliquoting, the ISO 7 Cleanroom 114A, and the ISO 5 BSC E001798 within the ISO 7 Cleanroom 114A were thoroughly cleaned and prepared by aliquoting analyst {alq_init}, before initiating the testing as per SOP 2.600.002 and SOP 2.600.018. Both the BSCs, E00{st.session_state.bsc_id} and E001798 in suite 114A, were certified and approved by the Engineering and Quality Assurance teams prior to use."
        p6 = f"On {received_date_str}, {a_init} confirmed that each sample vial for {st.session_state.sample_id}, was sprayed with an acidified bleach disinfectant, placed into pre-disinfected bins, and allowed a 10-minute contact time. Following initial disinfection, the bins were transferred to {disinf_route} Inside this cleanroom, the processing analyst, {a_init}, performed a final disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, the vials were transferred into the ISO 5 BSC E00{st.session_state.bsc_id}. Inside the BSC, the vials were placed on the disinfected work surface, aseptically opened, and tested in accordance with SOP 2.600.059 (Celsis Sterility Testing). Following testing, the media bottles were subsequently transferred into designated incubators, E001356 and E001357, to initiate incubation."
        p7 = f"Upon completion of incubation on {st.session_state.test_date}, TSB & FTM bottles for {st.session_state.sample_id} were disinfected and transferred to the middle ISO 7 buffer room (Suite 114A) for aliquoting step per SOP 2.600.059 (Celsis Sterility Testing). In Suite 114A, the media bottles were disinfected one more time before transferring them to the ISO 5 BSC E001798 located in Suite 114A. In ISO 5 BSC E001798, the {sample_noun} was aliquoted into assay cuvettes by analyst {alq_init}."
        p8 = f"After aliquoting, Celsis Sterility Reading was performed in accordance with SOP 2.600.059 by analyst {alq_init}. Following the reading, {sample_noun} {st.session_state.sample_id} was found to be positive in the {st.session_state.positive_media} media {bottle_noun}. The average Relative Luminescence Units (RLU) from the duplicate reading tube, originating from the {st.session_state.positive_media} sample {bottle_noun}, exceeded the average RLU of the {st.session_state.positive_media} negative control, confirming a positive result. It is to be noted that the %CV from the duplicate {st.session_state.positive_media} media bottles readings was greater than 30%. However, both duplicate tubes reached the instrument's upper detection limit, resulting in an 'overload' readings. All Daily Controls, including the Instrument Blank, Reagent Blank, and ATP Positive Control, were within the defined specifications, each with a %CV below 30%."
        p9 = f"Following the OOS result, the positive {st.session_state.positive_media} {bottle_noun} for the sample was submitted for Differential Staining and Microbial Identification under {st.session_state.positive_id}. Microbial growth was identified as {st.session_state.positive_org}."
        p10 = "The culture media utilized were within their expiry period. The negative culture media bottles were handled, processed, and incubated in a manner identical to that of actual samples. No microbial growth was observed in the corresponding negative control."
        p12 = "Tables 2 & 3 (please see attached) present the environmental monitoring results for the duration of testing. The environmental monitoring (EM) plates were incubated for no less than 48 hours at 30-35°C and no less than an additional five days at 20-25°C as per SOP 2.600.002, Rev 15 (Environmental Monitoring of the Cleanroom Facility). Table 2 pertains to Environmental Monitoring performed during Celsis Sterility Processing, and Table 3 pertains to Environmental Monitoring performed during Celsis Sterility Aliquoting."
        
        em_pro_narrative, em_alq_narrative, smart_just = cl.generate_celsis_narrative_and_details()
        
        p13 = em_pro_narrative
        p14 = em_alq_narrative
        p15 = smart_just
        
        p16 = f"All analysts confirmed full compliance with cleaning procedures as outlined in SOPs 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology), 2.600.059 (Celsis Sterility Testing), and 2.600.008 (USP <71> / EP 2.6.1 Sterility Test). A review of the available data confirms that the cleanroom and equipment conditions remained within acceptable parameters. No deviations or obvious signs of laboratory error during processing and aliquoting were noted from analysts.\\n\\nNo other sample processed by analyst {a_init} on {received_date_str} and aliquoted by analyst {alq_init} on {st.session_state.test_date}, failed Celsis Sterility testing that day."
        
        p17 = cl.generate_celsis_history_text()
        p18 = f"A review of the lot history shows that there have been no additional submissions of sample lot- {st.session_state.lot_number} for retesting using Celsis Sterility Testing or any other sterility method."
        
        if st.session_state.get("other_positives") == "No": 
            fresh_cross = f"All other samples processed by analyst {a_init} on the date of testing returned negative results with no evidence of microbial growth. The absence of positive findings across concurrently processed samples demonstrates that the testing environment was operating under controlled and acceptable conditions, and strongly indicates that cross-contamination between samples did not occur."
        else:
            fresh_cross = cl.generate_celsis_cross_contam_text()
            
        p19 = f"To assess the potential for sample-to-sample contamination as a contributing factor to the positive result, a comprehensive review was conducted of all samples processed during the same testing session on {received_date_str}. {fresh_cross} These findings support the conclusion that the positive result was an isolated event confined to the specific test article and was not attributable to analyst technique, sample handling procedures, or the laboratory environment."
        p20 = "A thorough review of all available data, encompassing reagents, supplies, cleanroom environmental monitoring, analyst performance records, and procedural compliance documentation, confirms that no contributing factors attributable to the laboratory or its personnel were identified. All critical control points were operating within established acceptance criteria at the time of testing and aliquoting. Accordingly, the positive result is considered a valid and isolated finding limited to the specific test article, with the probability of laboratory-introduced error effectively ruled out."

        smart_phase1_full = "\\n\\n".join([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20])
        smart_phase1_part1 = "\\n\\n".join([p1, p2, p3, p4, p5, p6])
        smart_phase1_part2 = "\\n\\n".join([p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20])"""

    new_content = re.sub(pattern, replacement, content)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
        
    print("Updated Celsis.py")

update_celsis_page(r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\Eagle\oos-tools\pages\Celsis.py")
