import os
from docxtpl import DocxTemplate

def generate_rich_template():
    # 1. We load the HOLLOW template (0.docx)
    tpl = DocxTemplate("USP71 OOS P1 template 0.docx")
    
    # 2. We construct the hardcoded English paragraphs for USP 71, 
    # but we inject literal Jinja2 tags (e.g., '{{ sample_id }}') instead of real data.
    
    # 智能双擎单复数探测器 (Smart Dual-Engine Concordance) placeholders
    sample_noun = "{{ sample_noun }}"
    sample_verb = "{{ sample_verb }}"
    bottle_noun = "{{ bottle_noun }}"
    submit_verb = "{{ submit_verb }}"
    org_noun = "{{ org_noun }}"

    p1 = f"All analysts involved in the prepping, processing, reading, and subculturing of the {sample_noun} – {{{{ prepper_name }}}}, {{{{ analyst_name }}}}, {{{{ reading_name }}}}, and {{{{ subculture_name }}}} were interviewed comprehensively. Their answers are recorded throughout this document."
    p2 = f"Upon arrival, the {sample_noun} {sample_verb} stored in accordance with the Client’s instructions. Analyst {{{{ prepper_name }}}} verified the integrity of the {sample_noun} throughout both the preparation and processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the {sample_noun}."
    p3 = "All reagents and supplies mentioned in the material section above were stored according to the suppliers’ recommendations, and their integrity was visually verified before utilization. Moreover, all reagents and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
    p4 = f"During the preparation phase, {{{{ prepper_name }}}} disinfected the {sample_noun} using acidified bleach and placed them into a pre-disinfected storage bin. On {{{{ process_date }}}}, prior to sample processing, {{{{ analyst_name }}}} performed a second disinfection with acidified bleach, allowing a minimum contact time of 10 minutes before transferring the {sample_noun} into the cleanroom suites. A final disinfection step was completed immediately before the {sample_noun} were introduced into the ISO 5 Biological Safety Cabinet (BSC), E00{{{{ bsc_id }}}}, located within the {{{{ bsc_location }}}}, (Suite {{{{ cr_suit }}}}{{{{ suit }}}}). All activities were conducted in accordance with SOP 2.600.008 for the USP <71> / EP 2.6.1 Sterility Test."
    
    p5 = f"{{{{ equipment_summary }}}}" # This is already dynamic
    
    p6 = (
        "{{% if testing_method == 'Membrane Filtration' %}}"
        f"On {{{{ received_data }}}}, the sample containers for {{{{ sample_id }}}} were received from the Sample Submissions team and brought into the Sterile Microbiology lab. Upon receipt, each sample container was sprayed with an acidified bleach disinfectant, placed into pre-disinfected bins, and allowed a 10-minute contact time. Following initial disinfection, the bins were transferred to the ISO 8 anteroom (Suite {{{{ cr_suit }}}}), where the container underwent a second disinfection using acidified bleach, again with a 10-minute contact time. Subsequently, the containers were moved into the ISO 7 clean room Suite {{{{ cr_suit }}}}{{{{ suit }}}}. Inside this cleanroom, the processing analyst, {{{{ analyst_name }}}}, performed a final disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, the containers were transferred into the ISO 5 BSC E00{{{{ bsc_id }}}}."
        "{{% else %}}"
        f"On {{{{ received_data }}}}, the sample vials for {{{{ sample_id }}}} were received from the Sample Submissions team and brought into the Sterile Microbiology lab. Upon arrival, each sample vial was sprayed with an acidified bleach disinfectant, placed into pre-disinfected bins, and allowed a 10-minute contact time. The secondary disinfection happened in the ISO 8 anteroom (Suite {{{{ cr_suit }}}}), where the vials were again treated with acidified bleach and provided a 10‑minute contact time before processing. Subsequently, the vials were moved into the ISO 7 cleanroom Suite {{{{ cr_suit }}}}{{{{ suit }}}}. Inside this cleanroom, the processing analyst, {{{{ analyst_name }}}}, performed a final disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, the vials were transferred into the ISO 5 BSC E00{{{{ bsc_id }}}}."
        "{{% endif %}}"
    )
    
    p7 = (
        "{{% if testing_method == 'Membrane Filtration' %}}"
        f"Once transferred into the ISO 5 BSC, the containers were placed on the disinfected working surface of the BSC E00{{{{ bsc_id }}}} and aseptically processed in accordance with SOP 2.600.008 (USP <71> / EP 2.6.1 Sterility Test). Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. The contents were then dispensed directly from the container into sterile canisters placed on a vacuum manifold for membrane filtration. The sample {{{{ sample_id }}}} was processed and tested as per SOP 2.600.008 (USP <71> / EP 2.6.1 Sterility Test). Media bottles were transferred into incubators E001356 and E001357 to begin incubation. Visual inspections were performed periodically by the analyst over the {{{{ incubation_time }}}}-day period to detect any macroscopic evidence of microbial growth."
        "{{% else %}}"
        f"Once transferred into the ISO 5 BSC, the vials were placed on the disinfected working surface of the BSC E00{{{{ bsc_id }}}} and aseptically processed in accordance with SOP 2.600.008 (USP <71> / EP 2.6.1 Sterility Test). Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. The contents were then transferred from the container into media bottles for direct inoculation. The {sample_noun} {sample_verb} inoculated into Fluid Thioglycollate Medium (FTM) and Tryptic Soy Broth (TSB). Following inoculation, the media bottles were transferred into designated incubators to initiate a 14-day continuous incubation cycle. FTM bottles were incubated at 30-35°C, while TSB bottles were incubated at 20-25°C. Visual inspections were performed periodically by the analyst over the {{{{ incubation_time }}}}-day period to detect any macroscopic evidence of microbial growth."
        "{{% endif %}}"
    )
    
    p8_p9_p10_combined = (
        "{{% if subculture_name %}}"
        "During the periodic visual inspections by analyst {{{{ reading_name }}}}, macroscopic evidence of microbial growth was observed. As a result, a subculture was initiated by analyst {{{{ subculture_name }}}} to confirm the presence of viable microorganisms and to proceed with identification. "
        "{{% else %}}"
        "During the periodic visual inspections by analyst {{{{ reading_name }}}}, macroscopic evidence of microbial growth was observed, confirming the presence of viable microorganisms and proceeding with identification. "
        "{{% endif %}}"
        f"Following the {{{{ incubation_time }}}}-day incubation and visual readings, {sample_noun} {{{{ sample_id }}}} {sample_verb} found to yield a positive reading in the {{{{ positive_media }}}} media {bottle_noun}, confirming a positive result for microbial growth. "
        f"The positive {{{{ positive_media }}}} {bottle_noun} for {{{{ sample_id }}}} {submit_verb} submitted for Differential Staining and Microbial Identification under {{{{ positive_id }}}}, where the {org_noun} identified as {{{{ positive_org }}}}."
    )
    
    p11 = (
        "{{% if testing_method == 'Membrane Filtration' %}}"
        "The culture media utilized were within their expiry period. The negative control canisters for the membrane filtration method for the original culture were handled, processed, and incubated in a manner identical to that of actual samples. No microbial growth was observed in the corresponding negative control."
        "{{% else %}}"
        "The culture media utilized were within their expiry period. The negative culture media bottles for the direct inoculation method for the original culture were handled, processed, and incubated in a manner identical to that of actual samples. No microbial growth was observed in the corresponding negative control."
        "{{% endif %}}"
    )
    p12 = f"{{{{ narrative_summary }}}}"
    p13 = "The analysts confirmed full compliance with cleaning procedures as outlined in SOPs 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology) and 2.600.008 (USP <71> / EP 2.6.1 Sterility Test)."
    p14 = f"Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 cleanroom, and its containing ISO 5 Biosafety Cabinets for CR {{{{ cr_suit }}}} was performed on {{{{ monthly_cleaning_date }}}}, as per SOP 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology). During both cleaning cycles, it was documented that all H₂O₂ indicators passed. This confirms the efficient monthly cleaning of all three parts of Cleanroom {{{{ cr_suit }}}}"
    p15 = f"{{{{ sample_history_paragraph }}}}"
    p16 = f"To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review was conducted of all samples processed on the same day. {{{{ cross_contamination_summary }}}}"
    p17 = "Based on the observations outlined above, it is unlikely that the failing results were due to reagents, supplies, the cleanroom environment, the process, or analyst involvement. Consequently, the possibility of laboratory error contributing to this failure is minimal and the original result is deemed to be valid."

    smart_phase1_part1 = "\n\n".join([p1, p2, p3, p4, p5, p6, p7])
    smart_phase1_part2 = "\n\n".join([p8_p9_p10_combined, p11, p12, p13, p14, p15, p16, p17])
    
    smart_personnel_block = (f"Prepper: \n{{{{ prepper_name }}}} ({{{{ prepper_initial }}}})\n\n"
                             f"Processor:\n{{{{ analyst_name }}}} ({{{{ analyst_initial }}}})\n\n"
                             f"Reading Analyst:\n{{{{ reading_name }}}} ({{{{ reading_initial }}}})\n\n"
                             f"Subculture Analyst:\n{{{{ subculture_name }}}} ({{{{ subculture_initial }}}})")
                             
    smart_incident_opening = f"On {{{{ test_date }}}}, {sample_noun} {{{{ sample_id }}}} {sample_verb} found positive for viable microorganisms after USP <71> / EP 2.6.1 Sterility Test."
    
    # Render the hollow template with these massive literal strings
    context = {
        "smart_phase1_part1": smart_phase1_part1,
        "smart_phase1_part2": smart_phase1_part2,
        "smart_incident_opening": smart_incident_opening,
        "smart_personnel_block": smart_personnel_block,
        "smart_comment_interview": f"Yes, analysts {{{{ prepper_name }}}}, {{{{ analyst_name }}}}, {{{{ reading_name }}}}, and {{{{ subculture_name }}}} were interviewed comprehensively.",
        "smart_comment_samples": f"Yes, {sample_noun} ID: {{{{ sample_id }}}}",
        "smart_comment_records": f"Yes, Information is available in EagleTrax under {{{{ sample_id }}}}",
        "smart_comment_storage": f"Yes, the {sample_noun} {sample_verb} stored as per client's instructions. Information is available in EagleTrax Sample Location History under {{{{ sample_id }}}}",
        "smart_cr_id": f"CR{{{{ cr_suite }}}} (E00{{{{ cr_room }}}})"
    }
    
    tpl.render(context)
    tpl.save("USP71 OOS P1 template.docx")
    print("Successfully reverse-rendered the hollow template into the rich template!")

if __name__ == "__main__":
    generate_rich_template()
