"""
Script: build_phase1_oos_262098.py
Purpose: Regenerate Phase 1 Word and PDF deliverables for OOS-262098 (Solyn LLC, GLP3R/Cagrilinitide, Lot 2608-216),
         strictly containing the ORIGINAL test (ETX-260902-0505) only, following the exact structure and template
         of reference OOS-261987 P1 (Signed by OA-RS).
"""

import os, sys, copy, shutil
from pypdf import PdfWriter, PdfReader
import fitz
import docx
from docx.shared import Pt, Inches
from docx.oxml import parse_xml
from docxtpl import DocxTemplate

OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"
DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")

OOS_ID = "262098"
CLIENT_NAME = "Solyn LLC (E75000)"
SAMPLE_NAME = "GLP3R/Cagrilinitide"
LOT_NUMBER = "2608-216"
DOSAGE_FORM = "Liquid"

ORIG_SAMPLE_ID = "ETX-260902-0505"
ORIG_PROCESS_DATE = "04-Sep-2026"
ORIG_PROCESS_DATE_SHORT = "04Sep26"
ORIG_READ_DATE = "10-Sep-2026"
ORIG_READ_DATE_SHORT = "10Sep26"

ORIG_PREPPER = "Ishita Sharma"
ORIG_PREPPER_INIT = "IS"
ORIG_PROCESSOR = "Alex Saravia"
ORIG_PROCESSOR_INIT = "AS"
ORIG_READER = "Elysse Nioupin"
ORIG_READER_INIT = "EN"

BSC_ID = "E001316"
CR_ID = "CR114"
CR_SENSOR = "E001736 (CR114)"
BSC_CAL_DUE = "Dec 2026"
CR_CAL_DUE = "Jan 2027"

# -------------------------------------------------------------
# 1. Master Narrative Blocks for Phase 1 (Matching OOS-261987 P1)
# -------------------------------------------------------------

# --- PAGE 3 (Text Field 49) ---
p1 = (
    "All analysts involved in the prepping, processing, and reading of the sample – Ishita Sharma, Alex Saravia, and Elysse Nioupin – "
    "were interviewed comprehensively. Their answers are recorded throughout this document."
)

p2 = (
    "Upon arrival, the sample was stored in accordance with the Client’s instructions. Analysts verified the "
    "integrity of the sample throughout both the preparation and processing stages. No leaks or turbidity were observed at "
    "any point, verifying the integrity of the sample."
)

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to the suppliers’ recommendations, "
    "and their integrity was visually verified before utilization. Moreover, all reagents and supplies had valid expiration dates. "
    "The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The cleanroom suite (CR 114) used for processing procedures comprises three interconnected sections: the innermost ISO 7 "
    "cleanroom (114B), which connects to the middle ISO 7 buffer room (114A), and then to the outermost ISO 8 anteroom (114). "
    "A positive air pressure system is maintained throughout the suite to ensure controlled, unidirectional airflow from 114B through 114A and into 114."
)

p5 = (
    "The ISO 5 Biological Safety Cabinet (BSC) E001316, located in the innermost ISO 7 room (114B), was used for sample processing steps. "
    "It was thoroughly cleaned and disinfected prior to each procedure in accordance with MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    "Additionally, BSC E001316 was certified and approved by both the Engineering and Quality Assurance teams. Sample processing was conducted "
    "in the ISO 5 BSC E001316 in the innermost ISO 7 room (114B) by Alex Saravia on 04 Sep 2026 as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p6 = (
    "On 04 Sep 2026, the sample vials for ETX-260902-0505 were received from the Sample Submissions team and brought into the Sterile Microbiology lab. "
    "Upon arrival, each sample vial was sprayed with an acidified bleach disinfectant, placed into pre-disinfected bins, and allowed a 10-minute contact time."
)

text_field_49 = "\r \r".join([p1, p2, p3, p4, p5, p6])

# --- PAGE 4 (Text Field 50) ---
p7 = (
    "The secondary disinfection happened in the ISO 8 anteroom (114), where the vials were again treated with acidified bleach and "
    "provided a 10-minute contact time before processing. Subsequently, the vials were moved into innermost ISO 7 cleanroom (114B). "
    "Inside this cleanroom, the processing analyst, Alex Saravia, performed a final disinfection step, allowing an additional 10-minute contact time. "
    "Once fully disinfected, the vials were transferred into the ISO 5 BSC E001316."
)

p8 = (
    "Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. The contents were then dispensed "
    "directly from the container into sterile canisters placed on a vacuum manifold for membrane filtration (45 gm filtered per media across 3 vials). "
    "The sample was processed and tested as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test). Media bottles were transferred into incubators E001356 and E001357 to begin incubation."
)

p9 = (
    "On 10 Sep 2026 (Day 6 of incubation), microbial growth was observed in one TSB (Tryptic Soy Broth) media bottle by analyst, Elysse Nioupin, "
    "and confirmed by Microbiology Lab Supervisor, Robin Seymour. The positive TSB bottle for ETX-260902-0505 was submitted for Differential Staining "
    "and Microbial Identification under ETX-260910-0290. Differential staining indicated the presence of Gram-positive rods. Definitive identification "
    "identified the isolate as Microbacterium sp. PM5 (Gram-positive rods)."
)

p10 = (
    "The culture media utilized were within their expiry period. Negative control media bottles for the membrane filtration method were handled, "
    "processed, and incubated in the same manner as the test samples. No microbial growth was observed in the corresponding negative controls."
)

p11 = (
    "Upon analyzing the environmental monitoring results, no microbial growth was detected on personnel monitoring plates, settling plates, "
    "or ISO 5 BSC surface sampling plates on the date of testing (04Sep26), the preceding testing date (03Sep26), or the subsequent testing date (08Sep26). "
    "Additionally, no microbial growth was recovered from the weekly surface sampling plate collected on 04Sep26. However, weekly active air monitoring "
    "of ISO 8 Room 114 (CR 114) recovered 2 CFUs (ETX-260914-0487). Definitive identification confirmed the organisms to be Corynebacterium ureicelerivorans "
    "and Mycobacterium grossiae."
)

text_field_50 = "\r \r".join([p7, p8, p9, p10, p11])

# --- PAGE 5 (Text Field 51) ---
p12 = (
    "It is important to note that the colony morphology of the microorganisms recovered from the cleanroom environment differed from that of the "
    "microorganism isolated from the test sample. This morphological distinction indicates that the environmental monitoring recovery and the test "
    "sample contamination were isolated and unrelated events."
)

p13 = (
    "In addition, considering the facility's layered disinfection program, controlled unidirectional airflow, and cleanroom design, it is unlikely "
    "that the microbial contaminant detected in the ISO 8 environment impacted on the sample processed within the ISO 5 area of the ISO 7 cleanroom (114B)."
)

p14 = (
    "The absence of contamination on analyst glove plates and work-surface environmental monitoring plates collected on the date of testing indicates "
    "that there were no viable transfer of contaminants to the ISO 5 BSC. Additionally, the lack of contamination in other samples processed during "
    "the same testing session further demonstrates that the testing environment was operating in optimal condition."
)

p15 = (
    "Therefore, considering that no viable organisms were recovered from the ISO 5 environment, personnel monitoring results were acceptable on the date "
    "of testing, and the environmental isolates were not recovered from locations or surfaces directly involved in sample preparation or testing, the "
    "environmental isolates are not considered a credible source of the contamination detected in the test sample."
)

p16 = (
    "The analysts confirmed full compliance with cleaning procedures as outlined in MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology) "
    "and MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p17 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 cleanroom, and its containing "
    "ISO 5 BSCs for Cleanroom suite CR114 was performed on 30 Aug 2026, as per MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    "During both cleaning cycles, it was documented that all H₂O₂ indicators passed. This confirms the efficient monthly cleaning of all three parts of Cleanroom suite CR114."
)

p18 = (
    "Analyzing a 6-month sample history for Solyn LLC (E75000), this specific analyte \"GLP3R/Cagrilinitide\" has had no prior failures using USP <71> / "
    "EP 2.6.1 Sterility Test during this period."
)

p19 = (
    "To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review was conducted of all samples "
    "processed on the same day. All other samples processed by the analyst and other analysts that day tested negative. These findings suggest that "
    "cross-contamination between samples is highly unlikely."
)

p20 = (
    "Based on the observations outlined above, it is unlikely that the failing results were due to reagents, supplies, the cleanroom environment, the "
    "process, or analyst involvement. Consequently, the possibility of laboratory error contributing to this failure is minimal and the original result is deemed to be valid."
)

text_field_51 = "\r \r".join([p12, p13, p14, p15, p16, p17, p18, p19, p20])

# -------------------------------------------------------------
# 2. Build Master Word Document
# -------------------------------------------------------------
def build_master_word_doc():
    primary_tpl = os.path.join(OOS_ROOT, "USP71 OOS P1 template.docx")
    if not os.path.exists(primary_tpl):
        primary_tpl = os.path.join(OOS_ROOT, "USP71 OOS P1 template 0.docx")
        
    tpl = DocxTemplate(primary_tpl)
    
    smart_full = f"{text_field_49}\n\n{text_field_50}\n\n{text_field_51}"
    
    data_docx = {
        "oos_id": OOS_ID,
        "client_name": CLIENT_NAME,
        "sample_id": ORIG_SAMPLE_ID,
        "sample_name": SAMPLE_NAME,
        "lot_number": LOT_NUMBER,
        "dosage_form": DOSAGE_FORM,
        "test_name": "USP <71> / EP 2.6.1 Sterility Test",
        "test_method": "MICRO-SOP-5",
        "sop_effective_date": "24Jul2026",
        "sop_rev": "19",
        "method_suitability": "N/A",
        "method_performed": "Membrane Filtration",
        "amount_filtered": "45 gm added per media (3 vials)",
        "process_date": ORIG_PROCESS_DATE_SHORT,
        "process_date_full": ORIG_PROCESS_DATE,
        "before_test": "03Sep26",
        "after_test": "08Sep26",
        "test_date": ORIG_READ_DATE_SHORT,
        "test_date_full": ORIG_READ_DATE,
        "received_data": "02Sep26",
        "incubation_time": "14",
        "positive_media": "1 x 100mL TSB bottle",
        "positive_id_1": "ETX-260910-0290",
        "positive_org": "Microbacterium sp. PM5",
        "prepper_initial": ORIG_PREPPER_INIT,
        "prepper_name": ORIG_PREPPER,
        "analyst_initial": ORIG_PROCESSOR_INIT,
        "analyst_name": ORIG_PROCESSOR,
        "subculture_name": "",
        "subculture_initial": "",
        "reading_initial": ORIG_READER_INIT,
        "reading_name": ORIG_READER,
        "writer_name": "Qiyue Chen",
        "qa_manager": "Robin Seymour",
        "qa_notified": "Kathan Parikh",
        "bsc_id": "1316",
        "cr_suit": "114",
        "cr_id": "1736",
        "smart_cr_id": "CR114 (E001736)",
        "suit": "B",
        "bsc_location": "innermost ISO 7 room (114B)",
        "monthly_cleaning_date": "30Aug26",
        "monthly_cleaning_date_full": "30 Aug 2026",
        "smart_phase1_summary": smart_full,
        "smart_comment_interview": f"Yes, analysts {ORIG_PREPPER}, {ORIG_PROCESSOR}, and {ORIG_READER} were comprehensively interviewed.",
        "smart_comment_samples": f"Yes, sample ID: {ORIG_SAMPLE_ID}",
        "smart_comment_records": f"Yes, information is available on EagleTrax under {ORIG_SAMPLE_ID}",
        "smart_comment_storage": f"Yes, the sample was stored as per client's instructions. Information is available in EagleTrax Sample Location History under {ORIG_SAMPLE_ID}",
        "smart_personnel_block": (
            f"Prepping Analyst:\r{ORIG_PREPPER} ({ORIG_PREPPER_INIT})\r \r"
            f"Processing Analyst:\r{ORIG_PROCESSOR} ({ORIG_PROCESSOR_INIT})\r \r"
            f"Reading Analyst:\r{ORIG_READER} ({ORIG_READER_INIT})"
        ),
        "analyst_signature": f"{ORIG_PROCESSOR} (Written by: Qiyue Chen)",
        "smart_incident_opening": f"On {ORIG_READ_DATE}, sample {ORIG_SAMPLE_ID} was found positive for viable microorganisms after USP <71> sterility testing.",
        "usp71_id": "E001316",
        "reader_name": ORIG_READER
    }
    
    tpl.render(data_docx)
    
    # Clean up static artifacts in rendered Table 0
    t0 = tpl.docx.tables[0]
    def set_clean_cell_text(cell, text, font_size_pt=9):
        cell.text = text
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.name = "Times New Roman"
                r.font.size = Pt(font_size_pt)

    for row in t0.rows:
        for cell in row.cells:
            if "Subculture Processor:" in cell.text:
                set_clean_cell_text(
                    cell,
                    f"Prepper: \n{ORIG_PREPPER} ({ORIG_PREPPER_INIT})\n\n"
                    f"Processor:\n{ORIG_PROCESSOR} ({ORIG_PROCESSOR_INIT})\n\n"
                    f"Reading Analyst:\n{ORIG_READER} ({ORIG_READER_INIT})",
                    font_size_pt=8
                )
            if "were interviewed comprehensively" in cell.text and ", ," in cell.text:
                set_clean_cell_text(cell, f"Yes, analysts {ORIG_PREPPER}, {ORIG_PROCESSOR}, and {ORIG_READER} were interviewed comprehensively.", font_size_pt=8)

    set_clean_cell_text(t0.rows[29].cells[11], "Dec 2026", font_size_pt=9)
    set_clean_cell_text(t0.rows[30].cells[11], "Jan 2027", font_size_pt=9)
    set_clean_cell_text(
        t0.rows[36].cells[6],
        "Incubator E001356 (Sensor E001450)\n\n"
        "Incubator E001357 (Sensor E001449)\n\n"
        "Incubator E001034 (Sensor E001501)\n\n"
        "Incubator E001031 (Sensor E001505)",
        font_size_pt=8
    )
    set_clean_cell_text(
        t0.rows[36].cells[11],
        "Jan 2027 / Feb 2027\n\n"
        "Jan 2027 / Feb 2027\n\n"
        "Aug 2027 / Feb 2027\n\n"
        "Aug 2027 / Feb 2027",
        font_size_pt=8
    )

    # Insert clean tables from master standalone tables document
    standalone_docx = os.path.join(DESKTOP_DIR, f"Tables OOS-{OOS_ID} {CLIENT_NAME} - USP71.docx")
    if os.path.exists(standalone_docx):
        doc_tables_src = docx.Document(standalone_docx)
        if len(tpl.docx.tables) >= 3 and len(doc_tables_src.tables) >= 2:
            t2_elem = tpl.docx.tables[1]._element
            p2_parent = t2_elem.getparent()
            idx2 = p2_parent.index(t2_elem)
            p2_parent.remove(t2_elem)
            new_t1_elem = copy.deepcopy(doc_tables_src.tables[0]._element)
            p2_parent.insert(idx2, new_t1_elem)

            t3_elem = tpl.docx.tables[2]._element
            p3_parent = t3_elem.getparent()
            idx3 = p3_parent.index(t3_elem)
            p3_parent.remove(t3_elem)
            new_t2_elem = copy.deepcopy(doc_tables_src.tables[1]._element)
            p3_parent.insert(idx3, new_t2_elem)

            if len(doc_tables_src.tables) >= 3:
                p_t3_heading = parse_xml(
                    '<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
                    '<w:pPr><w:spacing w:before="240" w:after="160"/>'
                    '<w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:b/><w:u w:val="single"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:pPr>'
                    '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:b/><w:u w:val="single"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr>'
                    '<w:t>Table 3: Environmental Monitoring from Processing Performed on 15Sep26</w:t></w:r></w:p>'
                )
                new_t3_elem = copy.deepcopy(doc_tables_src.tables[2]._element)
                p3_parent.insert(idx3 + 1, p_t3_heading)
                p3_parent.insert(idx3 + 2, new_t3_elem)

    out_docx_desktop = os.path.join(DESKTOP_DIR, f"OOS-{OOS_ID} {CLIENT_NAME} - USP71.docx")
    out_docx_docs = os.path.join(DOCUMENTS_DIR, f"OOS-{OOS_ID} {CLIENT_NAME} - USP71.docx")
    tpl.save(out_docx_desktop)
    tpl.save(out_docx_docs)
    print("Master Word Report saved to Desktop & Documents:", out_docx_desktop)

# -------------------------------------------------------------
# 3. Build Official PDF Form (CORP-FORM-21)
# -------------------------------------------------------------
def build_official_pdf_form():
    base_pdf = os.path.join(OOS_ROOT, "CORP-FORM-21 Laboratory OOS Investigation Form (v11.1).pdf")
    doc = fitz.open(base_pdf)
    
    smart_consumables_text = (
        "Process Consumables:\r"
        "Information is available in EagleTrax Sample Consumables section\r \r"
        "Environmental Plates:\r"
        "TSA and Surface Plate: see attached environmental logs\r \r"
        "Monthly Cleaning:\r"
        "H2O2 strips and IPA: See attached monthly cleaning logs"
    )
    
    pdf_values = {
        # Page 1
        'Text Field0': f"{ORIG_PROCESSOR} (written by: Qiyue Chen)",
        'Date Field0': ORIG_PROCESS_DATE,
        'Date Field1': ORIG_READ_DATE,
        'Date Field2': ORIG_READ_DATE,
        'Text Field1': "USP <71> / EP 2.6.1 Sterility Test",
        'Text Field2': ORIG_SAMPLE_ID,
        'Text Field3': (
            f"Prepping Analyst:\r{ORIG_PREPPER} ({ORIG_PREPPER_INIT})\r \r"
            f"Processing Analyst:\r{ORIG_PROCESSOR} ({ORIG_PROCESSOR_INIT})\r \r"
            f"Reading Analyst:\r{ORIG_READER} ({ORIG_READER_INIT})"
        ),
        'Text Field4': SAMPLE_NAME,
        'Text Field5': DOSAGE_FORM,
        'Text Field6': LOT_NUMBER,
        'Text Field7': f"On {ORIG_READ_DATE}, sample {ORIG_SAMPLE_ID} was found positive for viable microorganisms after USP <71> sterility testing.",
        'Text Field8': "MICRO-SOP-5",
        'Text Field9': "24Jul2026",
        'Text Field10': "19",
        'Text Field11': "Pass/Fail",
        'Text Field12': "Kathan Parikh",
        'Date Field3': ORIG_READ_DATE,
        'Text Field13': f"Yes, analysts {ORIG_PREPPER}, {ORIG_PROCESSOR}, and {ORIG_READER} were comprehensively interviewed.",
        'Text Field14': f"Yes, sample ID: {ORIG_SAMPLE_ID}",
        'Text Field15': "Yes, as per MICRO-SOP-5",
        'Text Field16': "Yes, as per MICRO-SOP-5",
        'Text Field17': f"Yes, information is available on EagleTrax under {ORIG_SAMPLE_ID}",
        'Text Field18': "Yes, the analysts are trained and qualified by quality to perform the test",
        'Text Field19': "Not Applicable",
        'Text Field20': "Not Applicable",
        'Text Field21': f"Yes, the sample was stored as per client's instructions. Information is available in EagleTrax Sample Location History under {ORIG_SAMPLE_ID}",
        
        # Page 2
        'Text Field22': smart_consumables_text,
        'Text Field23': smart_consumables_text,
        'Text Field24': "Not applicable",
        'Text Field25': "Not applicable",
        'Text Field26': "Not applicable",
        'Text Field27': "Not applicable",
        'Text Field28': "Not applicable",
        'Text Field29': "Not applicable",
        'Text Field30': f"ISO 5 BSC {BSC_ID}",
        'Text Field31': BSC_CAL_DUE,
        'Text Field32': f"E001736 ({CR_ID})",
        'Text Field33': CR_CAL_DUE,
        'Text Field34': "Not applicable",
        'Text Field35': "Not applicable",
        'Text Field36': "Not applicable",
        'Text Field37': "Not applicable",
        'Text Field38': "Not applicable",
        'Text Field39': "Not applicable",
        'Text Field40': "See Phase I Summary",
        'Text Field41': "See Phase I Summary",
        'Text Field42': "See Phase I Summary",
        'Text Field43': (
            "Incubator E001356 (Sensor E001450)\r \r"
            "Incubator E001357 (Sensor E001449)\r \r"
            "Incubator E001034 (Sensor E001501)\r \r"
            "Incubator E001031 (Sensor E001505)"
        ),
        'Text Field44': (
            "Jan 2027 / Feb 2027\r \r"
            "Jan 2027 / Feb 2027\r \r"
            "Aug 2027 / Feb 2027\r \r"
            "Aug 2027 / Feb 2027"
        ),
        'Text Field45': "See Phase I Summary",
        
        # Page 3
        'Text Field46': "Not applicable",
        'Text Field47': "Not applicable",
        'Text Field48': "N/A QYC 08Oct26",
        'Text Field49': text_field_49,
        
        # Page 4
        'Text Field50': text_field_50,
        
        # Page 5
        'Text Field51': text_field_51,
        
        # Page 6
        'Text Field52': "",
        'Text Field53': "Qiyue Chen",
        'Text Field54': "Robin Seymour"
    }
    
    # Checkbox state matching OOS-261987 P1
    cb_values = {
        # Page 1
        'Check Box0': 'Yes',
        'Check Box1': 'Yes',
        'Check Box2': 'Yes',
        'Check Box4': 'Yes',
        'Check Box7': 'Yes',
        'Check Box10': 'Yes',
        'Check Box13': 'Yes',
        'Check Box16': 'Yes',
        'Check Box19': 'Yes',
        'Check Box24': 'Yes',
        'Check Box27': 'Yes',
        'Check Box28': 'Yes',
        'Check Box32': 'Yes',
        'Check Box34': 'Yes',
        'Check Box38': 'Yes',
        
        # Page 2
        'Check Box42': 'Yes',
        'Check Box43': 'Yes',
        'Check Box48': 'Yes',
        'Check Box51': 'Yes',
        'Check Box52': 'Yes',
        'Check Box55': 'Yes',
        'Check Box60': 'Yes',
        'Check Box63': 'Yes',
        'Check Box66': 'Yes',
        'Check Box67': 'Yes',
        'Check Box70': 'Yes',
        'Check Box73': 'Yes',
        
        # Page 3
        'Check Box78': 'Yes',
        'Check Box79': 'Yes',
        
        # Page 6
        # Option 2: No, the OOS result is valid (Check Box88)
        'Check Box87': 'Off',
        'Check Box88': 'Yes',
        'Check Box89': 'Off',
        'Check Box90': 'Off',
        'Check Box91': 'Off',
        'Check Box92': 'Off',
    }
    
    for page in doc:
        for w in page.widgets():
            fn = w.field_name
            if fn == 'Text Field57':
                w.field_value = OOS_ID
                w.update()
            elif fn in pdf_values:
                w.field_value = pdf_values[fn]
                # Golden calibrated auto-fit font sizes
                if fn in ['Text Field49', 'Text Field50', 'Text Field51']:
                    w.text_fontsize = 9.2
                    w.text_font = "Helv"
                elif fn == 'Text Field3':
                    w.text_fontsize = 6.5
                elif fn == 'Text Field7':
                    w.text_fontsize = 8.0
                elif fn in ['Text Field13', 'Text Field14', 'Text Field15', 'Text Field16', 'Text Field17', 'Text Field21']:
                    w.text_fontsize = 7.5
                elif fn in ['Text Field22', 'Text Field23']:
                    w.text_fontsize = 5.5
                w.update()
            elif fn in cb_values:
                w.field_value = cb_values[fn]
                w.update()

    temp_form_pdf = os.path.join(OUTPUT_DIR, "temp_filled_p1_262098.pdf")
    doc.save(temp_form_pdf)
    doc.close()
    print("Filled 6-page Phase 1 form:", temp_form_pdf)
    
    # Append Master Tables PDF (Pages 7 & 8)
    tables_pdf = os.path.join(DESKTOP_DIR, f"Tables OOS-{OOS_ID} {CLIENT_NAME} - USP71.pdf")
    if not os.path.exists(tables_pdf):
        tables_pdf = os.path.join(DOCUMENTS_DIR, f"Tables OOS-{OOS_ID} {CLIENT_NAME} - USP71.pdf")
        
    writer = PdfWriter(clone_from=temp_form_pdf)
    if os.path.exists(tables_pdf):
        t_reader = PdfReader(tables_pdf)
        for p in t_reader.pages:
            writer.add_page(p)
        print("Appended Master Tables. Total pages:", len(writer.pages))
        
    out_pdf_desktop = os.path.join(DESKTOP_DIR, f"OOS-{OOS_ID} {CLIENT_NAME} - USP71.pdf")
    out_pdf_docs = os.path.join(DOCUMENTS_DIR, f"OOS-{OOS_ID} {CLIENT_NAME} - USP71.pdf")
    
    with open(out_pdf_docs, "wb") as f:
        writer.write(f)
    print("Master PDF saved to Documents:", out_pdf_docs)
    
    try:
        with open(out_pdf_desktop, "wb") as f:
            writer.write(f)
        print("Master PDF saved to Desktop:", out_pdf_desktop)
    except Exception as e:
        print("Desktop PDF copy note:", e)

if __name__ == "__main__":
    print("=== Building Corrected Phase 1 Deliverables for OOS-262098 (Original Test Only) ===")
    build_master_word_doc()
    build_official_pdf_form()
    print("Phase 1 deliverables built successfully!")
