import os, sys, shutil, copy
import docx
from docx.shared import Pt, Inches
from docx.oxml import parse_xml
from docxtpl import DocxTemplate

OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"
DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"

# Narrative blocks
p22 = (
    "All the analysts involved in the testing - the initial prepping analyst (Ishita Sharma), the initial processing analyst "
    "(Alex Saravia), the initial reading analyst (Elysse Nioupin), the retest prepping and reading analyst (Andrew Carrillo), "
    "and the retest processing analyst (Abayomi Odugbesi) - were interviewed comprehensively. Their answers are "
    "recorded throughout this document.\n\n"
    "INITIAL TEST UNDER SUBMISSION ETX-260902-0505:\n"
    "All analysts involved in the prepping, processing, and reading of the initial sample – Ishita Sharma, Alex Saravia, and Elysse Nioupin – "
    "were interviewed comprehensively. Upon arrival, the sample was stored in accordance with the Client’s instructions. "
    "Analysts verified the integrity of the sample throughout both preparation and processing stages. No leaks or turbidity were "
    "observed at any point, verifying sample integrity. All reagents and supplies mentioned in the material section above were "
    "stored according to the suppliers’ recommendations, and their integrity was visually verified before utilization. Moreover, "
    "all reagents and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing data "
    "generated by our comprehensive in-house continuous monitoring system. The cleanroom suite (CR 114) used for processing "
    "procedures comprises three interconnected sections: the innermost ISO 7 cleanroom (114B), which connects to the middle ISO 7 "
    "buffer room (114A), and then to the outermost ISO 8 anteroom (114). A positive air pressure system is maintained throughout "
    "the suite to ensure controlled, unidirectional airflow from 114B through 114A and into 114. The ISO 5 Biological Safety "
    "Cabinet (BSC) E001316, located in the innermost ISO 7 room, (114B), was used for initial sample processing steps. It was "
    "thoroughly cleaned and disinfected prior to each procedure in accordance with MICRO SOP-9 (Cleaning and Disinfecting Procedure "
    "for Microbiology). Additionally, BSC E001316 was certified and approved by both the Engineering and Quality Assurance teams. "
    "Initial sample processing was conducted in the ISO 5 BSC E001316 in the innermost ISO 7 room, (114B) by Alex Saravia on "
    "04 Sep 2026 as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p23 = (
    "On 04 Sep 2026, the sample vials for ETX-260902-0505 were received from Sample Submissions and brought into the Sterile "
    "Microbiology lab following multi-stage disinfection with acidified bleach (minimum 10-minute contact time at each transfer "
    "boundary). In ISO 5 BSC E001316, the containers were aseptically opened, and membrane filtration was performed (45 gm filtered "
    "per media across 3 vials) as per MICRO-SOP-5. Media bottles were transferred into designated incubators E001356 and E001357. On "
    "10 Sep 2026 (Day 6 of incubation), microbial growth was observed in 1 x 100mL TSB media bottle by analyst Elysse Nioupin and confirmed "
    "by supervisor Robin Seymour. The positive TSB bottle was submitted for Differential Staining and Microbial Identification under "
    "ETX-260910-0290, which definitively identified the isolate as Microbacterium sp. PM5 (Gram-positive rods). All concurrent negative "
    "controls for the membrane filtration method remained sterile (no growth).\n\n"
    "Upon analyzing environmental monitoring results, no microbial growth was detected on operator personnel fingertip touch plates, "
    "settling plates, or ISO 5 BSC surface contact plates on the date of testing (04 Sep 2026), the date before (03 Sep 2026), or the "
    "subsequent testing date (08 Sep 2026). Weekly active air monitoring of ISO 8 Room 114 recovered 2 CFUs (ETX-260914-0487, identified as "
    "Corynebacterium ureicelerivorans and Mycobacterium grossiae), which differed in morphology and genus from the sample isolate and was "
    "physically isolated within the outermost ISO 8 anteroom. Monthly cleaning and disinfection of Suite CR114 was performed on 30 Aug 2026 "
    "per MICRO-SOP-9 with all H2O2 indicators passing. All other samples processed in the same testing session tested negative, ruling out "
    "cross-contamination.\n\n"
    "During preliminary interview, the processing analyst noted a potential handling discrepancy during the resuspension of the lyophilized "
    "vials. In addition, the same sample lot (2608-216) had previously been submitted and passed sterility testing via ScanRDI under ETX-260807-0602. "
    "Based on these initial findings and to investigate whether the positive recovery was attributable to an inadvertent analyst handling error "
    "during resuspension, a Phase II investigation was initiated, and additional sample vials from the same lot were requested from the client for retesting."
)

p24 = (
    "PHASE II RETEST UNDER SUBMISSION ETX-260914-0470:\n"
    "In accordance with Phase II investigation procedures under Form 3.100.019.F02, additional sample vials from lot 2608-216 were submitted "
    "for retesting under submission ETX-260914-0470.\n\n"
    "The retest sample was prepared by Andrew Carrillo on 14 Sep 2026 and processed by Abayomi Odugbesi on 15 Sep 2026 in accordance with "
    "MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test) via membrane filtration (60 gm filtered across 4 vials). The retest was conducted in certified "
    "ISO 5 BSC E001314 within Cleanroom Suite 115 following standard multi-barrier disinfection and strict aseptic technique. All culture media "
    "(FTM Lot 2567320, TSB Lot 2567280) and reagents (Fluid D Lot 687774, Bacteriostatic Water Lot NM7681) were within valid expiration dates. "
    "Media bottles were incubated in designated incubators E001356 and E001357. Negative controls were handled concurrently and remained sterile.\n\n"
    "On 21 Sep 2026 (Day 06 of incubation), microbial growth was observed in 1 x 100mL TSB media bottle by analyst Andrew Carrillo and confirmed "
    "by supervisor Robin Seymour. The positive bottle was submitted for Microbial Identification under ETX-260921-0498. Confirmatory identification "
    "definitively identified the isolate as Microbacterium sp. PM5 (Gram-positive short rods), matching the identical species and strain designation (PM5), "
    "morphology (white shiny lawn growth), media selection (TSB), and incubation kinetics (Day 6) of the initial failure under ETX-260902-0505 "
    "(ETX-260910-0290). All other samples processed in the batch on 15 Sep 2026 tested negative.\n\n"
    "Upon analyzing environmental monitoring results for the retest processing on 15 Sep 2026, no microbial growth was detected on operator personnel "
    "fingertip touch plates, settling plates, or ISO 5 BSC surface contact plates on the date of testing (15 Sep 2026), the preceding testing date (14 Sep 2026), "
    "or the subsequent testing date (16 Sep 2026). Weekly active surface monitoring of Cleanroom Suite 115 showed no growth; weekly active air sampling in "
    "the outermost ISO 8 cleanroom 115 recovered 9 CFUs (ETX-260923-0402), identified as Kocuria indica, Brevibacterium sp. CS2, Corynebacterium sp, Micrococcus luteus, "
    "Paracoccus yeei, Staphylococcus hominis, and Kocuria rhizophila. 100% of these environmental isolates differed distinctly in genus and morphology from the product "
    "contamination isolate (Microbacterium sp. PM5). The ISO 5 critical zones in BSC E001314 remained completely sterile (0 CFU) and in optimal control throughout testing, "
    "with positive pressure cascades preventing anteroom air ingress. (Refer to Table 1 for sample details, Table 2 for environmental monitoring from processing "
    "performed on 04 Sep 2026, and Table 3 for environmental monitoring from processing performed on 15 Sep 2026).\n\n"
    "EVALUATION OF RETEST FINDINGS & JUSTIFICATION OF PRIOR SCANRDI RESULT:\n"
    "The successful replication of microbial recovery in the independent retest—conducted by a different processing analyst (Abayomi Odugbesi) "
    "in a different cleanroom suite (Cleanroom Suite 115 vs. Suite 114) and a different prepping/reading analyst (Andrew Carrillo)—conclusively "
    "refutes the preliminary hypothesis of analyst handling error during reconstitution. If the initial recovery had been an isolated artifact "
    "of analyst technique, the identical microorganism (Microbacterium sp. PM5) would not have been recovered on the identical incubation day in the retest.\n\n"
    "Importantly, the investigation evaluated why the prior rapid ScanRDI sterility test conducted on this lot (submission ETX-260807-0602, test record 081326-2017-2) "
    "yielded a passing result (Count 14/0, Pass). First, per EagleTrax records for ETX-260807-0602, only 1 single container (Number of Items in Batch: 1, 30 mL/gm) "
    "was submitted and tested via ScanRDI, whereas USP <71> compendial testing analyzed 3 vials (45 gm filtered per media) for initial test ETX-260902-0505 and 4 vials "
    "for retest ETX-260914-0470. Second, official records confirm that 'No Method Suitability on file' exists for ScanRDI with this specific peptide analyte formulation "
    "(Cagrilinitide / Retatrutide). Third, in compounded parenteral formulations, microbial contamination at low bioburden levels is well recognized to exhibit a non-uniform, "
    "heterogeneous distribution across individual batch containers. Under single-vial sampling (n = 1), random chance naturally selects a container devoid of viable cells—as "
    "occurred with the single vial tested under ETX-260807-0602—whereas multi-container sampling captures vials harboring viable cells. When viable cells were introduced into "
    "14-day compendial broth enrichment (USP <71> membrane filtration), the organisms were successfully enriched and recovered in TSB on Day 6 in both independent testing events "
    "(ETX-260902-0505 and ETX-260914-0470), yielding the identical strain (Microbacterium sp. PM5). Therefore, the passing ScanRDI result and the two failing USP <71> compendial "
    "results are scientifically consistent and attributable to non-uniform distribution of low-concentration microbial bioburden within the compounded lot. Consequently, "
    "inherent product contamination in Lot 2608-216 is confirmed, the initial failing result for ETX-260902-0505 is valid, retest ETX-260914-0470 is confirmed failing, "
    "and Lot 2608-216 fails sterility requirements."
)

p25 = (
    "Inherent product contamination in Lot 2608-216, confirmed by the replication of identical microbial recovery kinetics (Day 6 in TSB) and "
    "the identical strain (Microbacterium sp. PM5) in retest ETX-260914-0470. The discrepancy with the passing ScanRDI result (ETX-260807-0602) "
    "is scientifically attributed to non-uniform microbial distribution at low concentrations within the compounded batch. Original result confirmed valid."
)

data = {
    "sample_name": "GLP3R/Cagrilinitide",
    "retest_date": "15-Sep-2026",
    "smart_original_result_str": "Fail",
    "smart_retest_personnel_block": (
        "Prepping Analyst:\n"
        "Ishita Sharma (IS), Andrew Carrillo (AC)\n\n"
        "Processing Analyst:\n"
        "Alex Saravia (AS), Abayomi Odugbesi (AOD)\n\n"
        "Reading Analyst:\n"
        "Elysse Nioupin (EN), Andrew Carrillo (AC)"
    ),
    "smart_sample_id_block": "Original test:\nETX-260902-0505\n\nRetest:\nETX-260914-0470",
    "smart_retest_result_str": "Fail",
    "smart_retest_scan_id": "ISO 5 BSC E001316, ISO 5 BSC E001314",
    "smart_retest_bsc_list": "CR 114 (E001736) and CR 115",
    "smart_retest_suite_list": "Incubator E001356, E001357, E001034, E001031",
    "smart_phase1_summary_block": f"{p22}\n\n{p23}",
    "smart_phase2_narrative_block": f"{p24}\n\n{p25}"
}

tpl_path = os.path.join(OOS_ROOT, "ScanRDI OOS P2 template.docx")
doc_tpl = DocxTemplate(tpl_path)
doc_tpl.render(data)

# Embed Table 1, Table 2, and Table 3 with Headings from Phase II Table docx
table_docx_path = os.path.join(OUTPUT_DIR, "Tables OOS-262098 Solyn LLC (E75000) - Phase II.docx")
if os.path.exists(table_docx_path):
    table_doc = docx.Document(table_docx_path)
    for element in table_doc._body._element:
        tag = element.tag.split('}')[-1]
        if tag in ['p', 'tbl']:
            doc_tpl.docx._body._element.append(copy.deepcopy(element))

out_doc_report = os.path.join(OUTPUT_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.docx")
doc_tpl.save(out_doc_report)
print("Saved Phase II Master Word Report to:", out_doc_report)

# Sync Word report to Desktop and Documents
desktop_docx = os.path.join(DESKTOP_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.docx")
doc_docx = os.path.join(DOCUMENTS_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.docx")
shutil.copy2(out_doc_report, desktop_docx)
shutil.copy2(out_doc_report, doc_docx)
print("Synced Phase II Word report to Desktop and Documents:", desktop_docx)
