"""
Script: process_oos_262080.py
Purpose: Complete generation of Celsis OOS-262080 report files and tables.
"""

import os
import sys
import shutil
from datetime import datetime
import fitz  # PyMuPDF
from docxtpl import DocxTemplate
from docx.shared import Pt
from docx.oxml import parse_xml
from docx.opc.constants import RELATIONSHIP_TYPE
import win32com.client
import gc

sys.stdout.reconfigure(encoding='utf-8')

SAMPLE_URL = "https://etrax.eagleanalytical.com/SubmissionTest/Details/jzraMOOTFYUFD%24erkwgubw__"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"

# 1. NARRATIVE TEXT
p1 = (
    "All analysts involved in the preparation, processing, aliquoting, and reading of the samples, "
    "Andrew Carrillo, Gabrielle Surber, America Alanis, and Cuong Du, were interviewed comprehensively. "
    "Their responses are documented throughout this report. "
    "This investigation was performed as per MICRO-SOP-53 Sterility Test Out-of-Specification (OOS) Investigation Procedure."
)

p2 = (
    "Upon arrival, the sample was stored refrigerated in accordance with the client instructions. Both sample "
    "prepping analyst Andrew Carrillo and processing analyst Gabrielle Surber inspected the sample during preparation "
    "and processing. No leaks or visible turbidity were observed, and no evidence of compromised container "
    "integrity was identified."
)

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to supplier "
    "recommendations, and their integrity was visually verified before utilization. Moreover, all reagents "
    "and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing "
    "data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The cleanroom suite used for processing procedures (CR114) comprises three interconnected sections: "
    "the innermost ISO 7 cleanroom (114B), which connects to the middle ISO 7 buffer room (114A), and then "
    "to the outermost ISO 8 anteroom (114). A positive air pressure system is maintained throughout the suite "
    "to ensure controlled, unidirectional airflow from 114B through 114A and into 114."
)

p5 = (
    "The innermost ISO 7 cleanroom 114B and its ISO 5 BSC E001316 were thoroughly cleaned and prepared before "
    "initiating testing by analyst Gabrielle Surber as per MICRO-SOP-2 (Environmental Monitoring of the Clean "
    "Room Facility) and MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). For Celsis "
    "aliquoting, intermediate ISO 7 buffer room 114A and its ISO 5 BSC E001798 were thoroughly cleaned and "
    "prepared by analyst Cuong Du before initiating testing as per MICRO-SOP-44 and MICRO-SOP-9. Both BSCs, "
    "E001316 in 114B and E001798 in 114A, were certified and approved by the Engineering and Quality Assurance "
    "teams prior to use."
)

p6 = (
    "On 01 Sep 2026, the sample vials for ETX-260828-0527 were received from the Sample Submissions team and brought "
    "into the Sterile Microbiology lab. Upon arrival, each vial was sprayed with an acidified bleach disinfectant, "
    "placed into pre-disinfected bins, and allowed a 10-minute contact time. Secondary disinfection was performed in "
    "the ISO 8 anteroom (114), where the vials were again treated with acidified bleach with a 10-minute contact time "
    "before transfer into cleanroom 114B. Inside 114B, processing analyst Gabrielle Surber performed a final disinfection "
    "step with a 10-minute contact time. Once fully disinfected, the vials were transferred into the ISO 5 BSC E001316, "
    "placed on the disinfected work surface, aseptically opened, and tested in accordance with MICRO-SOP-44. Direct "
    "inoculation was performed by adding 25 mL of sample per media container, using five 300 mL FTM jars and five 300 mL "
    "TSB jars. In accordance with suitability method record 2601120497, one gram of Bovine Serum Albumin was prepared in "
    "100 mL of PBS, and 5 mL of this solution was added to each jar. Following testing, the media bottles were transferred "
    "into incubators E001356 and E001357 to initiate incubation."
)

p7 = (
    "Upon completion of incubation on 08 Sep 2026, the media bottles for ETX-260828-0527 were disinfected and transferred "
    "to the middle ISO 7 buffer room (114A) for the aliquoting step per MICRO-SOP-44 (Celsis Sterility Testing). In "
    "cleanroom 114A, the media bottles were disinfected one more time before transfer into the ISO 5 BSC E001798 located "
    "in cleanroom 114A. In ISO 5 BSC E001798, the sample was aliquoted into assay cuvettes by analyst Cuong Du. Following "
    "aliquoting, Celsis Sterility Reading was performed in accordance with MICRO-SOP-44 by analyst America Alanis."
)

p8 = (
    "Following the reading, sample ETX-260828-0527 was found to yield a positive reading in one of the 300 mL FTM media jars "
    "(ETX-260828-0527-3/5). The average Relative Luminescence Units (RLU) from the duplicate reading tube, originating from "
    "the FTM sample bottle, yielded 7,190 RLU, which exceeded the method cutoff of 2,955 RLU, where the FTM negative control "
    "was 985 RLU. All other FTM and TSB sample bottles in the same batch tested negative. The %CV from the duplicate reading tubes "
    "for the positive FTM bottles was well within the specification (< 30%). Additionally, all Daily Controls, including the "
    "Instrument Blank, Reagent Blank, and ATP Positive Control, were within the defined specifications, each with a %CV below 30%."
)

p9 = (
    "Following the OOS result, the positive FTM bottle for ETX-260828-0527 was submitted for Differential Staining and "
    "Microbial Identification under ETX-260908-0593. No microbial growth was recovered by subculture, with zero CFU observed "
    "on the plate as shown in Table 1, and no cellular morphology was visualized by differential staining. Therefore, no organism "
    "was recovered for identification or further microbiological comparison. The lack of recovery on subculture does not "
    "invalidate the initial analytical Celsis result and may be consistent with low-level or stressed microbial cells under the "
    "test conditions, though a specific physiological state could not be confirmed."
)

p10 = (
    "The culture media utilized were within their expiry period. The negative culture media bottles for the direct inoculation "
    "method for the original culture were handled, processed, and incubated in a manner identical to that of actual samples. No "
    "microbial growth was observed in the corresponding negative control."
)

p11 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 "
    "cleanroom, and its containing ISO 5 Biosafety Cabinets for CR114 was performed on 30 Aug 2026, as per MICRO-SOP-9 "
    "(Cleaning and Disinfecting Procedure for Microbiology). It was documented that all H2O2 indicators passed. This confirms "
    "the efficient monthly cleaning of all three parts of Cleanroom 114."
)

p12 = (
    "Attached Tables 2 and 3 present the environmental monitoring results for the duration of testing. The environmental "
    "monitoring (EM) plates were incubated for no less than 48 hours at 30-35°C and no less than an additional five days at "
    "20-25°C as per MICRO-SOP-2 (Environmental Monitoring of the Cleanroom Facility). Table 2 pertains to Environmental "
    "Monitoring performed during Celsis Sterility Processing, and Table 3 pertains to Environmental Monitoring performed during "
    "Celsis Sterility Aliquoting."
)

p13 = (
    "A review of the Environmental Monitoring (EM) results for the relevant Celsis Sterility processing period showed no "
    "microbial growth on personnel monitoring plates, settling plates, or ISO 5 BSC E001316 surface sampling plates on the date "
    "of testing (01Sep2026), the preceding sampling date (31Aug2026), or the subsequent sampling date (02Sep2026). Weekly active "
    "air and surface sampling of the cleanroom suite associated with processing was performed on 04Sep2026. No microbial recovery "
    "was observed from weekly surface sampling of the cleanroom suite. Active air sampling showed recovery of 1 CFU (ETX-260914-0487) "
    "in the ISO 8 area, identified as Gram-positive coccobacilli and Gram-positive rods, with zero recovery observed in the ISO 7 "
    "buffer or cleanrooms."
)

p14 = (
    "After reviewing the Environmental Monitoring (EM) results for the relevant Celsis Sterility aliquoting period, "
    "no microbial growth was observed on personnel monitoring plates, ISO 5 BSC E001798 surface sampling plates, or settling "
    "plates on the date of aliquoting (08Sep2026), the preceding sampling date (07Sep2026), or the subsequent sampling date "
    "(09Sep2026). Weekly active air sampling of the cleanroom suite performed on 10Sep2026 showed recovery of 1 CFU "
    "(ETX-260921-0520) in the ISO 8 area, identified as Gram-positive cocci, with zero recovery in the ISO 7 buffer or cleanrooms, "
    "and weekly surface sampling of the cleanroom suite showed no growth."
)

p15 = (
    "Evaluation of Environmental Monitoring Results: It is important to note that, for both processing and aliquoting activities, "
    "the samples are processed within validated ISO 5 BSCs (E001316 and E001798 respectively). Although microbial recovery was "
    "observed from weekly active air monitoring in the outermost ISO 8 room 114 background environment in cleanroom suite "
    "(CR114), these recoveries were not obtained from the ISO 5 processing environment or the ISO 7 cleanroom environment."
)

p16 = (
    "The absence of microbial recovery from both the processing and the aliquoting analyst glove plates, ISO 5 BSC surface "
    "monitoring plates, and ISO 5 settling plates indicates that no identifiable contamination transfer pathway existed between "
    "the monitored background cleanroom environment and the ISO 5 critical processing areas. Samples were also prepared and "
    "transferred into disinfected, lidded containers and transported on carts within the controlled cleanroom environment. "
    "Therefore, while the active air results demonstrate microbial recovery in the surrounding ISO 8 area, there is no evidence "
    "that the recovery originated from, or affected, the ISO 5 BSC environment where the test sample was handled and processed."
)

p17 = (
    "All analysts confirmed full compliance with cleaning procedures as outlined in MICRO-SOP-9 (Cleaning and Disinfecting "
    "Procedure for Microbiology) and MICRO-SOP-44 (Celsis Sterility Testing). A review of the available data confirms that "
    "the cleanroom and equipment conditions remained within acceptable parameters. No deviations or obvious signs of laboratory "
    "error during processing and aliquoting were noted from analysts."
)

p18 = (
    "No other sample processed by analyst Gabrielle Surber on 01 Sep 2026 and aliquoted by analyst Cuong Du on 08 Sep 2026, "
    "failed Celsis Sterility testing that day. To assess the potential for sample-to-sample contamination contributing to the "
    "positive results, a comprehensive review was conducted of all samples processed in the same batch. All other samples "
    "processed by the same analyst on the day of testing were found to test negative for microbial growth. These findings "
    "suggest that cross-contamination between samples is unlikely."
)

p19 = (
    'Analyzing a 6-month sample history for Optimal Balance Pharmacy indicates, this specific analyte "MOTs-C 10 MG/ML (5 ML) '
    'Injection" has had no prior failures using the Celsis Sterility testing during this period.'
)

p21 = (
    "Based on the laboratory investigation, no assignable laboratory cause was identified involving the analyst, instrument, "
    "reagents, supplies, or monitored laboratory environment. The initial Celsis OOS result therefore remains valid in "
    "accordance with the applicable laboratory OOS procedure."
)

text_field_49 = "\n\n".join([p1, p2, p3, p4, p5])
text_field_50 = "\n\n".join([p6, p7, p8, p9, p10, p11, p12])
text_field_51 = "\n\n".join([p13, p14, p15, p16, p17, p18, p19, p21])

smart_phase1_full = "\n\n".join([
    p1, p2, p3, p4, p5, p6, p7, p8, p9, p10,
    p11, p12, p13, p14, p15, p16, p17, p18, p19, p21
])

# ==========================================
# 2. RENDER WORD DOCUMENTS
# ==========================================
print("\n--- [1/4] Rendering Word Documents ---")

# A. Tables Word Document
table_context = {
    "sample_id": "ETX-260828-0527",
    "analyst_name": "Gabrielle Surber",
    "aliquoting_name": "Cuong Du",
    "positive_id": "ETX-260908-0593",
    "positive_media": "1 x 300mL FTM",
    "positive_org": "No growth was obtained",
    
    # Processing Phase (01Sep26)
    "process_date": "01Sep26",
    "pro_analyst_initial": "GS",
    "pro_before_test": "31Aug26",
    "pro_test_date": "01Sep26",
    "pro_after_test": "02Sep26",
    "pro_date_of_weekly": "04Sep26",
    
    "pro_be_obs_pers_dur_pro": "No growth", "pro_be_etx_pers_dur_pro": "N/A", "pro_be_id_pers_dur_pro": "N/A",
    "pro_obs_pers_dur_pro": "No growth",    "pro_etx_pers_dur_pro": "N/A",    "pro_id_pers_dur_pro": "N/A",
    "pro_af_obs_pers_dur_pro": "No growth", "pro_af_etx_pers_dur_pro": "N/A", "pro_af_id_pers_dur_pro": "N/A",
    
    "pro_be_obs_surf_dur_pro": "No growth", "pro_be_etx_surf_dur_pro": "N/A", "pro_be_id_surf_dur_pro": "N/A",
    "pro_obs_surf_dur_pro": "No growth",    "pro_etx_surf_dur_pro": "N/A",    "pro_id_surf_dur_pro": "N/A",
    "pro_af_obs_surf_dur_pro": "No growth", "pro_af_etx_surf_dur_pro": "N/A", "pro_af_id_surf_dur_pro": "N/A",
    
    "pro_be_obs_sett_dur_pro": "No growth", "pro_be_etx_sett_dur_pro": "N/A", "pro_be_id_sett_dur_pro": "N/A",
    "pro_obs_sett_dur_pro": "No growth",    "pro_etx_sett_dur_pro": "N/A",    "pro_id_sett_dur_pro": "N/A",
    "pro_af_obs_sett_dur_pro": "No growth", "pro_af_etx_sett_dur_pro": "N/A", "pro_af_id_sett_dur_pro": "N/A",
    
    "pro_obs_air_wk_of": "1 CFU (ISO 8 114)", "pro_etx_air_wk_of": "ETX-260914-0487", "pro_id_air_wk_of": "Gram (+) coccobacilli & Gram (+) rods",
    "pro_obs_room_wk_of": "No growth",        "pro_etx_room_wk_of": "N/A",             "pro_id_room_wk_of": "N/A",
    
    # Aliquoting Phase (08Sep26)
    "alq_analyst_initial": "ALA/CCD",
    "alq_before_test": "07Sep26",
    "alq_test_date": "08Sep26",
    "alq_after_test": "09Sep26",
    "alq_date_of_weekly": "10Sep26",
    
    "alq_be_obs_pers_dur_pro": "No growth", "alq_be_etx_pers_dur_pro": "N/A", "alq_be_id_pers_dur_pro": "N/A",
    "alq_obs_pers_dur_pro": "No growth",    "alq_etx_pers_dur_pro": "N/A",    "alq_id_pers_dur_pro": "N/A",
    "alq_af_obs_pers_dur_pro": "No growth", "alq_af_etx_pers_dur_pro": "N/A", "alq_af_id_pers_dur_pro": "N/A",
    
    "alq_be_obs_surf_dur_pro": "No growth", "alq_be_etx_surf_dur_pro": "N/A", "alq_be_id_surf_dur_pro": "N/A",
    "alq_obs_surf_dur_pro": "No growth",    "alq_etx_surf_dur_pro": "N/A",    "alq_id_surf_dur_pro": "N/A",
    "alq_af_obs_surf_dur_pro": "No growth", "alq_af_etx_surf_dur_pro": "N/A", "alq_af_id_surf_dur_pro": "N/A",
    
    "alq_be_obs_sett_dur_pro": "No growth", "alq_be_etx_sett_dur_pro": "N/A", "alq_be_id_sett_dur_pro": "N/A",
    "alq_obs_sett_dur_pro": "No growth",    "alq_etx_sett_dur_pro": "N/A",    "alq_id_sett_dur_pro": "N/A",
    "alq_af_obs_sett_dur_pro": "No growth", "alq_af_etx_sett_dur_pro": "N/A", "alq_af_id_sett_dur_pro": "N/A",
    
    "alq_obs_air_wk_of": "1 CFU (ISO 8 114)", "alq_etx_air_wk_of": "ETX-260921-0520", "alq_id_air_wk_of": "Gram (+) cocci",
    "alq_obs_room_wk_of": "No growth",        "alq_etx_room_wk_of": "N/A",             "alq_id_room_wk_of": "N/A",
}

tables_docx_path = os.path.join(DESKTOP_DIR, "Celsis table OOS-262080.docx")
tables_docx_scratch = os.path.join(SCRIPT_DIR, "Celsis table OOS-262080.docx")
tpl_tables = DocxTemplate(os.path.join(ROOT_DIR, "tables for celsis.docx"))
tpl_tables.render(table_context)
tpl_tables.save(tables_docx_scratch)

# Add neat page break before Table 3 so Table 3 starts cleanly on Page 2
doc_t_mod = docx.Document(tables_docx_scratch)
for p in doc_t_mod.paragraphs:
    if "Table 3:" in p.text:
        p.paragraph_format.page_break_before = True

def set_cell_text(cell, text):
    if cell.paragraphs and cell.paragraphs[0].runs:
        cell.paragraphs[0].runs[0].text = text
        for r in cell.paragraphs[0].runs[1:]:
            r.text = ""
    else:
        cell.text = text

def set_cell_hyperlink(cell, url, text):
    import docx
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    part = p.part
    r_id = part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink_xml = (
        f'<w:hyperlink xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        f'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
        f'r:id="{r_id}" w:history="1">'
        f'<w:r>'
        f'<w:rPr>'
        f'<w:rStyle w:val="Hyperlink"/>'
        f'<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        f'<w:color w:val="0000FF"/>'
        f'<w:sz w:val="15"/>'
        f'<w:szCs w:val="15"/>'
        f'<w:u w:val="single"/>'
        f'</w:rPr>'
        f'<w:t>{text}</w:t>'
        f'</w:r>'
        f'</w:hyperlink>'
    )
    p._p.append(parse_xml(hyperlink_xml))
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

# Set clickable hyperlink on Table 1 (Table 0) Sample ID
set_cell_hyperlink(doc_t_mod.tables[0].rows[1].cells[2], SAMPLE_URL, "ETX-260828-0527")

# Surgically update Table 2 (Processing Phase) to match ground truth Suite 114 weekly records
t2 = doc_t_mod.tables[1]
# Row 13: Active Air Sampling of Cleanrooms on 04Sep26 by ISS
set_cell_text(t2.rows[13].cells[3], "04Sep26")
set_cell_text(t2.rows[13].cells[4], "ISS")
set_cell_text(t2.rows[13].cells[8], "1 CFU (ISO 8 114)")
set_cell_text(t2.rows[13].cells[9], "ETX-260914-0487")
set_cell_text(t2.rows[13].cells[10], "Gram (+) coccobacilli & Gram (+) rods")
set_cell_text(t2.rows[13].cells[11], "Gram (+) coccobacilli & Gram (+) rods")

# Row 15: Surface Sampling of Cleanrooms on 04Sep26 by ISS
set_cell_text(t2.rows[15].cells[3], "04Sep26")
set_cell_text(t2.rows[15].cells[4], "ISS")
set_cell_text(t2.rows[15].cells[8], "No growth")
set_cell_text(t2.rows[15].cells[9], "N/A")
set_cell_text(t2.rows[15].cells[10], "N/A")
set_cell_text(t2.rows[15].cells[11], "N/A")

# Surgically update Table 3 (Aliquoting Phase) to match ground truth PDF records
# Personnel follows CCD (03Sep26, 08Sep26, 15Sep26)
# Surface & Settling in BSC 1798 follows ALA (07Sep26), CCD (08Sep26), ALA (09Sep26)
t3 = doc_t_mod.tables[2]
table3_updates = {
    2: ("03Sep26", "CCD"),
    3: ("08Sep26", "CCD"),
    4: ("15Sep26", "CCD"),
    6: ("07Sep26", "ALA"),
    7: ("08Sep26", "CCD"),
    8: ("09Sep26", "ALA"),
    9: ("07Sep26", "ALA"),
    10: ("08Sep26", "CCD"),
    11: ("09Sep26", "ALA"),
}
for r_idx, (d_val, a_val) in table3_updates.items():
    row = t3.rows[r_idx]
    set_cell_text(row.cells[3], d_val)
    set_cell_text(row.cells[4], a_val)
    set_cell_text(row.cells[5], a_val)

set_cell_text(t3.rows[13].cells[3], "10Sep26")
set_cell_text(t3.rows[13].cells[4], "SMO")
set_cell_text(t3.rows[13].cells[8], "1 CFU (ISO 8 114)")
set_cell_text(t3.rows[13].cells[9], "ETX-260921-0520")
set_cell_text(t3.rows[13].cells[10], "Gram (+) cocci")
set_cell_text(t3.rows[13].cells[11], "Gram (+) cocci")

set_cell_text(t3.rows[15].cells[3], "10Sep26")
set_cell_text(t3.rows[15].cells[4], "SMO")
set_cell_text(t3.rows[15].cells[8], "No growth")
set_cell_text(t3.rows[15].cells[9], "N/A")
set_cell_text(t3.rows[15].cells[10], "N/A")
set_cell_text(t3.rows[15].cells[11], "N/A")

doc_t_mod.save(tables_docx_scratch)
try:
    doc_t_mod.save(tables_docx_path)
    print(f"Generated Tables DOCX: {tables_docx_path}")
except PermissionError:
    print(f"Warning: {tables_docx_path} is currently locked by Word. Saved to {tables_docx_scratch}.")

# B. Main Word Report
personnel_block = (
    "Prepping Analyst:\nAndrew Carrillo (AC)\n\n"
    "Processing Analyst:\nGabrielle Surber (GS)\n\n"
    "Aliquoting Analyst:\nCuong Du (CCD)\n\n"
    "Reading Analyst:\nAmerica Alanis (ALA)"
)

word_context = {
    "oos_id": "262080",
    "client_name": "Optimal Balance Pharmacy (E19193)",
    "sample_id": "ETX-260828-0527",
    "sample_name": "MOTs-C 10 MG/ML (5 ML) Injection",
    "lot_number": "LG342010349",
    "dosage_form": "Injection",
    "test_date": "08Sep26",
    "process_date": "01Sep26",
    "received_data": "28Aug26",
    "prepper_name": "Andrew Carrillo",
    "prepper_initial": "AC",
    "analyst_name": "Gabrielle Surber",
    "analyst_initial": "GS",
    "aliquoting_name": "Cuong Du",
    "aliquoting_initial": "CCD",
    "reading_name": "America Alanis",
    "reading_initial": "ALA",
    "reader_name": "America Alanis",
    "bsc_id": "1316",
    "cr_suit": "114",
    "smart_cr_id": "E001736 (CR 114)",
    "smart_scan_id": "E002222",
    "control_positive": "Celsis ATP Positive Control",
    "control_lot": "022601-1483",
    "control_data": "31 Jan 2027",
    "monthly_cleaning_date": "30 Aug 2026",
    "smart_personnel_block": personnel_block,
    "smart_incident_opening": "On 08Sep26, sample ETX-260828-0527 was found positive for viable microorganisms after Celsis sterility testing.",
    "smart_comment_interview": "Yes, Andrew Carrillo, Gabrielle Surber, America Alanis, and Cuong Du were interviewed comprehensively.",
    "smart_comment_samples": "Yes, Sample ID ETX-260828-0527",
    "smart_comment_records": "Not Applicable",
    "smart_comment_storage": "Yes, the sample was stored refrigerated as per client instructions. Information is available in EagleTrax Sample Location History under ETX-260828-0527",
    "report_header": "ETX-260828-0527\n\nOptimal Balance Pharmacy (E19193)",
    "analyst_signature": "America Alanis (Written by: Qiyue Chen)",
    "smart_phase1_summary": smart_phase1_full,
    "smart_phase1_continued": "",
    "event_number": "",
    "confirm_number": "",
    "organism_morphology": "No growth was obtained",
    "oos1_analyst_name": "N/A",
    "oos1_sample_id": "N/A",
    "oos1_sample_name": "N/A",
    "oos1_organism_morphology": "N/A",
}

main_docx_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.docx")
main_docx_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.docx")
tpl_main = DocxTemplate(os.path.join(ROOT_DIR, "Celsis OOS P1 template.docx"))
tpl_main.render(word_context)
tpl_main.save(main_docx_scratch)
doc_main_mod = docx.Document(main_docx_scratch)
if len(doc_main_mod.tables) > 1 and len(doc_main_mod.tables[1].rows) > 1:
    set_cell_hyperlink(doc_main_mod.tables[1].rows[1].cells[2], SAMPLE_URL, "ETX-260828-0527")
doc_main_mod.save(main_docx_scratch)
try:
    doc_main_mod.save(main_docx_path)
    print(f"Generated Main DOCX with Table 1 Hyperlink: {main_docx_path}")
except PermissionError:
    print(f"Notice: {main_docx_path} is locked, saved to {main_docx_scratch}")

# ==========================================
# 3. FILL FILLABLE PDF FORM
# ==========================================
print("\n--- [2/4] Filling AcroForm PDF Form ---")

pdf_template_path = os.path.join(ROOT_DIR, "Celsis OOS P1 template.pdf")
doc_pdf = fitz.open(pdf_template_path)

# Fill Page 1
page1 = doc_pdf[0]
for w in page1.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field0': w.field_value = 'America Alanis (Written by Qiyue Chen)'
    elif fn == 'Date Field0': w.field_value = '01-Sep-2026'
    elif fn == 'Date Field1': w.field_value = '08-Sep-2026'
    elif fn == 'Date Field2': w.field_value = '08-Sep-2026'
    elif fn == 'Text Field1': w.field_value = 'Celsis Sterility Test'
    elif fn == 'Text Field2': w.field_value = 'ETX-260828-0527'
    elif fn == 'Text Field3':
        w.field_value = (
            "Prepping Analyst:\r"
            "Andrew Carrillo (AC)\r \r"
            "Processing Analyst:\r"
            "Gabrielle Surber (GS)\r \r"
            "Aliquoting Analyst:\r"
            "Cuong Du (CCD)\r \r"
            "Reading Analyst:\r"
            "America Alanis (ALA)"
        )
    elif fn == 'Text Field4': w.field_value = 'MOTs-C 10 MG/ML (5 ML) Injection'
    elif fn == 'Text Field5': w.field_value = 'Injection'
    elif fn == 'Text Field6': w.field_value = 'LG342010349'
    elif fn == 'Text Field7':
        w.field_value = 'On 08 Sep 2026, sample ETX-260828-0527 was found to be positive for growth after Celsis Sterility Testing'
    elif fn == 'Text Field8': w.field_value = 'MICRO-SOP-44'
    elif fn == 'Text Field9': w.field_value = '03-Jan-2025'
    elif fn == 'Text Field10': w.field_value = '01'
    elif fn == 'Text Field11': w.field_value = 'Pass/Fail'
    elif fn == 'Text Field12': w.field_value = 'Kathan Parikh'
    elif fn == 'Date Field3': w.field_value = '08-Sep-2026'
    elif fn == 'Text Field13':
        w.field_value = 'Yes, analysts Andrew Carrillo, Gabrielle Surber, America Alanis & Cuong Du were comprehensively interviewed.'
    elif fn == 'Text Field14': w.field_value = 'Yes, Sample ID ETX-260828-0527'
    elif fn in ['Text Field15', 'Text Field16']: w.field_value = 'Yes, as per MICRO-SOP-44'
    elif fn == 'Text Field17':
        w.field_value = 'Yes, Information is available in EagleTrax under ETX-260828-0527'
    elif fn == 'Text Field18': w.field_value = 'Yes, all analysts are trained and qualified by the quality department to perform the test'
    elif fn in ['Text Field19', 'Text Field20']: w.field_value = 'Not Applicable'
    elif fn == 'Text Field21':
        w.field_value = "Yes, the sample was stored refrigerated as per client's instructions"
    elif fn.startswith('Check Box'):
        page1_yes_boxes = {
            'Check Box0', 'Check Box1', 'Check Box2',
            'Check Box4', 'Check Box7', 'Check Box10', 'Check Box13',
            'Check Box16', 'Check Box19', 'Check Box24', 'Check Box27',
            'Check Box28', 'Check Box32', 'Check Box34', 'Check Box38'
        }
        w.field_value = 'Yes' if fn in page1_yes_boxes else 'Off'
    w.update()

# Fill Page 2
page2 = doc_pdf[1]
reagents_lots = (
    "Materials and Reagents\r"
    "TSB: 06242026-1\r"
    "FTM: 06162026-2\r"
    "PBS: 35725002\r"
    "BSA: 245862\r \r"
    "Celsis Reagents & Kits:\r"
    "Please refer to attached packet\r \r"
    "TSA / Surface Plates: See EM logs\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: 250409\r"
    "IPA: 01600581"
)

reagents_exp = (
    "Materials and Reagents\r"
    "TSB: 22 Sep 2026\r"
    "FTM: 14 Sep 2026\r"
    "PBS: 31 Dec 2027\r"
    "BSA: 23 Jan 2028\r \r"
    "Celsis Reagents & Kits:\r"
    "Please refer to attached packet\r \r"
    "TSA / Surface Plates: See EM logs\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: Apr 2027\r"
    "IPA: Sep 2027"
)

incubator_list = (
    "Incubator E001356 (Sensor E001450)\r \r"
    "Incubator E001357 (Sensor E001449)\r \r"
    "Incubator E001034 (Sensor E001501)\r \r"
    "Incubator E001031 (Sensor E001505)"
)

incubator_cal = (
    "Jan 2027 / Feb 2027\r \r"
    "Jan 2027 / Feb 2027\r \r"
    "Aug 2027 / Feb 2027\r \r"
    "Aug 2027 / Feb 2027"
)

for w in page2.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field22':
        w.field_value = reagents_lots
    elif fn == 'Text Field23':
        w.field_value = reagents_exp
    elif fn == 'Text Field24': w.field_value = 'Celsis ATP Positive Control'
    elif fn == 'Text Field25': w.field_value = '022601-1483'
    elif fn == 'Text Field26': w.field_value = '31 Jan 2027'
    elif fn in ['Text Field27', 'Text Field28', 'Text Field29']: w.field_value = 'Not Applicable '
    elif fn == 'Text Field30': w.field_value = 'E002222'
    elif fn == 'Text Field31': w.field_value = 'Sep 2026'
    elif fn == 'Text Field32':
        w.field_value = 'E001736 (CR 114), BSC E001316\rE001736 (CR 114), BSC E001798'
    elif fn == 'Text Field33':
        w.field_value = 'Dec 2026, Jun 2027\rDec 2026, Jun 2027'
    elif fn == 'Text Field34': w.field_value = 'E002222'
    elif fn == 'Text Field35': w.field_value = 'Sep 2026'
    elif fn in ['Text Field36', 'Text Field37', 'Text Field38', 'Text Field39']: w.field_value = 'Not Applicable'
    elif fn in ['Text Field40', 'Text Field41', 'Text Field42', 'Text Field45']:
        w.field_value = 'See Phase I Summary'
    elif fn == 'Text Field43':
        w.field_value = incubator_list
    elif fn == 'Text Field44':
        w.field_value = incubator_cal
    elif fn.startswith('Check Box'):
        page2_yes_boxes = {
            'Check Box42', 'Check Box43', 'Check Box48', 'Check Box51',
            'Check Box52', 'Check Box55', 'Check Box58', 'Check Box63',
            'Check Box66', 'Check Box67', 'Check Box70', 'Check Box73'
        }
        w.field_value = 'Yes' if fn in page2_yes_boxes else 'Off'
    w.update()

# Fill Page 3
page3 = doc_pdf[2]
for w in page3.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn.startswith('Check Box'):
        w.field_value = 'Yes' if fn in {'Check Box78', 'Check Box79'} else 'Off'
    elif fn in ['Text Field46', 'Text Field47']: w.field_value = 'Not Applicable '
    elif fn == 'Text Field48': w.field_value = 'N/A QYC 08Sep2026'
    elif fn == 'Text Field49':
        w.field_value = text_field_49.replace('\n\n', '\r \r').replace('\n', '\r')
    w.update()

# Fill Page 4
page4 = doc_pdf[3]
for w in page4.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field50':
        w.text_fontsize = 10.5
        w.field_value = text_field_50.replace('₂', '2').replace('\n\n', '\r \r').replace('\n', '\r')
    w.update()

# Fill Page 5
page5 = doc_pdf[4]
for w in page5.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field51':
        w.text_fontsize = 10.5
        w.field_value = text_field_51.replace('\n\n', '\r \r').replace('\n', '\r')
    w.update()

# Fill Page 6
page6 = doc_pdf[5]
for w in page6.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn.startswith('Check Box'):
        w.field_value = 'Yes' if fn == 'Check Box88' else 'Off'
    elif fn == 'Text Field53': w.field_value = 'Qiyue Chen'
    elif fn == 'Text Field54': w.field_value = 'Robin Seymour'
    w.update()

main_pdf_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.pdf")
main_pdf_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.pdf")
doc_pdf.save(main_pdf_scratch)
doc_pdf.close()
try:
    shutil.copy2(main_pdf_scratch, main_pdf_path)
    print(f"Generated Main PDF: {main_pdf_path}")
except PermissionError:
    print(f"Notice: Desktop PDF {main_pdf_path} is currently open in Adobe Acrobat. Saved latest version to {main_pdf_scratch}")

# ==========================================
# 4. EXPORT TABLES DOCX TO PDF VIA WORD COM
# ==========================================
print("\n--- [3/4] Exporting Tables DOCX to PDF ---")
tables_pdf_path = os.path.join(DESKTOP_DIR, "Celsis table OOS-262080.pdf")
tables_pdf_scratch = os.path.join(SCRIPT_DIR, "Celsis table OOS-262080.pdf")

word = None
try:
    word = win32com.client.Dispatch("Word.Application")
    word.Visible = False
    source_docx = tables_docx_scratch if os.path.exists(tables_docx_scratch) else tables_docx_path
    doc_word = word.Documents.Open(source_docx)
    # wdExportFormatPDF = 17
    doc_word.ExportAsFixedFormat(tables_pdf_scratch, 17)
    doc_word.Close(False)
    try:
        shutil.copy2(tables_pdf_scratch, tables_pdf_path)
        print(f"Exported Tables PDF: {tables_pdf_path}")
    except PermissionError:
        print(f"Warning: {tables_pdf_path} is locked. PDF saved to {tables_pdf_scratch}")
except Exception as e:
    print(f"Word COM Export error: {e}")
finally:
    if word:
        try:
            word.Quit()
        except:
            pass
        del word
        gc.collect()

# ==========================================
# 5. ASSEMBLE COMBINED PACKAGE PDF
# ==========================================
print("\n--- [4/4] Creating Complete Combined PDF ---")
combined_pdf_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis (Complete).pdf")
combined_pdf_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis (Complete).pdf")

doc_main = fitz.open(main_pdf_scratch if os.path.exists(main_pdf_scratch) else main_pdf_path)
source_tables_pdf = tables_pdf_scratch if os.path.exists(tables_pdf_scratch) else tables_pdf_path
if os.path.exists(source_tables_pdf):
    doc_tables = fitz.open(source_tables_pdf)
    doc_main.insert_pdf(doc_tables, annots=True)
    doc_tables.close()

doc_main.save(combined_pdf_scratch)
try:
    doc_main.save(combined_pdf_path)
    print(f"Generated Combined Complete PDF: {combined_pdf_path}")
except PermissionError:
    print(f"Warning: {combined_pdf_path} is locked. Saved to {combined_pdf_scratch}")
doc_main.close()

print("SUCCESS: All 5 deliverables generated successfully!")
