"""
Script: process_oos_262080.py
Purpose: Complete generation of Celsis OOS-262080 report files and tables.
"""

import os
import sys
import shutil
from datetime import datetime
import fitz  # PyMuPDF
from docxtpl import DocxTemplate
import docx
import win32com.client
import gc

sys.stdout.reconfigure(encoding='utf-8')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"

# 1. NARRATIVE TEXT
p1 = (
    "All analysts involved in the prepping, processing, aliquoting, and reading of the samples – "
    "Andrew Carrillo (AC), Gabrielle Surber (GS), America Alanis (ALA) and Cuong Du (CCD) were "
    "interviewed comprehensively. Their answers are recorded throughout this document."
)

p2 = (
    "Upon arrival, the sample was stored in accordance with the Client’s instructions. "
    "Both the sample prepping analyst - Andrew Carrillo (AC) - and the processing analyst - "
    "Gabrielle Surber (GS) - verified the sample's integrity throughout both the preparation and "
    "processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the sample."
)

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to the "
    "suppliers’ recommendations, and their integrity was visually verified before utilization. "
    "Moreover, all reagents and supplies had valid expiration dates. The functionality of all equipment "
    "was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The sample was processed within the ISO 5 Biological Safety Cabinet (BSC), E001316, situated in the "
    "innermost cleanroom (114B), which connects to the intermediate ISO 7 buffer room (114A). This buffer "
    "room, in turn, leads to the outermost ISO 8 Anteroom (114). Furthermore, a positive air pressure system "
    "is maintained, ensuring airflow from the innermost ISO 7 cleanroom to the intermediate ISO 7 buffer room "
    "and finally to the outermost ISO 8 Anteroom."
)

p5 = (
    "The innermost ISO 7 cleanroom 114B and its ISO 5 BSC E001316 were thoroughly cleaned and prepared before "
    "initiating the testing by analyst Gabrielle Surber as per MICRO-SOP-2 (Environmental Monitoring of the Clean "
    "Room Facility), and MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). Similarly, for Celsis "
    "aliquoting, the ISO 7 cleanroom 114A and its ISO 5 BSC E001798 were thoroughly cleaned and prepared by analyst "
    "America Alanis before initiating the testing as per MICRO-SOP-44 and MICRO-SOP-9. Both the BSCs, E001316 in 114B "
    "and E001798 in 114A, were certified and approved by the Engineering and Quality Assurance teams prior to use."
)

p6 = (
    "On 01 Sep 2026, the sample vials for ETX-260828-0527 were received from the Sample Submissions team and brought "
    "into the Sterile Microbiology lab. Upon arrival, each sample vial was sprayed with an acidified bleach disinfectant, "
    "placed into pre-disinfected bins, and allowed a 10-minute contact time. The secondary disinfection happened in the "
    "ISO 8 anteroom (114), where the vials were again treated with acidified bleach with a 10-minute contact time before "
    "being transferred to the innermost ISO 7 cleanroom (114B). Inside 114B, the processing analyst, Gabrielle Surber, "
    "performed a final disinfection step with a 10-minute contact time. Once fully disinfected, the vials were transferred "
    "into the ISO 5 BSC E001316. Inside the BSC, the vials were placed on the disinfected work surface, aseptically opened, "
    "and tested in accordance with MICRO-SOP-44 (Celsis Sterility Testing). Direct inoculation was performed by adding 25 mL "
    "per media (5 x 300mL FTM jars and 5 x 300mL TSB jars; 1g of Bovine Serum Albumin in 100mL of PBS and 5mL added per "
    "suitability method 2601120497). Following testing, the media bottles were subsequently transferred into designated "
    "incubators, E001356 and E001357, to initiate incubation."
)

p7 = (
    "Upon completion of incubation on 08 Sep 2026, TSB & FTM bottles for ETX-260828-0527 were disinfected and transferred "
    "to the intermediate ISO 7 buffer room (114A) for the aliquoting step per MICRO-SOP-44 (Celsis Sterility Testing). "
    "In 114A, the media bottles were disinfected one more time before transferring them to the ISO 5 BSC E001798 located "
    "in cleanroom 114A. In ISO 5 BSC E001798, the sample was aliquoted into assay cuvettes by analyst America Alanis. "
    "After aliquoting, Celsis Sterility Reading was performed in accordance with MICRO-SOP-44 on Celsis instrument E002222 "
    "by analyst Cuong Du (CCD)."
)

p8 = (
    "Following the reading, sample ETX-260828-0527 was found to yield positive readings in two of the 300mL FTM media jars "
    "(jars #3 and #5). The average Relative Luminescence Units (RLU) from the duplicate reading tubes, originating from the "
    "FTM sample jars, yielded 7190 RLU, which exceeded the negative control cutoff (FTM negative control = 985 RLU), "
    "confirming a positive result. The TSB media jars tested negative with an RLU of 1500 (TSB cutoff = 2007 RLU, negative "
    "control = 669 RLU). All other FTM and TSB sample bottles in the same batch tested negative. The %CV from the duplicate "
    "reading tubes was within specification (< 30%). Additionally, all Daily Controls, including the Instrument Blank, "
    "Reagent Blank, and ATP Positive Control, were within the defined specifications, each with a %CV below 30%."
)

p9 = (
    "Following the OOS result, the positive FTM bottles for ETX-260828-0527 were submitted for Differential Staining and "
    "Microbial Identification under ETX-260908-0593. No microbial growth was recovered from the subculture (0 CFU on plate, "
    "see Table 1), and differential staining was inconclusive as no cell morphology could be visualized, indicating that the "
    "microorganism present in the sample was potentially viable but not culturable."
)

p10 = (
    "The culture media utilized were within their expiry period. The negative culture media bottles for the direct "
    "inoculation method for the original culture were handled, processed, and incubated in a manner identical to that "
    "of actual samples. No microbial growth was observed in the corresponding negative control."
)

p11 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 "
    "cleanroom, and its containing ISO 5 Biosafety Cabinets for Cleanroom 114 was performed on 30 Aug 2026, as per "
    "MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). During cleaning, it was documented that all "
    "H₂O₂ indicators passed. This confirms the efficient monthly cleaning of all three parts of Cleanroom 114."
)

p12 = (
    "Tables 2 & 3 (please see attached) present the environmental monitoring results for the duration of testing. The "
    "environmental monitoring (EM) plates were incubated for no less than 48 hours at 30-35°C and no less than an additional "
    "five days at 20-25°C as per MICRO-SOP-2 (Environmental Monitoring of the Cleanroom Facility). Table 2 pertains to "
    "Environmental Monitoring performed during Celsis Sterility Processing, and Table 3 pertains to Environmental Monitoring "
    "performed during Celsis Sterility Aliquoting."
)

p13 = (
    "Environmental Monitoring from Celsis Sterility Processing:\n"
    "A review of the Environmental Monitoring (EM) results for the relevant testing period showed no microbial growth on "
    "personnel monitoring plates, settling plates, or ISO 5 BSC (E001316) surface sampling plates on the date of testing "
    "(01Sep2026), the preceding sampling date (31Aug2026), or the subsequent sampling date (02Sep2026)."
)

p14 = (
    "Environmental Monitoring from Celsis Sterility Aliquoting:\n"
    "After reviewing the Environmental Monitoring (EM) results for the relevant aliquoting and reading dates, no microbial "
    "growth was observed on personnel monitoring plates for analyst CCD on the date of testing (08Sep2026), the preceding "
    "sampling date (03Sep2026), or the subsequent sampling date (15Sep2026). Similarly, ISO 5 BSC (E001798) surface sampling "
    "and settling plates demonstrated no microbial growth on the date of testing (08Sep2026, CCD), the preceding sampling date "
    "(07Sep2026, ALA), or the subsequent sampling date (09Sep2026, ALA)."
)

p15 = (
    "Weekly active air sampling of the cleanrooms, performed on 10Sep2026, recovered 1 CFU from the outermost ISO 8 anteroom "
    "(114) under ETX-260921-0520 (identification pending), while the intermediate ISO 7 buffer room (114A) and innermost "
    "ISO 7 cleanroom (114B) showed no microbial recovery (0 CFU). Weekly surface sampling across Suite 114 likewise showed "
    "no microbial recovery (0 CFU) across all locations (Table 114, Cart 114, Cart 114A, Floor 114A, Cart 114B, Floor 114B). "
    "All sample processing and aliquoting activities were performed within validated ISO 5 Biological Safety Cabinets (BSCs) "
    "E001316 and E001798, located in ISO 7 cleanrooms 114B and 114A, respectively.\n\n"
    "Furthermore, the test samples and media do not come into direct contact with the anteroom air or room surfaces at any stage "
    "of the testing process. Samples and media are prepared and transferred in disinfected, lidded containers and transported on "
    "carts within the controlled environments. Therefore, the single environmental monitoring recovery from the outermost ISO 8 "
    "anteroom (114) originated from an area that is physically segregated from the controlled ISO 5 environments where the test "
    "sample was handled and processed.\n\n"
    "The complete absence of microbial recovery from analyst glove plates, settling plates, and ISO 5 critical work surfaces "
    "throughout both processing and aliquoting indicates that no identifiable contamination transfer pathway existed between "
    "the room environment and the ISO 5 processing areas. Therefore, based on the absence of microbial recovery within the "
    "critical ISO 5 processing environments, satisfactory environmental monitoring results for personnel and critical surfaces, "
    "and the controlled processing conditions maintained throughout testing, the analyst or cleanroom environment is not "
    "considered a likely source of contamination for the sample."
)

p16 = (
    "All analysts confirmed full compliance with cleaning procedures as outlined in SOPs MICRO-SOP-9 (Cleaning and Disinfecting "
    "Procedure for Microbiology) and MICRO-SOP-44 (Celsis Sterility Testing). A review of the available data confirms that the "
    "cleanroom and equipment conditions remained within acceptable parameters. No deviations or obvious signs of laboratory "
    "error during processing and aliquoting were noted from analysts."
)

p17 = (
    "To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review "
    "was conducted of all samples processed on the same day. ETX-260828-0527 was the 1st sample processed in the batch by "
    "processing analyst - GS - on 01 Sep 2026. No other sample processed by GS on that date was found to be positive for microbial "
    "growth. A review of all other samples processed, incubated, aliquoted, and read within the same testing batch demonstrated "
    "no evidence of microbial growth. The absence of additional positive results within the batch confirms that cross-contamination "
    "between samples is unlikely during both the processing and the aliquoting steps."
)

p18 = (
    "An analysis of the six-month sample history for Optimal Balance Pharmacy (E19193) indicates that Eagle Analytical processed "
    "samples for Celsis Sterility testing with no prior occurrences of an out-of-specification or positive result for this analyte "
    "during this period."
)

p19 = (
    "A review of the lot history shows that there have been no additional submissions of sample lot: LG342010349 for retesting "
    "using Celsis Sterility Testing or any other sterility method."
)

p20 = (
    "Based on the observations outlined above, there is no clear indication that the contamination originated from reagents, "
    "supplies, the cleanroom environment, or the analyst. Therefore, the results are considered valid, and the likelihood of "
    "laboratory error is minimal."
)

text_field_49 = "\n\n".join([p1, p2, p3, p4, p5])
text_field_50 = "\n\n".join([p6, p7, p8, p9, p10, p11, p12])
text_field_51 = "\n\n".join([p13, p14, p15, p16, p17, p18, p19, p20])

smart_phase1_full = "\n\n".join([
    p1, p2, p3, p4, p5, p6, p7, p8, p9, p10,
    p11, p12, p13, p14, p15, p16, p17, p18, p19, p20
])

# ==========================================
# 2. RENDER WORD DOCUMENTS
# ==========================================
print("\n--- [1/4] Rendering Word Documents ---")

# A. Tables Word Document
table_context = {
    "sample_id": "ETX-260828-0527",
    "analyst_name": "Gabrielle Surber",
    "aliquoting_name": "America Alanis",
    "positive_id": "ETX-260908-0593",
    "positive_media": "2 x 300mL FTM",
    "positive_org": "No growth was obtained",
    
    # Processing Phase (01Sep26)
    "process_date": "01Sep26",
    "pro_analyst_initial": "GS",
    "pro_before_test": "31Aug26",
    "pro_test_date": "01Sep26",
    "pro_after_test": "02Sep26",
    "pro_date_of_weekly": "03Sep26",
    
    "pro_be_obs_pers_dur_pro": "No growth", "pro_be_etx_pers_dur_pro": "N/A", "pro_be_id_pers_dur_pro": "N/A",
    "pro_obs_pers_dur_pro": "No growth",    "pro_etx_pers_dur_pro": "N/A",    "pro_id_pers_dur_pro": "N/A",
    "pro_af_obs_pers_dur_pro": "No growth", "pro_af_etx_pers_dur_pro": "N/A", "pro_af_id_pers_dur_pro": "N/A",
    
    "pro_be_obs_surf_dur_pro": "No growth", "pro_be_etx_surf_dur_pro": "N/A", "pro_be_id_surf_dur_pro": "N/A",
    "pro_obs_surf_dur_pro": "No growth",    "pro_etx_surf_dur_pro": "N/A",    "pro_id_surf_dur_pro": "N/A",
    "pro_af_obs_surf_dur_pro": "No growth", "pro_af_etx_surf_dur_pro": "N/A", "pro_af_id_surf_dur_pro": "N/A",
    
    "pro_be_obs_sett_dur_pro": "No growth", "pro_be_etx_sett_dur_pro": "N/A", "pro_be_id_sett_dur_pro": "N/A",
    "pro_obs_sett_dur_pro": "No growth",    "pro_etx_sett_dur_pro": "N/A",    "pro_id_sett_dur_pro": "N/A",
    "pro_af_obs_sett_dur_pro": "No growth", "pro_af_etx_sett_dur_pro": "N/A", "pro_af_id_sett_dur_pro": "N/A",
    
    "pro_obs_air_wk_of": "No growth",  "pro_etx_air_wk_of": "N/A",  "pro_id_air_wk_of": "N/A",
    "pro_obs_room_wk_of": "No growth", "pro_etx_room_wk_of": "N/A", "pro_id_room_wk_of": "N/A",
    
    # Aliquoting Phase (08Sep26)
    "alq_analyst_initial": "ALA/CCD",
    "alq_before_test": "07Sep26",
    "alq_test_date": "08Sep26",
    "alq_after_test": "09Sep26",
    "alq_date_of_weekly": "10Sep26",
    
    "alq_be_obs_pers_dur_pro": "No growth", "alq_be_etx_pers_dur_pro": "N/A", "alq_be_id_pers_dur_pro": "N/A",
    "alq_obs_pers_dur_pro": "No growth",    "alq_etx_pers_dur_pro": "N/A",    "alq_id_pers_dur_pro": "N/A",
    "alq_af_obs_pers_dur_pro": "No growth", "alq_af_etx_pers_dur_pro": "N/A", "alq_af_id_pers_dur_pro": "N/A",
    
    "alq_be_obs_surf_dur_pro": "No growth", "alq_be_etx_surf_dur_pro": "N/A", "alq_be_id_surf_dur_pro": "N/A",
    "alq_obs_surf_dur_pro": "No growth",    "alq_etx_surf_dur_pro": "N/A",    "alq_id_surf_dur_pro": "N/A",
    "alq_af_obs_surf_dur_pro": "No growth", "alq_af_etx_surf_dur_pro": "N/A", "alq_af_id_surf_dur_pro": "N/A",
    
    "alq_be_obs_sett_dur_pro": "No growth", "alq_be_etx_sett_dur_pro": "N/A", "alq_be_id_sett_dur_pro": "N/A",
    "alq_obs_sett_dur_pro": "No growth",    "alq_etx_sett_dur_pro": "N/A",    "alq_id_sett_dur_pro": "N/A",
    "alq_af_obs_sett_dur_pro": "No growth", "alq_af_etx_sett_dur_pro": "N/A", "alq_af_id_sett_dur_pro": "N/A",
    
    "alq_obs_air_wk_of": "1 CFU (ISO 8 114)", "alq_etx_air_wk_of": "ETX-260921-0520", "alq_id_air_wk_of": "Pending",
    "alq_obs_room_wk_of": "No growth",        "alq_etx_room_wk_of": "N/A",             "alq_id_room_wk_of": "N/A",
}

tables_docx_path = os.path.join(DESKTOP_DIR, "Celsis table OOS-262080.docx")
tables_docx_scratch = os.path.join(SCRIPT_DIR, "Celsis table OOS-262080.docx")
tpl_tables = DocxTemplate(os.path.join(ROOT_DIR, "tables for celsis.docx"))
tpl_tables.render(table_context)
tpl_tables.save(tables_docx_scratch)

# Add neat page break before Table 3 so Table 3 starts cleanly on Page 2
doc_t_mod = docx.Document(tables_docx_scratch)
for p in doc_t_mod.paragraphs:
    if "Table 3:" in p.text:
        p.paragraph_format.page_break_before = True

def set_cell_text(cell, text):
    if cell.paragraphs and cell.paragraphs[0].runs:
        cell.paragraphs[0].runs[0].text = text
        for r in cell.paragraphs[0].runs[1:]:
            r.text = ""
    else:
        cell.text = text

# Surgically update Table 3 (Aliquoting Phase) to match ground truth PDF records
# Personnel follows CCD (03Sep26, 08Sep26, 15Sep26)
# Surface & Settling in BSC 1798 follows ALA (07Sep26), CCD (08Sep26), ALA (09Sep26)
t3 = doc_t_mod.tables[2]
table3_updates = {
    2: ("03Sep26", "CCD"),
    3: ("08Sep26", "CCD"),
    4: ("15Sep26", "CCD"),
    6: ("07Sep26", "ALA"),
    7: ("08Sep26", "CCD"),
    8: ("09Sep26", "ALA"),
    9: ("07Sep26", "ALA"),
    10: ("08Sep26", "CCD"),
    11: ("09Sep26", "ALA"),
}
for r_idx, (d_val, a_val) in table3_updates.items():
    row = t3.rows[r_idx]
    set_cell_text(row.cells[3], d_val)
    set_cell_text(row.cells[4], a_val)
    set_cell_text(row.cells[5], a_val)

doc_t_mod.save(tables_docx_scratch)
try:
    doc_t_mod.save(tables_docx_path)
    print(f"Generated Tables DOCX: {tables_docx_path}")
except PermissionError:
    print(f"Warning: {tables_docx_path} is currently locked by Word. Saved to {tables_docx_scratch}.")

# B. Main Word Report
personnel_block = (
    "Prepper: \nAndrew Carrillo (AC)\n\n"
    "Processor:\nGabrielle Surber (GS)\n\n"
    "Aliquoting Analyst:\nAmerica Alanis (ALA)\n\n"
    "Reading Analyst:\nCuong Du (CCD)"
)

word_context = {
    "oos_id": "262080",
    "client_name": "Optimal Balance Pharmacy (E19193)",
    "sample_id": "ETX-260828-0527",
    "sample_name": "MOTs-C 10 MG/ML (5 ML) Injection",
    "lot_number": "LG342010349",
    "dosage_form": "Injection",
    "test_date": "08Sep26",
    "process_date": "01Sep26",
    "received_data": "28Aug26",
    "prepper_name": "Andrew Carrillo",
    "prepper_initial": "AC",
    "analyst_name": "Gabrielle Surber",
    "analyst_initial": "GS",
    "aliquoting_name": "America Alanis",
    "aliquoting_initial": "ALA",
    "reading_name": "Cuong Du",
    "reading_initial": "CCD",
    "reader_name": "Cuong Du",
    "bsc_id": "1316",
    "cr_suit": "114",
    "smart_cr_id": "E001736 (114)",
    "smart_scan_id": "E002222",
    "control_positive": "Celsis ATP Positive Control",
    "control_lot": "022601-1483",
    "control_data": "31 Jan 2027",
    "monthly_cleaning_date": "30 Aug 2026",
    "smart_personnel_block": personnel_block,
    "smart_incident_opening": "On 08Sep26, sample ETX-260828-0527 was found positive for viable microorganisms after Celsis sterility testing.",
    "smart_comment_interview": "Yes, Andrew Carrillo (AC), Gabrielle Surber (GS), America Alanis (ALA), and Cuong Du (CCD) were interviewed comprehensively.",
    "smart_comment_samples": "Yes, Sample ID: ETX-260828-0527",
    "smart_comment_records": "N/A",
    "smart_comment_storage": "Yes, the sample was stored as per client's instructions. Information is available in EagleTrax Sample Location History under ETX-260828-0527",
    "report_header": "ETX-260828-0527\n\nOptimal Balance Pharmacy (E19193)",
    "analyst_signature": "Gabrielle Surber (Written by: Qiyue Chen)",
    "smart_phase1_summary": smart_phase1_full,
    "smart_phase1_continued": "",
    "event_number": "",
    "confirm_number": "",
    "organism_morphology": "No growth was obtained",
    "oos1_analyst_name": "N/A",
    "oos1_sample_id": "N/A",
    "oos1_sample_name": "N/A",
    "oos1_organism_morphology": "N/A",
}

main_docx_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.docx")
main_docx_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.docx")
tpl_main = DocxTemplate(os.path.join(ROOT_DIR, "Celsis OOS P1 template.docx"))
tpl_main.render(word_context)
tpl_main.save(main_docx_path)
tpl_main.save(main_docx_scratch)
print(f"Generated Main DOCX: {main_docx_path}")

# ==========================================
# 3. FILL FILLABLE PDF FORM
# ==========================================
print("\n--- [2/4] Filling AcroForm PDF Form ---")

pdf_template_path = os.path.join(ROOT_DIR, "Celsis OOS P1 template.pdf")
doc_pdf = fitz.open(pdf_template_path)

# Fill Page 1
page1 = doc_pdf[0]
for w in page1.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field0': w.field_value = 'Cuong Du (Written by Qiyue Chen)'
    elif fn == 'Date Field0': w.field_value = '01-Sep-2026'
    elif fn == 'Date Field1': w.field_value = '08-Sep-2026'
    elif fn == 'Date Field2': w.field_value = '08-Sep-2026'
    elif fn == 'Text Field1': w.field_value = 'Celsis Sterility Test'
    elif fn == 'Text Field2': w.field_value = 'ETX-260828-0527'
    elif fn == 'Text Field3':
        w.text_fontsize = 7.0
        w.field_value = (
            "Andrew Carrillo (AC)\r(Celsis Sterility Prepper)\r \r"
            "Gabrielle Surber (GS)\r(Celsis Sterility Processor)\r \r"
            "America Alanis (ALA)\r(Celsis Sterility Aliquoting Analyst)\r \r"
            "Cuong Du (CCD)\r(Celsis Sterility Reading Analyst)"
        )
    elif fn == 'Text Field4': w.field_value = 'MOTs-C 10 MG/ML (5 ML) Injection\r \r \r \r'
    elif fn == 'Text Field5': w.field_value = 'Injection'
    elif fn == 'Text Field6': w.field_value = 'LG342010349'
    elif fn == 'Text Field7':
        w.text_fontsize = 7.5
        w.field_value = 'On 08 Sep 2026, sample ETX-260828-0527 was found to be positive for growth after Celsis Sterility Testing\r \r'
    elif fn in ['Check Box0', 'Check Box1', 'Check Box2']: w.field_value = 'Yes'
    elif fn == 'Text Field8': w.field_value = 'MICRO-SOP-44'
    elif fn == 'Text Field9': w.field_value = '03-Jan-2025'
    elif fn == 'Text Field10': w.field_value = '01'
    elif fn == 'Text Field11': w.field_value = 'Pass/Fail'
    elif fn == 'Text Field12': w.field_value = 'Kathan Parikh'
    elif fn == 'Date Field3': w.field_value = '08-Sep-2026'
    elif fn == 'Text Field13':
        w.text_fontsize = 6.8
        w.field_value = 'Yes, analysts Andrew Carrillo, Gabrielle Surber, America Alanis & Cuong Du were comprehensively interviewed.'
    elif fn == 'Text Field14': w.field_value = 'Yes, Sample ID: ETX-260828-0527'
    elif fn in ['Text Field15', 'Text Field16']: w.field_value = 'Yes, as per MICRO-SOP-44'
    elif fn == 'Text Field17': w.field_value = 'Yes, Information is available in Eagle Trax under ETX-260828-0527'
    elif fn == 'Text Field18': w.field_value = 'Yes, all analysts are trained and qualified by the quality department to perform the test'
    elif fn in ['Text Field19', 'Text Field20']: w.field_value = 'Not Applicable'
    elif fn == 'Text Field21': w.field_value = "Yes, the samples were stored refrigerated as per client's instructions"
    elif fn in ['Check Box4', 'Check Box7', 'Check Box10', 'Check Box13', 'Check Box16', 'Check Box19',
                'Check Box24', 'Check Box27', 'Check Box28', 'Check Box32', 'Check Box36', 'Check Box38']:
        w.field_value = 'Yes'
    w.update()

# Fill Page 2
page2 = doc_pdf[1]
reagents_lots = (
    "Materials and Reagents\r"
    "TSB: 06242026-1\r"
    "FTM: 06162026-2\r"
    "PBS (Phosphate Buffered Saline): 35725002\r"
    "Bovine Serum Albumin (BSA): 245862\r \r"
    "Celsis AmpiScreen Reagents:\r"
    "Celsis Daily Wash & Rinse Kit:\r"
    "Celsis ATP Positive Control:\r"
    "Please refer to the data packet attached.\r \r \r"
    "TSA and Surface Plates: Please refer to the Environmental Logs uploaded under the submission on EagleTrax\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: 250409\r"
    "IPA: 01600581"
)

reagents_exp = (
    "Materials and Reagents\r"
    "TSB: 22 Sep 2026\r"
    "FTM: 14 Sep 2026\r"
    "PBS: 31 Dec 2027\r"
    "Bovine Serum Albumin (BSA): 23 Jan 2028\r \r"
    "Celsis AmpiScreen Reagents:\r"
    "Celsis Daily Wash & Rinse Kit:\r"
    "Celsis ATP Positive Control:\r"
    "Please refer to the data packet attached.\r \r"
    "TSA and Surface Plates: Please refer to the Environmental Logs uploaded under the submission on EagleTrax\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: Apr 2027\r"
    "IPA: Sep 2027"
)

incubator_list = (
    "Incubator E001356\r"
    "(Monitored by\r"
    "Sensor E001450)\r \r"
    "Incubator E001357\r"
    "(Monitored by\r"
    "Sensor E001449)\r \r"
    "Incubator E001034\r"
    "(Monitored by\r"
    "Sensor E001501)\r \r \r"
    "Incubator E001031\r"
    "(Monitored by\r"
    "Sensor E001505)"
)

incubator_cal = (
    "Jan 2027\r"
    "Feb 2027\r \r"
    "Jan 2027\r"
    "Feb 2027\r \r"
    "Aug 2027\r"
    "Feb 2027\r \r \r"
    "Aug 2027\r"
    "Feb 2027"
)

for w in page2.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn in ['Check Box42', 'Check Box43']: w.field_value = 'Yes'
    elif fn == 'Text Field22': w.field_value = reagents_lots
    elif fn == 'Text Field23': w.field_value = reagents_exp
    elif fn == 'Text Field24': w.field_value = 'Celsis ATP Positive Control\r \r'
    elif fn == 'Text Field25': w.field_value = '022601-1483'
    elif fn == 'Text Field26': w.field_value = '31 Jan 2027'
    elif fn in ['Text Field27', 'Text Field28', 'Text Field29']: w.field_value = 'Not Applicable '
    elif fn == 'Text Field30': w.field_value = 'E002222'
    elif fn == 'Text Field31': w.field_value = 'Sep 2026'
    elif fn == 'Text Field32': w.field_value = 'E001736 (114), BSC E001316 \rE001736 (114), BSC E001798'
    elif fn == 'Text Field33': w.field_value = 'Dec 2026, Jun 2027\rDec 2026, Jun 2027'
    elif fn == 'Text Field34': w.field_value = 'E002222'
    elif fn == 'Text Field35': w.field_value = 'Sep 2026'
    elif fn in ['Text Field36', 'Text Field37', 'Text Field38', 'Text Field39']: w.field_value = 'Not Applicable'
    elif fn in ['Text Field40', 'Text Field41', 'Text Field42', 'Text Field45']: w.field_value = 'See Phase I Summary'
    elif fn == 'Text Field43': w.field_value = incubator_list
    elif fn == 'Text Field44': w.field_value = incubator_cal
    elif fn in ['Check Box48', 'Check Box51', 'Check Box52', 'Check Box55', 'Check Box58',
                'Check Box63', 'Check Box66', 'Check Box67', 'Check Box70', 'Check Box73']:
        w.field_value = 'Yes'
    w.update()

# Fill Page 3
page3 = doc_pdf[2]
for w in page3.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn in ['Check Box78', 'Check Box79']: w.field_value = 'Yes'
    elif fn in ['Text Field46', 'Text Field47']: w.field_value = 'Not Applicable '
    elif fn == 'Text Field48': w.field_value = 'N/A QYC 08Sep2026'
    elif fn == 'Text Field49':
        w.field_value = text_field_49.replace('\n', '\r')
    w.update()

# Fill Page 4
page4 = doc_pdf[3]
for w in page4.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field50':
        w.text_fontsize = 7.5
        w.field_value = text_field_50.replace('\n', '\r').replace('₂', '2')
    w.update()

# Fill Page 5
page5 = doc_pdf[4]
for w in page5.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Text Field51':
        w.text_fontsize = 7.0
        w.field_value = text_field_51.replace('\n', '\r')
    w.update()

# Fill Page 6
page6 = doc_pdf[5]
for w in page6.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262080'
    elif fn == 'Check Box88': w.field_value = 'Yes'
    elif fn == 'Text Field53': w.field_value = 'Qiyue Chen'
    elif fn == 'Text Field54': w.field_value = 'Robin Seymour'
    w.update()

main_pdf_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.pdf")
main_pdf_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis.pdf")
doc_pdf.save(main_pdf_path)
doc_pdf.save(main_pdf_scratch)
doc_pdf.close()
print(f"Generated Main PDF: {main_pdf_path}")

# ==========================================
# 4. EXPORT TABLES DOCX TO PDF VIA WORD COM
# ==========================================
print("\n--- [3/4] Exporting Tables DOCX to PDF ---")
tables_pdf_path = os.path.join(DESKTOP_DIR, "Celsis table OOS-262080.pdf")
tables_pdf_scratch = os.path.join(SCRIPT_DIR, "Celsis table OOS-262080.pdf")

word = None
try:
    word = win32com.client.Dispatch("Word.Application")
    word.Visible = False
    source_docx = tables_docx_scratch if os.path.exists(tables_docx_scratch) else tables_docx_path
    doc_word = word.Documents.Open(source_docx)
    # wdExportFormatPDF = 17
    doc_word.ExportAsFixedFormat(tables_pdf_scratch, 17)
    doc_word.Close(False)
    try:
        shutil.copy2(tables_pdf_scratch, tables_pdf_path)
        print(f"Exported Tables PDF: {tables_pdf_path}")
    except PermissionError:
        print(f"Warning: {tables_pdf_path} is locked. PDF saved to {tables_pdf_scratch}")
except Exception as e:
    print(f"Word COM Export error: {e}")
finally:
    if word:
        try:
            word.Quit()
        except:
            pass
        del word
        gc.collect()

# ==========================================
# 5. ASSEMBLE COMBINED PACKAGE PDF
# ==========================================
print("\n--- [4/4] Creating Complete Combined PDF ---")
combined_pdf_path = os.path.join(DESKTOP_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis (Complete).pdf")
combined_pdf_scratch = os.path.join(SCRIPT_DIR, "OOS-262080 Optimal Balance Pharmacy (E19193) - Celsis (Complete).pdf")

doc_main = fitz.open(main_pdf_path)
source_tables_pdf = tables_pdf_scratch if os.path.exists(tables_pdf_scratch) else tables_pdf_path
if os.path.exists(source_tables_pdf):
    doc_tables = fitz.open(source_tables_pdf)
    doc_main.insert_pdf(doc_tables)
    doc_tables.close()

doc_main.save(combined_pdf_scratch)
try:
    doc_main.save(combined_pdf_path)
    print(f"Generated Combined Complete PDF: {combined_pdf_path}")
except PermissionError:
    print(f"Warning: {combined_pdf_path} is locked. Saved to {combined_pdf_scratch}")
doc_main.close()

print("SUCCESS: All 5 deliverables generated successfully!")
