import os, sys, shutil, datetime
from pypdf import PdfWriter, PdfReader
import fitz

OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"
DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"

base_pdf = os.path.join(OOS_ROOT, "ScanRDI OOS P2 template.pdf")

# Narratives
p22 = (
    "All the analysts involved in the testing - the initial processing analyst (Alex Saravia), the processing analyst who "
    "performed the retest (Abayomi Odugbesi), the reading analyst who confirmed the initial positive result (Elysse Nioupin), "
    "and the analyst who prepped and read the retest (Andrew Carrillo) - were interviewed comprehensively. Their answers are "
    "recorded throughout this document.\r \r"
    "INITIAL TEST UNDER SUBMISSION ETX-260902-0505:\r"
    "All analysts involved in the prepping, processing, and reading of the initial sample – Alex Saravia and Elysse Nioupin – "
    "were interviewed comprehensively. Upon arrival, the sample was stored in accordance with the Client’s instructions. "
    "Analysts verified the integrity of the sample throughout both preparation and processing stages. No leaks or turbidity were "
    "observed at any point, verifying sample integrity. All reagents and supplies mentioned in the material section above were "
    "stored according to the suppliers’ recommendations, and their integrity was visually verified before utilization. Moreover, "
    "all reagents and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing data "
    "generated by our comprehensive in-house continuous monitoring system. The cleanroom suite (CR 114) used for processing "
    "procedures comprises three interconnected sections: the innermost ISO 7 cleanroom (114B), which connects to the middle ISO 7 "
    "buffer room (114A), and then to the outermost ISO 8 anteroom (114). A positive air pressure system is maintained throughout "
    "the suite to ensure controlled, unidirectional airflow from 114B through 114A and into 114. The ISO 5 Biological Safety "
    "Cabinet (BSC) E001316, located in the innermost ISO 7 room, (114B), was used for initial sample processing steps. It was "
    "thoroughly cleaned and disinfected prior to each procedure in accordance with MICRO SOP-9 (Cleaning and Disinfecting Procedure "
    "for Microbiology). Additionally, BSC E001316 was certified and approved by both the Engineering and Quality Assurance teams. "
    "Initial sample processing was conducted in the ISO 5 BSC E001316 in the innermost ISO 7 room, (114B) by Alex Saravia on "
    "04 Sep 2026 as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p23 = (
    "On 04 Sep 2026, the sample vials for ETX-260902-0505 were received from Sample Submissions and brought into the Sterile "
    "Microbiology lab following multi-stage disinfection with acidified bleach (minimum 10-minute contact time at each transfer "
    "boundary). In ISO 5 BSC E001316, the containers were aseptically opened, and membrane filtration was performed (3 vials filtered) "
    "as per MICRO-SOP-5. Media bottles were transferred into designated incubators E001356 and E001357. On 10 Sep 2026 (Day 6 of incubation), "
    "microbial growth was observed in 1 x 100mL TSB media bottle by analyst Elysse Nioupin and confirmed by supervisor Robin Seymour. "
    "The positive TSB bottle was submitted for Differential Staining and Microbial Identification under ETX-260910-0290, which definitively "
    "identified the isolate as Microbacterium sp. PM5 (Gram-positive rods). All concurrent negative controls for the membrane filtration "
    "method remained sterile (no growth).\r \r"
    "Upon analyzing environmental monitoring results, no microbial growth was detected on operator personnel fingertip touch plates, "
    "settling plates, or ISO 5 BSC surface contact plates on the date of testing (04 Sep 2026), the date before (03 Sep 2026), or the "
    "subsequent testing date (08 Sep 2026). Weekly active air monitoring of ISO 8 Room 114 recovered 2 CFUs (ETX-260914-0487, identified as "
    "Corynebacterium ureicelerivorans and Mycobacterium grossiae), which differed in morphology and genus from the sample isolate and was "
    "physically isolated within the outermost ISO 8 anteroom. Monthly cleaning and disinfection of Suite CR114 was performed on 30 Aug 2026 "
    "per MICRO-SOP-9 with all H2O2 indicators passing. All other samples processed in the same testing session tested negative, ruling out "
    "cross-contamination.\r \r"
    "During preliminary interview, the processing analyst noted a potential handling discrepancy during the resuspension of the lyophilized "
    "vials. In addition, the same sample lot (2608-216) had previously been submitted and passed sterility testing via ScanRDI under ETX-260807-0602. "
    "Based on these initial findings and to investigate whether the positive recovery was attributable to an inadvertent analyst handling error "
    "during resuspension, a Phase II investigation was initiated, and additional sample vials from the same lot were requested from the client for retesting."
)

p24 = (
    "PHASE II RETEST UNDER SUBMISSION ETX-260914-0470:\r"
    "In accordance with Phase II investigation procedures under Form 3.100.019.F02, additional sample vials from lot 2608-216 were submitted "
    "for retesting under submission ETX-260914-0470.\r \r"
    "The retest sample was prepared by Andrew Carrillo on 14 Sep 2026 and processed by Abayomi Odugbesi on 15 Sep 2026 in accordance with "
    "MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test) via membrane filtration (60 gm filtered across 4 vials). The retest was conducted in certified "
    "ISO 5 BSC E001314 within cleanroom suite CR 114 following standard multi-barrier disinfection and strict aseptic technique. All culture media "
    "(FTM Lot 2567320, TSB Lot 2567280) and reagents (Fluid D Lot 687774, Bacteriostatic Water Lot NM7681) were within valid expiration dates. "
    "Media bottles were incubated in designated incubators E001356 and E001357. Negative controls were handled concurrently and remained sterile.\r \r"
    "On 21 Sep 2026 (Day 06 of incubation), microbial growth was observed in 1 x 100mL TSB media bottle by analyst Andrew Carrillo and confirmed "
    "by supervisor Robin Seymour. The positive bottle was submitted for Microbial Identification under ETX-260921-0498. Confirmatory identification "
    "identified the isolate as Microbacterium sp. (Gram-positive rods), matching the exact species, morphology, media selection (TSB), and incubation "
    "kinetics (Day 6) of the initial failure under ETX-260902-0505. All other samples processed in the batch on 15 Sep 2026 tested negative.\r \r"
    "EVALUATION OF RETEST FINDINGS:\r"
    "The successful replication of microbial recovery in the independent retest—conducted by a different processing analyst (Abayomi Odugbesi) "
    "and a different prepping/reading analyst (Andrew Carrillo)—conclusively refutes the preliminary hypothesis of analyst handling error during reconstitution. "
    "If the initial recovery had been an isolated artifact of analyst technique, the identical microorganism would not have been recovered on the identical "
    "incubation day in the retest.\r \r"
    "Furthermore, while the lot previously passed rapid ScanRDI testing under ETX-260807-0602, that test had no method suitability on file. "
    "In low-bioburden or slow-growing presentations, compendial membrane filtration enrichment provides superior sensitivity. "
    "Consequently, the retest confirms that the microbial recovery is inherent to product Lot 2608-216. The initial failing result for ETX-260902-0505 is "
    "confirmed as valid, the retest result for ETX-260914-0470 is confirmed as failing, and Lot 2608-216 fails USP <71> sterility testing."
)

p25 = (
    "The replication of microbial growth in the Phase II retest under ETX-260914-0470, with identical recovery kinetics (Day 6 in TSB) and confirmation "
    "of the identical organism (Microbacterium sp.), definitively disproves laboratory handling error and confirms inherent product contamination "
    "in Lot 2608-216. The original OOS result is confirmed valid, and the lot fails sterility requirements."
)

pdf_map = {
    # Page 1
    "Text Field0": "GLP3R/Cagrilinitide",
    "Date Field0": "15-Sep-2026",
    "Text Field1": "Prepping Analyst:\rAndrew Carrillo (AC)\r \rProcessing Analyst:\rAbayomi Odugbesi (AO)\r \rReading Analyst:\rAndrew Carrillo (AC)",
    "Text Field2": "Original test:\rETX-260902-0505\r \rRetest:\rETX-260914-0470",
    "Text Field3": "Fail",
    "Text Field4": "Fail",
    "Text Field5": "MICRO-SOP-5",
    "Text Field6": "TSB: Please see Consumables section under the submission on EagleTrax\r \rFTM: Please see Consumables section under the submission on EagleTrax",
    "Text Field7": "TSB: Please see Consumables section under the submission on EagleTrax\r \rFTM: Please see Consumables section under the submission on EagleTrax",
    
    # Page 1 Checkboxes
    "Check Box0": "/Yes",
    "Check Box2": "/Yes",
    "Check Box4": "/Yes",
    "Check Box6": "/Yes",
    "Check Box8": "/Yes",
    "Check Box10": "/Yes",
    "Check Box12": "/Yes",
    
    # Page 1 Equipment
    "Text Field8": "ISO 5 BSC E001316, ISO 5 BSC E001314",
    "Text Field9": "CR E001736",
    "Text Field10": "Incubator E001356 (Sensor E001450)\rIncubator E001357 (Sensor E001449)",
    "Text Field11": "Incubator E001034 (Sensor E001501)",
    "Text Field12": "Incubator E001031 (Sensor E001505)",
    "Text Field13": "Dec 2026",
    "Text Field14": "Jun 2027, Jun 2027",
    "Text Field15": "Jan 2027, Feb 2027\rJan 2027, Feb 2027",
    "Text Field16": "Aug 2027, Feb 2027",
    "Text Field17": "Aug 2027, Feb 2027",
    "Text Field18": "Not Applicable",
    
    # Page 1 Cleanroom & Controls
    "Check Box14": "/Yes",
    "Date Field1": "31-Dec-2026",
    "Check Box17": "/Yes",
    "Text Field19": "See Phase II Summary",
    "Check Box20": "/Yes",
    "Text Field20": "See Phase II Summary",
    "Check Box25": "/Yes",
    "Check Box28": "/Yes",
    "Check Box31": "/Yes",
    "Text Field30": "262098",
    
    # Page 2
    "Check Box32": "/Yes",
    "Check Box35": "/Yes",
    "Check Box38": "/Yes",  # N/A for processing method set per Tahsin guidance
    "Check Box41": "/Yes",  # N/A for same vial
    "Check Box42": "/Yes",  # formula worksheet
    "Check Box50": "/Yes",  # Section C Other
    "Text Field21": "Retest of additional vials from same lot",
    "Text Field22": p22,
    
    # Page 3
    "Text Field23": p23,
    
    # Page 4
    "Text Field24": p24,
    
    # Page 5
    "Text Field25": p25,
    "Check Box51": "/Yes",  # Root cause identified
    "Check Box52": "/Off",
    "Check Box53": "/Yes",  # Client Care notified
    "Check Box61": "/Yes",  # External Phenomena
    "Text Field26": "Inherent Product Contamination (Lot 2608-216)",
    "Text Field27": "Client Care notified of confirmed OOS sterility failure. Lot 2608-216 rejected.",
    "Text Field28": "N/A - Failure is inherent to client product; all laboratory equipment, media, and aseptic controls conformed to approved procedures.",
    "Check Box63": "/Yes",  # CAPA required: No
    "Check Box65": "/Yes",  # Follow-up required: No
    "Date Field3": "08-Oct-2026",
    "Date Field4": "08-Oct-2026",
}

writer = PdfWriter(clone_from=base_pdf)
for p in writer.pages:
    writer.update_page_form_field_values(p, pdf_map)

# Append Phase II Table PDF as Page 6
table_pdf_path = os.path.join(OUTPUT_DIR, "Tables OOS-262098 Solyn LLC (E75000) - Phase II.pdf")
if os.path.exists(table_pdf_path):
    t_reader = PdfReader(table_pdf_path)
    for tp in t_reader.pages:
        writer.add_page(tp)
    print("Appended Table page. Total pages:", len(writer.pages))

out_p2_pdf = os.path.join(OUTPUT_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.pdf")
with open(out_p2_pdf, "wb") as f:
    writer.write(f)
print("Saved Phase II PDF:", out_p2_pdf)

# Calibrate font sizes with PyMuPDF
doc_fitz = fitz.open(out_p2_pdf)
font_sizes = {
    # Page 1
    "Text Field0": 8.5,
    "Date Field0": 8.5,
    "Text Field1": 6.225,
    "Text Field2": 7.5,
    "Text Field3": 8.5,
    "Text Field4": 8.5,
    "Text Field5": 8.5,
    "Text Field6": 5.0,
    "Text Field7": 5.0,
    "Text Field8": 7.05,
    "Text Field9": 8.5,
    "Text Field10": 7.05,
    "Text Field11": 7.05,
    "Text Field12": 7.05,
    "Text Field13": 8.5,
    "Text Field14": 8.5,
    "Text Field15": 7.05,
    "Text Field16": 7.05,
    "Text Field17": 7.05,
    "Text Field18": 8.5,
    "Date Field1": 8.5,
    "Text Field19": 8.5,
    "Text Field20": 8.5,
    
    # Page 2
    "Text Field21": 8.5,
    "Text Field22": 9.2,
    
    # Page 3
    "Text Field23": 9.2,
    
    # Page 4
    "Text Field24": 9.2,
    
    # Page 5
    "Text Field25": 8.5,
    "Text Field26": 8.5,
    "Text Field27": 7.5,
    "Text Field28": 7.0,
    "Date Field3": 8.5,
    "Date Field4": 8.5,
}

for page in doc_fitz:
    for w in page.widgets():
        if w.field_name in font_sizes:
            w.text_fontsize = font_sizes[w.field_name]
            w.text_font = "Helv"
            w.update()

out_tuned = os.path.join(OUTPUT_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II_tuned.pdf")
doc_fitz.save(out_tuned)
doc_fitz.close()
shutil.copy2(out_tuned, out_p2_pdf)
print("Calibrated font sizes and finalized Phase II PDF!")

# Sync to Desktop and Documents
desktop_pdf = os.path.join(DESKTOP_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.pdf")
doc_pdf = os.path.join(DOCUMENTS_DIR, "OOS-262098 Solyn LLC (E75000) - Phase II.pdf")
shutil.copy2(out_p2_pdf, desktop_pdf)
shutil.copy2(out_p2_pdf, doc_pdf)
print("Synced to Desktop and Documents:", desktop_pdf)
