import os, sys, json, re, io, copy, shutil
OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
sys.path.insert(0, OOS_ROOT)
os.chdir(OOS_ROOT)

import docx
from docx.shared import Pt, Inches, RGBColor
from docx.oxml import parse_xml
from docx.opc.constants import RELATIONSHIP_TYPE
from docxtpl import DocxTemplate
from pypdf import PdfWriter, PdfReader
from datetime import datetime
import win32com.client
from utils import get_room_logic, get_cleanroom_narrative, ordinal, num_to_words, get_full_name

DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")
TABLE_INPUT_DOCX = r"C:\Users\qchen\Downloads\71 table.docx"

print("--- STARTING USP <71> OOS-262074 PROCESSING ---")

# 1. Investigation Master Dataset
data = {
    "oos_id": "262074",
    "client_name": "Hillstone Pharmacy (E17047)",
    "sample_id": "ETX-260806-0702 (BUD-T30)",
    "sample_id_pure": "ETX-260806-0702",
    "sample_url": "https://etrax.eagleanalytical.com/Submission/Details/l-JhbNGUHLdQSKAIyoIIMg__",
    "sample_name": "TB-500 10mg/ml",
    "lot_number": "24JUL2026-059",
    "dosage_form": "Liquid",
    "test_name": "USP <71> / EP 2.6.1 Sterility Test",
    "test_method": "USP <71> / EP 2.6.1 Sterility Test",
    "method_suitability": "ETX-260623-0160",
    "method_performed": "Membrane Filtration",
    "amount_filtered": "20 ml per media (10 vials)",
    "process_date": "31Aug26",
    "before_test": "28Aug26",
    "after_test": "01Sep26",
    "test_date": "07Sep26",
    "received_data": "28Aug26",
    "incubation_time": "14",
    "positive_media": "1 x 100 mL TSB",
    "positive_id": "ETX-260907-0017",
    "positive_id_url": "https://etrax.eagleanalytical.com/Submission/Details/e33ICd2xlQzZ9QFbX10xKA__",
    "positive_org": "Paenibacillus lautus Gram (+) rods",
    "prepper_initial": "AC",
    "prepper_name": "Andrew Carrillo",
    "analyst_initial": "ES",
    "analyst_name": "Alex Saravia",
    "reading_initial": "AC",
    "reading_name": "Andrew Carrillo",
    "writer_name": "Qiyue Chen",
    "qa_manager": "Robin Seymour",
    "qa_notified": "Kathan Parikh",
    "bsc_id": "1314",
    "chgbsc_id": "1314",
    "cr_suit": "115",
    "cr_id": "1737",
    "suit": "B",
    "bsc_location": "innermost ISO 7 room",
    "monthly_cleaning_date": "30Aug26",
    "ftm_lot": "2567320",
    "ftm_exp": "12/16/2026",
    "tsb_lot": "2548010",
    "tsb_exp": "04/19/2027",
    "fluid_d_lot": "685561",
    "fluid_d_exp": "10/31/2026",
    "incubator_tsb": "E001356 (Monitored by Sensor E001450)",
    "incubator_ftm": "E001357 (Monitored by Sensor E001449)",
}

# 2. Build Narrative Paragraphs
t_room, t_suite, t_suffix, t_loc = get_room_logic(data["bsc_id"])
cleanroom_narrative = get_cleanroom_narrative(t_suite, t_room=None, action_text="processing procedures", verb="comprises")

p1 = "All analysts involved in the prepping, processing, and reading of the sample – Andrew Carrillo (AC) and Alex Saravia (ES) were interviewed comprehensively. Their answers are recorded throughout this document."

p2 = "Upon arrival, the sample was stored in accordance with the Client’s instructions under refrigeration. Analyst Alex Saravia verified the integrity of the sample throughout both the preparation and processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the sample."

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to the suppliers’ recommendations, "
    "and their integrity was visually verified before utilization. Fluid Thioglycollate Medium (FTM 100ML, Lot: 2567320, Exp: 12/16/2026), "
    "Trypticase Soy Broth (TSB 100mL, Lot: 2548010, Exp: 04/19/2027), and Fluid D (Lot: 685561, Exp: 10/31/2026) had valid expiration dates. "
    "The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    f"{cleanroom_narrative}\n\n"
    f"The ISO 5 BSC E00{data['bsc_id']}, located in the {t_loc} (115B), was used for sample processing steps. It was thoroughly "
    "cleaned and disinfected prior to each procedure in accordance with SOP 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology). "
    f"Additionally, BSC E00{data['bsc_id']} was certified and approved by both the Engineering and Quality Assurance teams. Sample processing was "
    f"conducted in the ISO 5 BSC E00{data['bsc_id']} in 115B by Alex Saravia on 31Aug26 as per SOP 2.600.008 (USP <71> / EP 2.6.1 Sterility Test)."
)

p5 = (
    f"On 28Aug26, the sample containers for {data['sample_id_pure']} were received from the Sample Submissions team and brought into "
    "the Sterile Microbiology lab. Upon receipt, each sample container was sprayed with an acidified bleach disinfectant, placed into "
    "pre-disinfected bins, and allowed a 10-minute contact time. Following initial disinfection, the bins were transferred to the ISO 8 anteroom "
    "(115), where the containers underwent a second disinfection using acidified bleach, again with a 10-minute contact time. Subsequently, "
    f"the containers were moved into the ISO 7 cleanroom 115B. Inside this cleanroom, the processing analyst, Alex Saravia, performed a final "
    f"disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, the containers were transferred into the ISO 5 BSC E00{data['bsc_id']}."
)

p6 = (
    f"Once transferred into the ISO 5 BSC, the containers were placed on the disinfected working surface of BSC E00{data['bsc_id']} and "
    "aseptically processed in accordance with SOP 2.600.008 (USP <71> / EP 2.6.1 Sterility Test) utilizing membrane filtration under method "
    f"suitability {data['method_suitability']}. Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. "
    "The contents of 10 vials (20 mL per media) were filtered directly through sterile canisters on a vacuum manifold. Following filtration, canisters "
    "were rinsed with sterile Fluid D and filled with TSB and FTM media. Media bottles were transferred into incubators E001356 (monitored by sensor "
    "E001450) and E001357 (monitored by sensor E001449) to begin incubation. Visual inspections were performed periodically by the analyst over the "
    "14-day incubation period to detect any macroscopic evidence of microbial growth."
)

p7 = (
    f"During periodic visual inspections on 07Sep26 (Day 7 of incubation), macroscopic evidence of microbial growth was observed by reading analyst "
    f"Andrew Carrillo in 1 x 100 mL TSB media bottle, while FTM media bottles showed no microbial growth. The positive TSB bottle for {data['sample_id_pure']} "
    f"was submitted for Differential Staining and Microbial Identification under {data['positive_id']}, where the organism was definitively identified as "
    f"{data['positive_org']}."
)

p8 = (
    "The culture media utilized were within their expiry period. The negative control canisters for the membrane filtration method were handled, "
    "processed, and incubated in a manner identical to that of actual samples. No microbial growth was observed in the corresponding negative controls."
)

p9 = (
    "A review of the Environmental Monitoring (EM) results for the relevant testing period showed no microbial growth on daily personnel monitoring "
    f"plates (left and right glove touches), daily settling plates, or ISO 5 BSC E00{data['bsc_id']} surface sampling plates across all bracketing dates "
    f"(28Aug26, 31Aug26, and 01Sep26). Weekly cleanroom surface sampling for Cleanroom 115 (E001737), performed on 04Sep26, likewise demonstrated "
    "no microbial growth. Weekly active air sampling on 04Sep26 showed 1 CFU (ETX-260914-0487, pending identification) in the ISO 8 anteroom (114). "
    f"However, all sample processing activities were performed within the validated ISO 5 BSC E00{data['bsc_id']} located in innermost ISO 7 cleanroom 115B. "
    "The sample containers were transferred inside closed, disinfected bins, and did not come into contact with ambient ISO 8 air. Furthermore, the complete "
    "absence of microbial recovery across all daily analyst glove touch plates, critical ISO 5 BSC work surfaces, and settling plates confirms that no "
    "contamination transfer pathway existed between the lower-classified anteroom environment and the ISO 5 processing zone."
)

p10 = (
    "The analysts confirmed full compliance with cleaning procedures as outlined in SOPs 2.600.018 (Cleaning and Disinfecting Procedure for Microbiology) "
    f"and 2.600.008 (USP <71> / EP 2.6.1 Sterility Test). Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, "
    f"the innermost ISO 7 cleanroom, and its containing ISO 5 Biosafety Cabinets for 115 was performed on {data['monthly_cleaning_date']}, as per SOP 2.600.018. "
    "During both cleaning cycles, all H2O2 indicators passed, confirming efficient monthly decontamination."
)

p11 = (
    f"Analyzing a 6-month sample history for {data['client_name']}, this specific analyte \"{data['sample_name']}\" has had no prior failures using "
    f"USP <71> / EP 2.6.1 Sterility Test during this period. Furthermore, the previous T0 time point for this stability lot ({data['lot_number']}) "
    "yielded valid passing sterility results."
)

p12 = (
    "To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review was conducted of all samples "
    f"processed on the same day (31Aug26). Sample {data['sample_id_pure']} was the 4th sample processed in the batch. All other samples processed by "
    "the analyst in the batch on that day tested negative. These findings confirm that cross-contamination between samples is highly unlikely."
)

p13 = (
    "Based on the observations outlined above, it is unlikely that the failing results were due to reagents, supplies, the cleanroom environment, "
    "the process, or analyst involvement. Consequently, the possibility of laboratory error contributing to this failure is minimal and the original "
    "result is deemed to be valid."
)

smart_phase1_full = "\n\n".join([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13])
smart_phase1_part1 = "\n\n".join([p1, p2, p3, p4, p5, p6])
smart_phase1_part2 = "\n\n".join([p7, p8, p9, p10, p11, p12, p13])

data["smart_phase1_summary"] = smart_phase1_full
data["equipment_summary"] = p4
data["narrative_summary"] = p9
data["sample_history_paragraph"] = p11
data["cross_contamination_summary"] = p12
data["smart_comment_interview"] = "Yes, analysts Andrew Carrillo and Alex Saravia were interviewed comprehensively."
data["smart_comment_samples"] = f"Yes, sample ID: {data['sample_id_pure']}"
data["smart_comment_records"] = f"Yes, Information is available in EagleTrax under {data['sample_id_pure']}"
data["smart_comment_storage"] = f"Yes, the sample was stored refrigerated as per client's instructions. Information is available in EagleTrax Sample Location History under {data['sample_id_pure']}"
data["smart_personnel_block"] = f"Prepper: \n{data['prepper_name']} ({data['prepper_initial']})\n\nProcessor:\n{data['analyst_name']} ({data['analyst_initial']})\n\nReading Analyst:\n{data['reading_name']} ({data['reading_initial']})"
data["analyst_signature"] = f"{data['analyst_name']} (Written by: {data['writer_name']})"
data["smart_incident_opening"] = f"On {data['test_date']}, sample {data['sample_id']} was found positive for viable microorganisms after USP <71> / EP 2.6.1 sterility testing."
data["smart_cr_id"] = "CR115 (E001737)"
data["usp71_id"] = f"E00{data['bsc_id']}"
data["reader_name"] = data["reading_name"]

# 3. Helper functions for table formatting
def set_cell_hyperlink(cell, url, text):
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    part = p.part
    r_id = part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink_xml = (
        f'<w:hyperlink xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        f'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
        f'r:id="{r_id}" w:history="1">'
        f'<w:r>'
        f'<w:rPr>'
        f'<w:rStyle w:val="Hyperlink"/>'
        f'<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        f'<w:color w:val="467886"/>'
        f'<w:sz w:val="15"/>'
        f'<w:szCs w:val="15"/>'
        f'<w:u w:val="single"/>'
        f'</w:rPr>'
        f'<w:t>{text}</w:t>'
        f'</w:r>'
        f'</w:hyperlink>'
    )
    p._p.append(parse_xml(hyperlink_xml))
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

def update_cell_text(cell, text, bold=False, italic=False, font_size=Pt(7.0), align=docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER):
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = align
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.name = "Times New Roman"
    run.font.size = font_size
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

# 4. Generate Standalone Tables Document with Strict 1-Page Constraint
out_doc_tables = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
doc_orig = docx.Document(TABLE_INPUT_DOCX)

# Create a clean fresh doc with 0.4 inch margins
doc_clean = docx.Document()
sec = doc_clean.sections[0]
sec.top_margin = Inches(0.4)
sec.bottom_margin = Inches(0.4)
sec.left_margin = Inches(0.45)
sec.right_margin = Inches(0.45)

# Add Table 1 Header
p_t1 = doc_clean.add_paragraph()
p_t1.paragraph_format.space_before = Pt(0)
p_t1.paragraph_format.space_after = Pt(3)
r_t1 = p_t1.add_run(f"Table 1: Information for {data['sample_id']} under investigation")
r_t1.bold = True
r_t1.font.name = "Times New Roman"
r_t1.font.size = Pt(9.5)

# Copy Table 1
t1_clean = doc_clean.add_table(rows=2, cols=6)
t1_clean.style = 'Table Grid'
t1_clean.autofit = False

# Copy headers from original Table 1
t1_orig = doc_orig.tables[0]
for c_idx, cell in enumerate(t1_orig.rows[0].cells):
    update_cell_text(t1_clean.rows[0].cells[c_idx], cell.text.strip(), bold=True, font_size=Pt(7.5))

# Populate Table 1 row 1
r1_clean = t1_clean.rows[1]
update_cell_text(r1_clean.cells[0], "Andrew Carrillo", font_size=Pt(7.5))
update_cell_text(r1_clean.cells[1], "7", font_size=Pt(7.5))
set_cell_hyperlink(r1_clean.cells[2], data["sample_url"], data["sample_id"])
set_cell_hyperlink(r1_clean.cells[3], data["positive_id_url"], data["positive_id"])
update_cell_text(r1_clean.cells[4], data["positive_media"], font_size=Pt(7.5))
update_cell_text(r1_clean.cells[5], "Paenibacillus lautus\nGram (+) rods", font_size=Pt(7.5))

# Add brief spacing and Table 2 Header
p_t2 = doc_clean.add_paragraph()
p_t2.paragraph_format.space_before = Pt(8)
p_t2.paragraph_format.space_after = Pt(3)
r_t2 = p_t2.add_run("Table 2: Environmental Monitoring for Analyst & Cleanroom")
r_t2.bold = True
r_t2.font.name = "Times New Roman"
r_t2.font.size = Pt(9.5)

# Copy Table 2
t2_orig = doc_orig.tables[1]
t2_clean = doc_clean.add_table(rows=len(t2_orig.rows), cols=len(t2_orig.columns))
t2_clean.style = 'Table Grid'
t2_clean.autofit = False

# Populate Table 2 Header (Row 0)
for c_idx, cell in enumerate(t2_orig.rows[0].cells):
    update_cell_text(t2_clean.rows[0].cells[c_idx], cell.text.strip(), bold=True, font_size=Pt(7.0))

# Row 1: Merged header
t2_clean.rows[1].cells[0].merge(t2_clean.rows[1].cells[-1])
update_cell_text(t2_clean.rows[1].cells[0], "Personnel EM Bracketing 31Aug2026", bold=True, font_size=Pt(7.5))

# Personnel rows (2, 3, 4)
em_personnel_data = [
    ("Personal (Left Touch and Right Touch)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Personal (Left Touch and Right Touch)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Personal (Left Touch and Right Touch)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_personnel_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[2 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 5: Merged BSC header
t2_clean.rows[5].cells[0].merge(t2_clean.rows[5].cells[-1])
update_cell_text(t2_clean.rows[5].cells[0], "Biological Safety Cabinet EM Bracketing Biological Safety Cabinet (BSC) E001314", bold=True, font_size=Pt(7.5))

# Surface sampling (6, 7, 8)
em_surf_data = [
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_surf_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[6 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Settling sampling (9, 10, 11)
em_sett_data = [
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_sett_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[9 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 12: Weekly Active Air header
t2_clean.rows[12].cells[0].merge(t2_clean.rows[12].cells[-1])
update_cell_text(t2_clean.rows[12].cells[0], "Weekly Active Air Sampling for CR 114", bold=True, font_size=Pt(7.5))

# Row 13: Active Air data
air_vals = ("Active Air Sampling of Cleanrooms", "Weekly", "04 Sep 2026", "SMO", "Week of Testing", "1 CFU (ISO8)", "ETX-260914-0487", "Pending", "None")
for c_idx, val in enumerate(air_vals):
    align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    update_cell_text(t2_clean.rows[13].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 14: Surface Sampling Anteroom header
t2_clean.rows[14].cells[0].merge(t2_clean.rows[14].cells[-1])
update_cell_text(t2_clean.rows[14].cells[0], "Surface Sampling of Anteroom and Cleanroom for CR 115 (E001737)", bold=True, font_size=Pt(7.5))

# Row 15: Cleanroom surface data
clean_vals = ("Surface Sampling of Cleanrooms", "Weekly", "04 Sep 2026", "SMO", "Week of Testing", "No growth", "N/A", "N/A", "None")
for c_idx, val in enumerate(clean_vals):
    align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    update_cell_text(t2_clean.rows[15].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Set row heights and padding tight to ensure 1 page
for t in [t1_clean, t2_clean]:
    for row in t.rows:
        trPr = row._tr.get_or_add_trPr()
        trHeight = parse_xml(f'<w:trHeight xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:val="220" w:hRule="atLeast"/>')
        trPr.append(trHeight)

doc_clean.save(out_doc_tables)
print("Saved Standalone Tables Docx (clean 1-page design) to:", out_doc_tables)

# 5. Export Standalone Tables Docx to PDF via Word COM
out_pdf_tables = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
try:
    word = win32com.client.DispatchEx("Word.Application")
    word.Visible = False
    try:
        d = word.Documents.Open(os.path.abspath(out_doc_tables), ReadOnly=True)
        d.SaveAs(os.path.abspath(out_pdf_tables), FileFormat=17)
        d.Close(SaveChanges=False)
        print("Saved Standalone Tables PDF via Word to:", out_pdf_tables)
    finally:
        word.Quit()
except Exception as e:
    print(f"Word COM export notice: {e}")

# Verify Tables PDF Page Count
r_check = PdfReader(out_pdf_tables)
print(f"Verified Tables PDF Page Count: {len(r_check.pages)} (Must be 1)")

# 6. Render Master Word Report
out_doc_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
primary_tpl = "USP71 OOS P1 template.docx" if os.path.exists("USP71 OOS P1 template.docx") else "USP71 OOS P1 template 0.docx"
tpl_report = DocxTemplate(primary_tpl)
tpl_report.render(data)

# Replace Table 2 & Table 3 in Master Word Report with the updated clean Table 1 & Table 2
if len(tpl_report.docx.tables) >= 3:
    # Replace Table 2 (t1 in clean doc)
    t2_elem = tpl_report.docx.tables[1]._element
    p2_parent = t2_elem.getparent()
    idx2 = p2_parent.index(t2_elem)
    p2_parent.remove(t2_elem)
    new_t1_elem = copy.deepcopy(t1_clean._element)
    p2_parent.insert(idx2, new_t1_elem)

    # Replace Table 3 (t2 in clean doc)
    t3_elem = tpl_report.docx.tables[2]._element
    p3_parent = t3_elem.getparent()
    idx3 = p3_parent.index(t3_elem)
    p3_parent.remove(t3_elem)
    new_t2_elem = copy.deepcopy(t2_clean._element)
    p3_parent.insert(idx3, new_t2_elem)

# Clean up paragraph titles above tables in master report
for p in tpl_report.docx.paragraphs:
    if "Table 1:" in p.text:
        p.text = f"Table 1: Information for {data['sample_id']} under investigation"
        p.runs[0].bold = True
    elif "Table 2:" in p.text:
        p.text = "Table 2: Environmental Monitoring for Analyst & Cleanroom"
        p.runs[0].bold = True

tpl_report.save(out_doc_report)
print("Saved Master Word Report to:", out_doc_report)

# 7. Render Official PDF Form (using USP71 OOS P1 template.pdf as base)
base_pdf = "USP71 OOS P1 template.pdf"
pdf_map = {
    'Text Field57': data['oos_id'],
    'Date Field0': "31-Aug-2026",
    'Date Field1': "07-Sep-2026",
    'Date Field2': "07-Sep-2026",
    'Date Field3': "07-Sep-2026",
    'Text Field1': data['test_name'],
    'Text Field2': data['sample_id'],
    'Text Field3': data['smart_personnel_block'],
    'Text Field4': data['sample_name'] + "\n\n\n\n",
    'Text Field5': data['dosage_form'],
    'Text Field6': data['lot_number'],
    'Text Field7': data['smart_incident_opening'] + "\n\n",
    'Text Field8': "2.600.008",
    'Text Field9': "26Aug25",
    'Text Field10': "18",
    'Text Field11': "Pass/Fail",
    'Text Field12': data['qa_notified'],
    'Text Field0': data['analyst_signature'],
    'Text Field13': data['smart_comment_interview'],
    'Text Field14': data['smart_comment_samples'],
    'Text Field15': "Yes, as per SOP 2.600.008",
    'Text Field16': "Yes, as per SOP 2.600.008",
    'Text Field17': data['smart_comment_records'],
    'Text Field18': "Yes, all analysts are trained and qualified by quality to perform the test.",
    'Text Field19': "Not Applicable",
    'Text Field20': "Not Applicable",
    'Text Field21': data['smart_comment_storage'],
    'Text Field22': "Process Consumables:\nFTM 100ML: 2567320\nTSB 100mL: 2548010\nFluid D: 685561",
    'Text Field23': "Process Consumables:\nFTM: 12/16/2026\nTSB: 04/19/2027\nFluid D: 10/31/2026",
    'Text Field24': "Not Applicable",
    'Text Field25': "Not Applicable",
    'Text Field26': "Not Applicable",
    'Text Field27': "Not Applicable",
    'Text Field28': "Not Applicable",
    'Text Field29': "Not Applicable",
    'Text Field30': f"ISO 5 BSC E00{data['bsc_id']}",
    'Text Field31': "Dec 2026",
    'Text Field32': data['smart_cr_id'],
    'Text Field33': "Jun 2026",
    'Text Field34': f"E00{data['bsc_id']}",
    'Text Field36': "Not Applicable",
    'Text Field37': "Not Applicable",
    'Text Field38': "Not Applicable",
    'Text Field39': "Not Applicable",
    'Text Field40': "See Phase I Summary",
    'Text Field41': "See Phase I Summary",
    'Text Field42': "See Phase I Summary",
    'Text Field43': f"{data['incubator_tsb']}\n{data['incubator_ftm']}",
    'Text Field44': "Jul 2026 / Feb 2027\nJul 2026 / Feb 2027",
    'Text Field45': "See Phase I Summary",
    'Text Field46': "Not Applicable",
    'Text Field47': "Not Applicable",
    'Text Field48': f"N/A QC {datetime.now().strftime('%d%b%y')}",
    'Text Field49': smart_phase1_part1,
    'Text Field50': smart_phase1_part2,
    'Text Field51': "Reviewer comment(s): Satisfactory investigation. The failure is valid and not attributable to laboratory error.",
    'Text Field53': f"{data['analyst_name']} (Written by: {data['writer_name']})",
    'Text Field54': data['qa_manager']
}

# Add standard compliance checkboxes
checkbox_fields = {
    'Check Box1': '/Yes',   # QA Dept notified Yes
    'Check Box2': '/Yes',   # Analyst interviewed Yes
    'Check Box5': '/Yes',   # Correct samples analyzed Yes
    'Check Box8': '/Yes',   # Correct SOP used Yes
    'Check Box11': '/Yes',  # Correct sample collection Yes
    'Check Box14': '/Yes',  # Test result records attached Yes
    'Check Box17': '/Yes',  # Analyst qualified Yes
    'Check Box22': '/N/A',  # Formula worksheet N/A
    'Check Box25': '/Yes',  # Processing method conforms Yes
    'Check Box28': '/Yes',  # Sample stored appropriately Yes
    'Check Box32': '/No',   # Integrity questionable No
    'Check Box35': '/Yes',  # Sample transported appropriately Yes
    'Check Box39': '/No',   # Other test results under investigation No
    'Check Box42': '/N/A',  # Appropriate glassware N/A
    'Check Box43': '/Yes',  # Reagents stored properly Yes
    'Check Box48': '/N/A',  # Standard source of root cause N/A
    'Check Box51': '/N/A',  # Retest solution kept N/A
    'Check Box52': '/Yes',  # Instrument setup correctly Yes
    'Check Box55': '/Yes',  # Cleanroom facility certified Yes
    'Check Box60': '/N/A',  # System performance check N/A
    'Check Box63': '/N/A',  # System suitability RSD < 2% N/A
    'Check Box66': '/N/A',  # System suitability RSD < 10% N/A
    'Check Box69': '/Yes',  # EM conform to standards Yes (with just)
    'Check Box72': '/Yes',  # Controls conform Yes
    'Check Box75': '/Yes',  # Equipment functional Yes
    'Check Box78': '/N/A',  # Chromatogram/spectra N/A
    'Check Box80': '/1',    # Section C N/A
    'Check Box88': '/1',    # Root cause lab error: No, OOS is valid
}
pdf_map.update(checkbox_fields)

writer = PdfWriter(clone_from=base_pdf)
while len(writer.pages) > 6:
    del writer.pages[-1]

for p in writer.pages:
    writer.update_page_form_field_values(p, pdf_map)

# Append Tables PDF as Page 7 if available
if os.path.exists(out_pdf_tables):
    table_reader = PdfReader(out_pdf_tables)
    for table_page in table_reader.pages:
        writer.add_page(table_page)
    print(f"Appended Tables PDF to form. Total pages: {len(writer.pages)} (Expect 7)")

out_pdf_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
with open(out_pdf_report, "wb") as f:
    writer.write(f)
print("Saved complete PDF Report to:", out_pdf_report)

# Adjust font sizes in PDF narrative fields to ensure neat fit
try:
    import fitz
    doc_fitz = fitz.open(out_pdf_report)
    font_sizes = {
        'Text Field49': 8.5,
        'Text Field50': 8.5,
        'Text Field51': 9.0,
    }
    for page in doc_fitz:
        for w in page.widgets():
            if w.field_name in font_sizes:
                w.text_fontsize = font_sizes[w.field_name]
                w.update()
    temp_pdf_out = out_pdf_report + ".tmp.pdf"
    doc_fitz.save(temp_pdf_out)
    doc_fitz.close()
    shutil.move(temp_pdf_out, out_pdf_report)
    print("Successfully fine-tuned narrative font sizes with PyMuPDF.")
except Exception as e:
    print(f"PyMuPDF font tuning notice: {e}")

# 8. Save State Data (.txt / .json)
out_json_path = os.path.join(OUTPUT_DIR, f"SAVE_OOS-{data['oos_id']} {data['client_name']} - USP71.txt")
with open(out_json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
print("Saved session state JSON to:", out_json_path)

# 9. Sync all deliverables to Documents directory
files_to_sync = [
    out_doc_report,
    out_doc_tables,
    out_pdf_report,
    out_pdf_tables,
    out_json_path
]
for fpath in files_to_sync:
    if fpath and os.path.exists(fpath):
        dest = os.path.join(DOCUMENTS_DIR, os.path.basename(fpath))
        try:
            shutil.copy2(fpath, dest)
            print(f"Synced to Documents: {dest}")
        except PermissionError:
            print(f"Notice: {dest} is open in another app, skipped overwrite.")
        except Exception as e:
            print(f"Sync notice: {e}")

print("\n--- ALL GENERATION COMPLETED SUCCESSFULLY! ---")
