import os, sys, json, re, io, copy, shutil
OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
sys.path.insert(0, OOS_ROOT)
os.chdir(OOS_ROOT)

import docx
from docx.shared import Pt, Inches, RGBColor
from docx.oxml import parse_xml
from docx.opc.constants import RELATIONSHIP_TYPE
from docxtpl import DocxTemplate
from pypdf import PdfWriter, PdfReader
from datetime import datetime
import win32com.client
from utils import get_room_logic, get_cleanroom_narrative, ordinal, num_to_words, get_full_name

DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")
TABLE_INPUT_DOCX = r"C:\Users\qchen\Downloads\71 table.docx"

print("--- STARTING USP <71> OOS-262074 UPGRADE TO MATCH GOLD STANDARD OOS-261987 ---")

# 1. Investigation Master Dataset
data = {
    "oos_id": "262074",
    "client_name": "Hillstone Pharmacy (E17047)",
    "sample_id": "ETX-260806-0702 (BUD-T30)",
    "sample_id_pure": "ETX-260806-0702",
    "sample_url": "https://etrax.eagleanalytical.com/Submission/Details/l-JhbNGUHLdQSKAIyoIIMg__",
    "sample_name": "TB-500 10mg/ml",
    "lot_number": "24JUL2026-059",
    "dosage_form": "Liquid",
    "test_name": "USP <71> / EP 2.6.1 Sterility Test",
    "test_method": "MICRO-SOP-5",
    "sop_effective_date": "24Jul2026",
    "sop_rev": "19",
    "method_suitability": "ETX-260623-0160",
    "method_performed": "Membrane Filtration",
    "amount_filtered": "20 ml per media (10 vials)",
    "process_date": "31Aug26",
    "process_date_full": "31 Aug 2026",
    "before_test": "28Aug26",
    "after_test": "01Sep26",
    "test_date": "07Sep26",
    "test_date_full": "07 Sep 2026",
    "received_data": "28Aug26",
    "incubation_time": "14",
    "positive_media": "1 x 100 mL TSB",
    "positive_id": "ETX-260907-0017",
    "positive_id_url": "https://etrax.eagleanalytical.com/Submission/Details/e33ICd2xlQzZ9QFbX10xKA__",
    "positive_org": "Paenibacillus lautus Gram (+) rods",
    "prepper_initial": "AC",
    "prepper_name": "Andrew Carrillo",
    "analyst_initial": "ES",
    "analyst_name": "Alex Saravia",
    "reading_initial": "AC",
    "reading_name": "Andrew Carrillo",
    "writer_name": "Qiyue Chen",
    "qa_manager": "Robin Seymour",
    "qa_notified": "Kathan Parikh",
    "bsc_id": "1316",
    "chgbsc_id": "1316",
    "cr_suit": "114",
    "cr_id": "1736",
    "suit": "B",
    "bsc_location": "innermost ISO 7 room",
    "monthly_cleaning_date": "30Aug26",
    "monthly_cleaning_date_full": "30 Aug 2026",
    "ftm_lot": "2567320",
    "ftm_exp": "12/16/2026",
    "tsb_lot": "2548010",
    "tsb_exp": "04/19/2027",
    "fluid_d_lot": "685561",
    "fluid_d_exp": "10/31/2026",
}

# 2. Build Narrative Paragraphs Split Exactly across 3 Pages (Page 3, Page 4, Page 5)
# Following OOS-261987 Gold Standard structure

# --- PAGE 3 (Text Field 49) ---
p1 = "All analysts involved in the prepping, processing, and reading of the sample – Andrew Carrillo, Alex Saravia and Andrew Carrillo, were interviewed comprehensively. Their answers are recorded throughout this document."

p2 = "Upon arrival, the sample was stored in accordance with the Client’s instructions. Analysts - Andrew Carrillo and Alex Saravia - verified the integrity of the sample throughout both the preparation and processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the sample."

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to the suppliers’ recommendations, "
    "and their integrity was visually verified before utilization. Moreover, all reagents and supplies had valid expiration dates. "
    "The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The cleanroom suite (CR 114) used for processing procedures comprises three interconnected sections: the innermost ISO 7 cleanroom (114B), "
    "which connects to the middle ISO 7 buffer room (114A), and then to the outermost ISO 8 anteroom (114). A positive air pressure system "
    "is maintained throughout the suite to ensure controlled, unidirectional airflow from 114B through 114A and into 114."
)

p5 = (
    f"The ISO 5 BSC E00{data['bsc_id']}, located in the innermost ISO 7 room, (114B), was used for sample processing steps. It was thoroughly "
    "cleaned and disinfected prior to each procedure in accordance with MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    f"Additionally, BSC E00{data['bsc_id']} was certified and approved by both the Engineering and Quality Assurance teams. Sample processing was "
    f"conducted in the ISO 5 BSC E00{data['bsc_id']} in the innermost ISO 7 room, (114B) by Alex Saravia on {data['process_date_full']} as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p6 = (
    f"On 28 Aug 2026, the sample vials for {data['sample_id_pure']} were received from the Sample Submissions team and brought into "
    "the Sterile Microbiology lab. Upon arrival, each sample vial was sprayed with an acidified bleach disinfectant, placed into "
    "pre-disinfected bins, and allowed a 10-minute contact time."
)

p7 = (
    "The secondary disinfection happened in the ISO 8 anteroom (114), where the vials were again treated with acidified bleach and provided "
    "a 10-minute contact time before processing. Subsequently, the vials were moved into innermost ISO 7 cleanroom (114B). Inside this cleanroom, "
    "the processing analyst, Alex Saravia, performed a final disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, "
    f"the vials were transferred into the ISO 5 BSC E00{data['bsc_id']}."
)

p8 = (
    "Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. The contents of 10 vials (20 mL per media) "
    "were dispensed directly from the container into sterile canisters placed on a vacuum manifold for membrane filtration under method suitability "
    f"{data['method_suitability']}. The sample was processed and tested as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test). Media bottles were "
    "transferred into incubators E001356 and E001357 to begin incubation."
)

p9 = (
    f"On {data['test_date_full']} (Day 7 of incubation), microbial growth was observed in one TSB (Tryptic Soy Broth) media bottle by reading analyst, "
    f"Andrew Carrillo, and confirmed by Microbiology Lab Supervisor, Robin Seymour. The positive TSB bottle for {data['sample_id_pure']} was submitted "
    f"for Differential Staining and Microbial Identification under {data['positive_id']}.  Definitive identification identified the isolate as {data['positive_org']}."
)

p10 = (
    "The culture media utilized were within their expiry period. Negative control media bottles for the membrane filtration method were handled, "
    "processed, and incubated in the same manner as the test samples. No microbial growth was observed in the corresponding negative controls."
)

p11 = (
    "Upon analyzing the environmental monitoring results, no microbial growth was detected on personnel monitoring plates, settling plates, or "
    f"ISO 5 BSC surface sampling plates on the date of testing ({data['process_date_full']}), the preceding testing date (28 Aug 2026), or the subsequent "
    "testing date (01 Sep 2026). Additionally, no microbial growth was recovered from the weekly surface sampling plate collected on 04 Sep 2026 for Cleanroom 114 (E001736). "
    "However, weekly active air monitoring of ISO 8 Room 114 (CR 114) recovered 1 CFU (ETX-260914-0487, pending identification)."
)

text_field_49 = "\r \r".join([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11])

# --- PAGE 4 (Text Field 50) ---
p12 = (
    f"It is important to note that all sample processing activities were performed within the validated ISO 5 BSC E00{data['bsc_id']} located in the innermost "
    "ISO 7 cleanroom (Suite 114B). The test samples do not come into contact with ambient ISO 8 air, as samples are transferred in disinfected, "
    "lidded containers through the layered cleanroom suites. Furthermore, the colony recovery occurred in the lower-classified ISO 8 anteroom environment, "
    "which is physically segregated from the ISO 5 processing zone."
)

p13 = (
    "In addition, considering the facility's layered disinfection program, controlled unidirectional airflow, and cleanroom design, it is unlikely "
    "that the microbial contaminant detected in the ISO 8 environment impacted on the sample processed within the ISO 5 area of the ISO 7 cleanroom (Suite 114B)."
)

p14 = (
    "The absence of contamination on analyst glove plates and work-surface environmental monitoring plates collected on the date of testing indicates "
    "that there was no viable transfer of contaminants to the ISO 5 biological safety cabinet (BSC). Additionally, the lack of contamination in other samples "
    "processed during the same testing session further demonstrates that the testing environment was operating in optimal condition."
)

p15 = (
    "Therefore, considering that no viable organisms were recovered from the ISO 5 environment, personnel monitoring results were acceptable on the date "
    "of testing, and the environmental isolates were not recovered from locations or surfaces directly involved in sample preparation or testing, the "
    "environmental isolate is not considered a credible source of the contamination detected in the test sample."
)

p16 = (
    "The analysts confirmed full compliance with cleaning procedures as outlined in MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology) "
    "and MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p17 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 cleanroom, and its containing "
    f"ISO 5 BSCs for Cleanroom suite CR114 was performed on {data['monthly_cleaning_date_full']}, as per MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    "During both cleaning cycles, it was documented that all H2O2 indicators passed. This confirms the efficient monthly cleaning of all three parts of Cleanroom suite CR114."
)

p18 = (
    f"Analyzing a 6-month sample history for {data['client_name']}, this specific analyte \"{data['sample_name']}\" has had no prior failures using "
    f"USP <71> / EP 2.6.1 Sterility Test during this period. This sample was submitted as part of a Beyond-Use Date (BUD) stability study "
    f"for lot {data['lot_number']}. The baseline T0 time point (tested on 06 Aug 2026 by analyst GL) yielded valid passing results for USP <71> sterility."
)

p19 = (
    "To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review was conducted of all samples "
    f"processed on the same day ({data['process_date_full']}). Sample {data['sample_id_pure']} was the 4th sample processed in the batch. All other samples "
    "processed by the analyst and other analysts that day tested negative. These findings suggest that cross-contamination between samples is highly unlikely."
)

p20 = (
    "Based on the observations outlined above, it is unlikely that the failing results were due to reagents, supplies, the cleanroom environment, "
    "the process, or analyst involvement. Consequently, the possibility of laboratory error contributing to this failure is minimal and the original "
    "result is deemed to be valid."
)

text_field_50 = "\r \r".join([p12, p13, p14, p15, p16, p17, p18, p19, p20])

# --- PAGE 5 (Text Field 51) ---
writer_initial = "QYC"
text_field_51 = f"N/A {writer_initial} {datetime.now().strftime('%d%b%y')}"

# Assemble Master Narrative for Word Template
smart_phase1_full = f"{text_field_49}\n\n{text_field_50}"

data["smart_phase1_summary"] = smart_phase1_full
data["equipment_summary"] = p5
data["narrative_summary"] = p11
data["sample_history_paragraph"] = p18
data["cross_contamination_summary"] = p19
data["smart_comment_interview"] = "Yes, analysts Andrew Carrillo and Alex Saravia were interviewed comprehensively."
data["smart_comment_samples"] = f"Yes, sample ID: {data['sample_id_pure']}"
data["smart_comment_records"] = f"Yes, Information is available in EagleTrax under {data['sample_id_pure']}"
data["smart_comment_storage"] = f"Yes, the sample was stored as per client's instructions. Information is available in EagleTrax Sample Location History under {data['sample_id_pure']}"
data["smart_personnel_block"] = (
    "Prepping Analyst:\nAndrew Carrillo (AC)\n\n"
    "Processing Analyst:\nAlex Saravia (ES)\n\n"
    "Reading Analyst:\nAndrew Carrillo (AC)"
)
data["analyst_signature"] = f"Alex Saravia (Written by: {data['writer_name']})"
data["smart_incident_opening"] = f"On {data['test_date_full']}, sample {data['sample_id']} was found positive for viable microorganisms after USP <71> sterility testing."
data["smart_cr_id"] = "CR E001736"
data["usp71_id"] = f"E00{data['bsc_id']}"
data["reader_name"] = data["reading_name"]

# 3. Helper functions for table formatting
def set_cell_hyperlink(cell, url, text):
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    part = p.part
    r_id = part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink_xml = (
        f'<w:hyperlink xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        f'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
        f'r:id="{r_id}" w:history="1">'
        f'<w:r>'
        f'<w:rPr>'
        f'<w:rStyle w:val="Hyperlink"/>'
        f'<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        f'<w:color w:val="467886"/>'
        f'<w:sz w:val="15"/>'
        f'<w:szCs w:val="15"/>'
        f'<w:u w:val="single"/>'
        f'</w:rPr>'
        f'<w:t>{text}</w:t>'
        f'</w:r>'
        f'</w:hyperlink>'
    )
    p._p.append(parse_xml(hyperlink_xml))
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

def update_cell_text(cell, text, bold=False, italic=False, font_size=Pt(7.0), align=docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER):
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = align
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    run = p.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.name = "Times New Roman"
    run.font.size = font_size
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

# 4. Generate Standalone Tables Document with Strict 1-Page Constraint
# Header matching OOS-261987: Processing Analyst | Reading Analyst | Sample ID | Related Microbial ID | Media with Microbial growth | Morphology Description
out_doc_tables = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
doc_orig = docx.Document(TABLE_INPUT_DOCX)

doc_clean = docx.Document()
sec = doc_clean.sections[0]
sec.top_margin = Inches(0.4)
sec.bottom_margin = Inches(0.4)
sec.left_margin = Inches(0.45)
sec.right_margin = Inches(0.45)

# Add Table 1 Header
p_t1 = doc_clean.add_paragraph()
p_t1.paragraph_format.space_before = Pt(0)
p_t1.paragraph_format.space_after = Pt(3)
r_t1 = p_t1.add_run(f"Table 1: Information for {data['sample_id']} under investigation")
r_t1.bold = True
r_t1.font.name = "Times New Roman"
r_t1.font.size = Pt(9.5)

# Table 1: exactly matching OOS-261987 columns
t1_clean = doc_clean.add_table(rows=2, cols=6)
t1_clean.style = 'Table Grid'
t1_clean.autofit = False

t1_headers = [
    "Processing Analyst",
    "Reading Analyst",
    "Sample ID",
    "Related Microbial ID",
    "Media with Microbial growth",
    "Morphology Description"
]
for c_idx, h_text in enumerate(t1_headers):
    update_cell_text(t1_clean.rows[0].cells[c_idx], h_text, bold=True, font_size=Pt(7.5))

# Populate Table 1 row 1
r1_clean = t1_clean.rows[1]
update_cell_text(r1_clean.cells[0], "Alex Saravia", font_size=Pt(7.5))
update_cell_text(r1_clean.cells[1], "Andrew Carrillo", font_size=Pt(7.5))
set_cell_hyperlink(r1_clean.cells[2], data["sample_url"], data["sample_id"])
set_cell_hyperlink(r1_clean.cells[3], data["positive_id_url"], data["positive_id"])
update_cell_text(r1_clean.cells[4], "1 x 100 mL TSB", font_size=Pt(7.5))
update_cell_text(r1_clean.cells[5], "Paenibacillus lautus\n(Gram (+) rods)", font_size=Pt(7.5))

# Add Table 2 Header
p_t2 = doc_clean.add_paragraph()
p_t2.paragraph_format.space_before = Pt(8)
p_t2.paragraph_format.space_after = Pt(3)
r_t2 = p_t2.add_run("Table 2: Environmental Monitoring for Analyst & Cleanroom")
r_t2.bold = True
r_t2.font.name = "Times New Roman"
r_t2.font.size = Pt(9.5)

# Table 2: 16 rows, 9 columns
t2_orig = doc_orig.tables[1]
t2_clean = doc_clean.add_table(rows=len(t2_orig.rows), cols=len(t2_orig.columns))
t2_clean.style = 'Table Grid'
t2_clean.autofit = False

# Row 0: Headers
for c_idx, cell in enumerate(t2_orig.rows[0].cells):
    update_cell_text(t2_clean.rows[0].cells[c_idx], cell.text.strip(), bold=True, font_size=Pt(7.0))

# Row 1: Merged header
t2_clean.rows[1].cells[0].merge(t2_clean.rows[1].cells[-1])
update_cell_text(t2_clean.rows[1].cells[0], "Personnel EM Bracketing 31Aug2026", bold=True, font_size=Pt(7.5))

# Personnel rows (2, 3, 4)
em_personnel_data = [
    ("Personal (Left Touch and Right Touch)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Personal (Left Touch and Right Touch)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Personal (Left Touch and Right Touch)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_personnel_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[2 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 5: Merged BSC header
t2_clean.rows[5].cells[0].merge(t2_clean.rows[5].cells[-1])
update_cell_text(t2_clean.rows[5].cells[0], "Biological Safety Cabinet EM Bracketing Biological Safety Cabinet (BSC) E001316", bold=True, font_size=Pt(7.5))

# Surface sampling (6, 7, 8)
em_surf_data = [
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Surface Sampling of ISO 5 (4 locations)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_surf_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[6 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Settling sampling (9, 10, 11)
em_sett_data = [
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "28 Aug 2026", "ES", "Date Before Testing", "No growth", "N/A", "N/A", "None"),
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "31 Aug 2026", "ES", "Date of Testing", "No growth", "N/A", "N/A", "None"),
    ("Settling Sampling of ISO 5 (2 locations)", "Daily", "01 Sep 2026", "ES", "Date After Testing", "No growth", "N/A", "N/A", "None")
]
for r_offset, row_vals in enumerate(em_sett_data):
    for c_idx, val in enumerate(row_vals):
        align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        update_cell_text(t2_clean.rows[9 + r_offset].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 12: Weekly Active Air header
t2_clean.rows[12].cells[0].merge(t2_clean.rows[12].cells[-1])
update_cell_text(t2_clean.rows[12].cells[0], "Weekly Active Air Sampling of CR 114 (E001736)", bold=True, font_size=Pt(7.5))

# Row 13: Active Air data
air_vals = ("Active Air Sampling of Cleanrooms", "Weekly", "04 Sep 2026", "SMO", "Week of Testing", "1 CFU\n(ISO 8 114)", "ETX-260914-0487", "Pending", "None")
for c_idx, val in enumerate(air_vals):
    align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    update_cell_text(t2_clean.rows[13].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Row 14: Surface Sampling Anteroom header
t2_clean.rows[14].cells[0].merge(t2_clean.rows[14].cells[-1])
update_cell_text(t2_clean.rows[14].cells[0], "Surface Sampling of Anteroom and Cleanroom of CR 114 (E001736)", bold=True, font_size=Pt(7.5))

# Row 15: Cleanroom surface data
clean_vals = ("Surface Sampling of Cleanrooms", "Weekly", "04 Sep 2026", "SMO", "Week of Testing", "No growth", "N/A", "N/A", "None")
for c_idx, val in enumerate(clean_vals):
    align = docx.enum.text.WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    update_cell_text(t2_clean.rows[15].cells[c_idx], val, font_size=Pt(7.0), align=align)

# Set row heights tight to guarantee 1 page
for t in [t1_clean, t2_clean]:
    for row in t.rows:
        trPr = row._tr.get_or_add_trPr()
        trHeight = parse_xml(f'<w:trHeight xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" w:val="220" w:hRule="atLeast"/>')
        trPr.append(trHeight)

doc_clean.save(out_doc_tables)
print("Saved Standalone Tables Docx to:", out_doc_tables)

# 5. Export Standalone Tables Docx to PDF via Word COM
out_pdf_tables = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
try:
    word = win32com.client.DispatchEx("Word.Application")
    word.Visible = False
    try:
        d = word.Documents.Open(os.path.abspath(out_doc_tables), ReadOnly=True)
        d.SaveAs(os.path.abspath(out_pdf_tables), FileFormat=17)
        d.Close(SaveChanges=False)
        print("Saved Standalone Tables PDF via Word to:", out_pdf_tables)
    finally:
        word.Quit()
except Exception as e:
    print(f"Word COM export notice: {e}")

# Verify Tables PDF Page Count
r_check = PdfReader(out_pdf_tables)
print(f"Verified Tables PDF Page Count: {len(r_check.pages)} (Must be 1)")

# 6. Render Master Word Report
out_doc_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
primary_tpl = "USP71 OOS P1 template.docx" if os.path.exists("USP71 OOS P1 template.docx") else "USP71 OOS P1 template 0.docx"
tpl_report = DocxTemplate(primary_tpl)
tpl_report.render(data)

# Replace Table 2 & Table 3 in Master Word Report with the updated clean Table 1 & Table 2
if len(tpl_report.docx.tables) >= 3:
    t2_elem = tpl_report.docx.tables[1]._element
    p2_parent = t2_elem.getparent()
    idx2 = p2_parent.index(t2_elem)
    p2_parent.remove(t2_elem)
    new_t1_elem = copy.deepcopy(t1_clean._element)
    p2_parent.insert(idx2, new_t1_elem)

    t3_elem = tpl_report.docx.tables[2]._element
    p3_parent = t3_elem.getparent()
    idx3 = p3_parent.index(t3_elem)
    p3_parent.remove(t3_elem)
    new_t2_elem = copy.deepcopy(t2_clean._element)
    p3_parent.insert(idx3, new_t2_elem)

# Clean up paragraph titles above tables in master report
for p in tpl_report.docx.paragraphs:
    if "Table 1:" in p.text:
        p.text = f"Table 1: Information for {data['sample_id']} under investigation"
        p.runs[0].bold = True
    elif "Table 2:" in p.text:
        p.text = "Table 2: Environmental Monitoring for Analyst & Cleanroom"
        p.runs[0].bold = True

tpl_report.save(out_doc_report)
print("Saved Master Word Report to:", out_doc_report)

# 7. Render Official PDF Form (using CORP-FORM-21 / USP71 base PDF)
base_pdf = "USP71 OOS P1 template.pdf"
pdf_map = {
    'Text Field57': data['oos_id'],
    'Date Field0': "31-Aug-2026",
    'Date Field1': "07-Sep-2026",
    'Date Field2': "07-Sep-2026",
    'Date Field3': "07-Sep-2026",
    'Text Field1': data['test_name'],
    'Text Field2': data['sample_id'],
    'Text Field3': data['smart_personnel_block'],
    'Text Field4': data['sample_name'] + "\n\n\n\n",
    'Text Field5': data['dosage_form'],
    'Text Field6': data['lot_number'],
    'Text Field7': data['smart_incident_opening'] + "\n\n",
    'Text Field8': data['test_method'],
    'Text Field9': data['sop_effective_date'],
    'Text Field10': data['sop_rev'],
    'Text Field11': "Pass/Fail",
    'Text Field12': data['qa_notified'],
    'Text Field0': data['analyst_signature'],
    'Text Field13': data['smart_comment_interview'],
    'Text Field14': data['smart_comment_samples'],
    'Text Field15': f"Yes, as per {data['test_method']}",
    'Text Field16': f"Yes, as per {data['test_method']}",
    'Text Field17': data['smart_comment_records'],
    'Text Field18': "Yes, the analysts are trained and qualified by quality to perform the test",
    'Text Field19': "Not Applicable",
    'Text Field20': "Not Applicable",
    'Text Field21': data['smart_comment_storage'],
    'Text Field22': (
        "Process Consumables:\r\n"
        "Information is available in EagleTrax Sample Consumables section\r\n \r\n"
        "Environmental Plates:\r\n"
        "TSA and Surface Plate: see attached environmental logs\r\n \r\n"
        "Monthly Cleaning:\r\n"
        "H2O2 strips and IPA: See attached monthly cleaning logs"
    ),
    'Text Field23': (
        "Process Consumables:\r\n"
        "Information is available in EagleTrax Sample Consumables section\r\n \r\n"
        "Environmental Plates:\r\n"
        "TSA and Surface Plate: see attached environmental logs\r\n \r\n"
        "Monthly Cleaning:\r\n"
        "H2O2 strips and IPA: See attached monthly cleaning logs"
    ),
    'Text Field24': "Not applicable",
    'Text Field25': "Not applicable",
    'Text Field26': "Not applicable",
    'Text Field27': "Not applicable",
    'Text Field28': "Not applicable",
    'Text Field29': "Not applicable",
    'Text Field30': f"ISO 5 BSC E00{data['bsc_id']}",
    'Text Field31': "Jun 2027",
    'Text Field32': data['smart_cr_id'],
    'Text Field33': "Dec 2026",
    'Text Field34': "Not applicable",
    'Text Field35': "Not applicable",
    'Text Field36': "Not applicable",
    'Text Field37': "Not applicable",
    'Text Field38': "See Phase I Summary",
    'Text Field39': "See Phase I Summary",
    'Text Field40': "See Phase I Summary",
    'Text Field41': "See Phase I Summary",
    'Text Field42': "See Phase I Summary",
    'Text Field43': (
        "Incubator E001356 \r\n(Monitored by\r\nSensor E001450)\r\n \r\n"
        "Incubator E001357\r\n(Monitored by \r\nSensor E001449)\r\n \r\n"
        "Incubator E001034\r\n(Monitored by \r\nSensor E001501)\r\n \r\n"
        "Incubator E001031\r\n(Monitored by\r\nSensor E001505)"
    ),
    'Text Field44': (
        "Jan 2027\r\n \r\nFeb 2027\r\n \r\n"
        "Jan 2027\r\n \r\nFeb 2027\r\n \r\n"
        "Aug 2027\r\n \r\nFeb 2027\r\n \r\n"
        "Aug 2027\r\n \r\nFeb 2027"
    ),
    'Text Field45': "See Phase I Summary",
    'Text Field46': "Not applicable",
    'Text Field47': "Not applicable",
    'Text Field48': f"N/A {writer_initial} {datetime.now().strftime('%d%b%y')}",
    'Text Field49': text_field_49,
    'Text Field50': text_field_50,
    'Text Field51': text_field_51,
    'Text Field53': data['writer_name'],
    'Text Field54': ""
}

# Checkboxes exactly matching OOS-261987
checkbox_fields = {
    'Check Box0': '/Yes',
    'Check Box1': '/Yes',
    'Check Box2': '/Yes',
    'Check Box4': '/Yes',
    'Check Box7': '/Yes',
    'Check Box10': '/Yes',
    'Check Box13': '/Yes',
    'Check Box16': '/Yes',
    'Check Box19': '/Yes',
    'Check Box24': '/Yes',
    'Check Box27': '/Yes',
    'Check Box28': '/Yes',
    'Check Box32': '/Yes',
    'Check Box34': '/Yes',
    'Check Box38': '/Yes',
    'Check Box42': '/Yes',
    'Check Box43': '/Yes',
    'Check Box48': '/Yes',
    'Check Box51': '/Yes',
    'Check Box52': '/Yes',
    'Check Box55': '/Yes',
    'Check Box60': '/Yes',
    'Check Box63': '/Yes',
    'Check Box66': '/Yes',
    'Check Box69': '/Yes',
    'Check Box72': '/Yes',
    'Check Box73': '/Yes',
    'Check Box78': '/Yes',
    'Check Box79': '/Yes',
    'Check Box88': '/Yes',  # No lab error - original result valid
}
pdf_map.update(checkbox_fields)

writer = PdfWriter(clone_from=base_pdf)
while len(writer.pages) > 6:
    del writer.pages[-1]

for p in writer.pages:
    writer.update_page_form_field_values(p, pdf_map)

# Append Tables PDF as Page 7
if os.path.exists(out_pdf_tables):
    table_reader = PdfReader(out_pdf_tables)
    for table_page in table_reader.pages:
        writer.add_page(table_page)
    print(f"Appended Tables PDF to form. Total pages: {len(writer.pages)} (Must be 7)")

out_pdf_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
with open(out_pdf_report, "wb") as f:
    writer.write(f)
print("Saved complete PDF Report to:", out_pdf_report)

# Adjust font sizes in PDF narrative fields to ensure neat fit
try:
    import fitz
    doc_fitz = fitz.open(out_pdf_report)
    font_sizes = {
        'Text Field49': 8.5,
        'Text Field50': 8.5,
        'Text Field51': 7.8,
    }
    for page in doc_fitz:
        for w in page.widgets():
            if w.field_name in font_sizes:
                w.text_fontsize = font_sizes[w.field_name]
                w.update()
    temp_pdf_out = out_pdf_report + ".tmp.pdf"
    doc_fitz.save(temp_pdf_out)
    doc_fitz.close()
    shutil.move(temp_pdf_out, out_pdf_report)
    print("Successfully fine-tuned narrative font sizes with PyMuPDF.")
except Exception as e:
    print(f"PyMuPDF font tuning notice: {e}")

# 8. Save State Data (.txt / .json)
out_json_path = os.path.join(OUTPUT_DIR, f"SAVE_OOS-{data['oos_id']} {data['client_name']} - USP71.txt")
with open(out_json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
print("Saved session state JSON to:", out_json_path)

# 9. Sync all deliverables to Documents directory
files_to_sync = [
    out_doc_report,
    out_doc_tables,
    out_pdf_report,
    out_pdf_tables,
    out_json_path
]
for fpath in files_to_sync:
    if fpath and os.path.exists(fpath):
        dest = os.path.join(DOCUMENTS_DIR, os.path.basename(fpath))
        try:
            shutil.copy2(fpath, dest)
            print(f"Synced to Documents: {dest}")
        except PermissionError:
            print(f"Notice: {dest} is open in another app, skipped overwrite.")
        except Exception as e:
            print(f"Sync notice: {e}")

print("\n--- ALL GOLD-STANDARD GENERATION COMPLETED SUCCESSFULLY! ---")
