"""
Script: process_oos_262017.py
Purpose: Complete generation of Celsis OOS-262017 report files (Word and AcroForm PDF)
         incorporating all data extracted from 1.pdf, 31AUG26.pdf, and RS QA review standards.
"""

import os
import sys
import shutil
import fitz  # PyMuPDF
import docx
from docx.shared import Pt
from docx.oxml import parse_xml
from docx.opc.constants import RELATIONSHIP_TYPE
from docxtpl import DocxTemplate
import win32com.client
import gc

sys.stdout.reconfigure(encoding='utf-8')

SAMPLE_URL = "https://etrax.eagleanalytical.com/Submission/Details/OIX27OGNKb64xLa70p0RRQ__"
MICRO_URL = "https://etrax.eagleanalytical.com/SubmissionTest/Details/OCvPHc7TodycYzvim2KtjQ__"
URL_0487 = "https://etrax.eagleanalytical.com/SubmissionTest/Details/fd3G2StZClcy1TP2ES6BLw__"
URL_0112 = "https://etrax.eagleanalytical.com/SubmissionTest/Details/NcOow%24YzQzS3BNKfJsb8Ug__#TestDetails"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"

# ==========================================
# 1. NARRATIVE TEXT
# ==========================================
p1 = (
    "All analysts involved in the preparation, processing, aliquoting, and reading of the samples, "
    "Elysse Nioupin, Elizabeth Sanchez, America Alanis, and Cuong Du, were interviewed comprehensively. "
    "Their responses are documented throughout this report. "
    "This investigation was performed as per MICRO-SOP-53 Sterility Test Out-of-Specification (OOS) Investigation Procedure."
)

p2 = (
    "Upon arrival on 21 Aug 2026, the sample was stored refrigerated in accordance with the client instructions. Both sample "
    "prepping analyst Elysse Nioupin and processing analyst Elizabeth Sanchez inspected the sample during preparation "
    "and processing. No leaks or visible turbidity were observed, and no evidence of compromised container "
    "integrity was identified."
)

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to supplier "
    "recommendations, and their integrity was visually verified before utilization. Moreover, all reagents "
    "and supplies had valid expiration dates. The functionality of all equipment was confirmed by reviewing "
    "data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The cleanroom suite used for processing procedures (CR114) comprises three interconnected sections: "
    "the innermost ISO 7 cleanroom (114B), which connects to the middle ISO 7 buffer room (114A), and then "
    "to the outermost ISO 8 anteroom (114). A positive air pressure system is maintained throughout the suite "
    "to ensure controlled, unidirectional airflow from 114B through 114A and into 114."
)

p5 = (
    "The innermost ISO 7 cleanroom 114B and its ISO 5 BSC E001316 were thoroughly cleaned and prepared before "
    "initiating testing by analyst Elizabeth Sanchez as per MICRO-SOP-2 (Environmental Monitoring of the Clean "
    "Room Facility) and MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). For Celsis "
    "aliquoting, intermediate ISO 7 buffer room 114A and its ISO 5 BSC E001798 were thoroughly cleaned and "
    "prepared by analyst America Alanis before initiating testing as per MICRO-SOP-44 and MICRO-SOP-9. Both BSCs, "
    "E001316 in 114B and E001798 in 114A, were certified and approved by the Engineering and Quality Assurance "
    "teams prior to use."
)

p6 = (
    "On 24 Aug 2026, the sample vials for ETX-260821-0259 were received from the Sample Submissions team and brought "
    "into the Sterile Microbiology lab. Upon arrival, each vial was sprayed with an acidified bleach disinfectant, "
    "placed into pre-disinfected bins, and allowed a 10-minute contact time. Secondary disinfection was performed in "
    "the ISO 8 anteroom (114), where the vials were again treated with acidified bleach with a 10-minute contact time "
    "before transfer into cleanroom 114B. Inside 114B, processing analyst Elizabeth Sanchez performed a final disinfection "
    "step with a 10-minute contact time. Once fully disinfected, the vials were transferred into the ISO 5 BSC E001316, "
    "placed on the disinfected work surface, aseptically opened, and tested in accordance with MICRO-SOP-44. Direct "
    "inoculation was performed by adding a total of 84 mL of sample across 14 vials (6 mL per vial), using nine 300 mL "
    "FTM jars and nine 300 mL TSB jars, in accordance with suitability method record: ETX-251218-0432. Tween 80 (Lot# "
    "0000606420, Exp: 01Sep2027) was incorporated into the test procedure per suitability requirements. Accordingly, a "
    "matching negative control with the same modifications was prepared and handled identically to actual samples. Following "
    "testing, the media bottles were transferred into incubators E001356 and E001357 to initiate incubation."
)

p7 = (
    "Upon completion of incubation on 31 Aug 2026, the media bottles for ETX-260821-0259 were disinfected and transferred "
    "to the middle ISO 7 buffer room (114A) for the aliquoting step per MICRO-SOP-44 (Celsis Sterility Testing). In "
    "cleanroom 114A, the media bottles were disinfected one more time before transfer into the ISO 5 BSC E001798 located "
    "in cleanroom 114A. In ISO 5 BSC E001798, the sample was aliquoted into assay cuvettes by analyst America Alanis. Following "
    "aliquoting, Celsis Sterility Reading was performed in accordance with MICRO-SOP-44 by analyst Cuong Du on instrument "
    "Advance 2 (E002222)."
)

p8 = (
    "Following the reading, sample ETX-260821-0259 was found to yield positive readings in two of the 300 mL TSB media jars "
    "(Bottle 1 and Bottle 6). Bottle 1 yielded > 9,999,999 RLU (instrument overload) on both the initial read and confirmation re-read. "
    "Bottle 6 yielded 1,275 RLU (duplicate reading tubes 1,301 RLU and 1,249 RLU, %CV 2%) on the initial read and 1,386 RLU (duplicate "
    "reading tubes 1,481 RLU and 1,291 RLU, %CV 7%) upon confirmation re-read, both exceeding the method cutoffs of 1,197.0 RLU and "
    "1,165.5 RLU respectively, where the corresponding TSB negative control yielded 399 RLU and 389 RLU. All other TSB bottles (Bottles "
    "2, 3, 4, 5, 7, 8, 9) and all nine FTM sample bottles in the same batch tested negative (FTM cutoff 5,416.5 RLU, FTM negative control "
    "1,806 RLU). The %CV from duplicate reading tubes for the positive TSB bottles was well within specification (< 30%). Additionally, "
    "all Daily Controls, including Instrument Blank (8 RLU), Reagent Blank (77 RLU, %CV 1%), and ATP Positive Control (103,864 RLU, "
    "%CV 3%), met defined acceptance criteria with %CV below 30%."
)

p9 = (
    "Following the OOS result, the positive TSB bottles for ETX-260821-0259 were submitted for Differential Staining and "
    "Microbial Identification under ETX-260831-0608. Microbial growth was successfully recovered by subculture on solid growth media, "
    "and differential staining visualized Gram-positive rods. Microbial identification confirmed the isolate as Terribacillus goriensis, "
    "as presented in Table 1."
)

p10 = (
    "The culture media utilized were within their expiry period (TSB lot 07102026-1, Exp: 08Oct2026). The negative culture media bottles "
    "for the direct inoculation method for the original culture were handled, processed, and incubated in a manner identical to that "
    "of actual samples. No microbial growth was observed in the corresponding negative control."
)

p11 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 "
    "cleanroom, and its containing ISO 5 Biosafety Cabinets for CR114 was performed on 16 Aug 2026, as per MICRO-SOP-9 "
    "(Cleaning and Disinfecting Procedure for Microbiology). It was documented that all H2O2 indicators passed. This confirms "
    "the efficient monthly cleaning of all three parts of Cleanroom 114 prior to testing."
)

p12 = (
    "Attached Tables 2 and 3 present the environmental monitoring results for the duration of testing. The environmental "
    "monitoring (EM) plates were incubated for no less than 48 hours at 30-35°C and no less than an additional five days at "
    "20-25°C as per MICRO-SOP-2 (Environmental Monitoring of the Cleanroom Facility). Table 2 pertains to Environmental "
    "Monitoring performed during Celsis Sterility Processing, and Table 3 pertains to Environmental Monitoring performed during "
    "Celsis Sterility Aliquoting."
)

p13 = (
    "A review of the Environmental Monitoring (EM) results for the relevant Celsis Sterility processing period showed no "
    "microbial growth on personnel monitoring plates, settling plates, or ISO 5 BSC E001316 surface sampling plates on the date "
    "of testing (24Aug26), the preceding sampling date (21Aug26), or the subsequent sampling date (25Aug26). Weekly active air "
    "and surface sampling of the cleanroom suite associated with processing was performed on 25Aug26. No microbial recovery "
    "was observed from weekly surface sampling of the cleanroom suite. Active air sampling showed recovery of 4 CFU (ETX-260901-0112) "
    "in the ISO 8 area, identified as 3 Gram (+) cocci and 1 Hyphae, with zero recovery observed in the ISO 7 buffer or cleanrooms."
)

p14 = (
    "After reviewing the Environmental Monitoring (EM) results for the relevant Celsis Sterility aliquoting period, "
    "no microbial growth was observed on personnel monitoring plates, ISO 5 BSC E001798 surface sampling plates, or settling "
    "plates on the date of aliquoting (31Aug26), the preceding sampling date (28Aug26), or the subsequent sampling date "
    "(01Sep26). Weekly active air sampling of the cleanroom suite performed on 04Sep26 showed recovery of 2 CFU (ETX-260914-0487) "
    "in the ISO 8 area, identified as Corynebacterium ureicelerivorans and Mycobacterium grossiae, with zero recovery in the ISO 7 "
    "buffer or cleanrooms, and weekly surface sampling of the cleanroom suite showed no growth."
)

p15 = (
    "Evaluation of Environmental Monitoring Results: It is important to note that, for both processing and aliquoting activities, "
    "the samples are processed within validated ISO 5 BSCs (E001316 and E001798 respectively). Although microbial recovery was "
    "observed from weekly active air monitoring in the outermost ISO 8 room 114 background environment in cleanroom suite "
    "(CR114), these recoveries were not obtained from the ISO 5 processing environment or the ISO 7 cleanroom environment."
)

p16 = (
    "The absence of microbial recovery from both the processing and the aliquoting analyst glove plates, ISO 5 BSC surface "
    "monitoring plates, and ISO 5 settling plates indicates that no identifiable contamination transfer pathway existed between "
    "the monitored background cleanroom environment and the ISO 5 critical processing areas. Samples were also prepared and "
    "transferred into disinfected, lidded containers and transported on carts within the controlled cleanroom environment. "
    "Therefore, while the active air results demonstrate microbial recovery in the surrounding ISO 8 area, there is no evidence "
    "that the recovery originated from, or affected, the ISO 5 BSC environment where the test sample was handled and processed."
)

p17 = (
    "All analysts confirmed full compliance with cleaning procedures as outlined in MICRO-SOP-9 (Cleaning and Disinfecting "
    "Procedure for Microbiology) and MICRO-SOP-44 (Celsis Sterility Testing). A review of the available data confirms that "
    "the cleanroom and equipment conditions remained within acceptable parameters. No deviations or obvious signs of laboratory "
    "error during processing and aliquoting were noted from analysts."
)

p18 = (
    "No other sample processed by analyst Elizabeth Sanchez on 24 Aug 2026 and aliquoted by analyst America Alanis on 31 Aug 2026, "
    "failed Celsis Sterility testing that day. To assess the potential for sample-to-sample contamination contributing to the "
    "positive results, a comprehensive review was conducted of all samples processed in the same batch. All other samples processed "
    "by the same analyst on the day of testing were found to test negative for microbial growth. These findings suggest that "
    "cross-contamination between samples is unlikely."
)

p19 = (
    'Analyzing a 6-month sample history for Revive Rx Pharmacy - PO Required (E00927) indicates that this specific analyte '
    '"Tesamorelin 12 mg per Vial" (Lot: 16590773) has had no prior failures using the Celsis Sterility testing during this period, '
    'and review of lot history confirms no other submissions of this lot failed testing.'
)

p21 = (
    "Based on the laboratory investigation, no assignable laboratory cause was identified involving the analyst, instrument, "
    "reagents, supplies, or monitored laboratory environment. The initial Celsis OOS result therefore remains valid in "
    "accordance with the applicable laboratory OOS procedure."
)

text_field_49 = "\n\n".join([p1, p2, p3, p4, p5])
text_field_50 = "\n\n".join([p6, p7, p8, p9, p10, p11, p12])
text_field_51 = "\n\n".join([p13, p14, p15, p16, p17, p18, p19, p21])

smart_phase1_full = "\n\n".join([
    p1, p2, p3, p4, p5, p6, p7, p8, p9, p10,
    p11, p12, p13, p14, p15, p16, p17, p18, p19, p21
])

# ==========================================
# 2. RENDER WORD DOCUMENT
# ==========================================
print("\n--- [1/3] Rendering Word Document ---")

personnel_block = (
    "Prepping Analyst:\nElysse Nioupin (EN)\n\n"
    "Processing Analyst:\nElizabeth Sanchez (ES)\n\n"
    "Aliquoting Analyst:\nAmerica Alanis (ALA)\n\n"
    "Reading Analyst:\nCuong Du (CCD)"
)

word_context = {
    "oos_id": "262017",
    "client_name": "Revive Rx Pharmacy - PO Required (E00927)",
    "sample_id": "ETX-260821-0259",
    "sample_name": "Tesamorelin 12 mg per Vial",
    "lot_number": "16590773",
    "dosage_form": "Lyophilized",
    "test_date": "31Aug26",
    "process_date": "24Aug26",
    "received_data": "21Aug26",
    "prepper_name": "Elysse Nioupin",
    "prepper_initial": "EN",
    "analyst_name": "Elizabeth Sanchez",
    "analyst_initial": "ES",
    "aliquoting_name": "America Alanis",
    "aliquoting_initial": "ALA",
    "reading_name": "Cuong Du",
    "reading_initial": "CCD",
    "reader_name": "Cuong Du",
    "bsc_id": "1316",
    "cr_suit": "114",
    "smart_cr_id": "E001736 (CR 114)",
    "smart_scan_id": "E002222",
    "control_positive": "Celsis ATP Positive Control",
    "control_lot": "022601-1483",
    "control_data": "31 Jan 2027",
    "monthly_cleaning_date": "16 Aug 2026",
    "smart_personnel_block": personnel_block,
    "smart_incident_opening": "On 31Aug26, sample ETX-260821-0259 was found positive for viable microorganisms after Celsis sterility testing.",
    "smart_comment_interview": "Yes, Elysse Nioupin, Elizabeth Sanchez, America Alanis, and Cuong Du were interviewed comprehensively.",
    "smart_comment_samples": "Yes, Sample ID ETX-260821-0259",
    "smart_comment_records": "Not Applicable",
    "smart_comment_storage": "Yes, the sample was stored refrigerated as per client instructions. Information is available in EagleTrax Sample Location History under ETX-260821-0259",
    "report_header": "ETX-260821-0259\n\nRevive Rx Pharmacy - PO Required (E00927)",
    "analyst_signature": "Cuong Du (Written by: Qiyue Chen)",
    "smart_phase1_summary": smart_phase1_full,
    "smart_phase1_continued": "",
    "event_number": "",
    "confirm_number": "",
    "organism_morphology": "Terribacillus goriensis",
    "oos1_analyst_name": "N/A",
    "oos1_sample_id": "N/A",
    "oos1_sample_name": "N/A",
    "oos1_organism_morphology": "N/A",
}

main_docx_path = os.path.join(DESKTOP_DIR, "OOS-262017 Revive Rx Pharmacy - PO Required (E00927) - Celsis.docx")
main_docx_scratch = os.path.join(SCRIPT_DIR, "OOS-262017 Revive Rx Pharmacy - PO Required (E00927) - Celsis.docx")

tpl_main = DocxTemplate(os.path.join(ROOT_DIR, "Celsis OOS P1 template.docx"))
tpl_main.render(word_context)
tpl_main.save(main_docx_scratch)

# Add hyperlink to Table 1 in main docx if present
doc_main_mod = docx.Document(main_docx_scratch)

def set_cell_hyperlink(cell, url, text):
    cell.text = ''
    p = cell.paragraphs[0]
    p.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    part = p.part
    r_id = part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink_xml = (
        f'<w:hyperlink xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        f'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
        f'r:id="{r_id}" w:history="1">'
        f'<w:r>'
        f'<w:rPr>'
        f'<w:rStyle w:val="Hyperlink"/>'
        f'<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        f'<w:color w:val="0000FF"/>'
        f'<w:sz w:val="15"/>'
        f'<w:szCs w:val="15"/>'
        f'<w:u w:val="single"/>'
        f'</w:rPr>'
        f'<w:t>{text}</w:t>'
        f'</w:r>'
        f'</w:hyperlink>'
    )
    p._p.append(parse_xml(hyperlink_xml))
    cell.vertical_alignment = docx.enum.table.WD_CELL_VERTICAL_ALIGNMENT.CENTER

if len(doc_main_mod.tables) > 1 and len(doc_main_mod.tables[1].rows) > 1:
    set_cell_hyperlink(doc_main_mod.tables[1].rows[1].cells[2], SAMPLE_URL, "ETX-260821-0259")

doc_main_mod.save(main_docx_scratch)
try:
    doc_main_mod.save(main_docx_path)
    print(f"Generated Main DOCX: {main_docx_path}")
except PermissionError:
    print(f"Notice: {main_docx_path} is locked by Word, saved to {main_docx_scratch}")

# ==========================================
# 3. FILL FILLABLE PDF FORM
# ==========================================
print("\n--- [2/3] Filling AcroForm PDF Form ---")

pdf_template_path = os.path.join(ROOT_DIR, "Celsis OOS P1 template.pdf")
doc_pdf = fitz.open(pdf_template_path)

# Fill Page 1
page1 = doc_pdf[0]
for w in page1.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn == 'Text Field0': w.field_value = 'Cuong Du (Written by Qiyue Chen)'
    elif fn == 'Date Field0': w.field_value = '24-Aug-2026'
    elif fn == 'Date Field1': w.field_value = '31-Aug-2026'
    elif fn == 'Date Field2': w.field_value = '31-Aug-2026'
    elif fn == 'Text Field1': w.field_value = 'Celsis Sterility Test'
    elif fn == 'Text Field2': w.field_value = 'ETX-260821-0259'
    elif fn == 'Text Field3':
        w.field_value = (
            "Prepping Analyst:\r"
            "Elysse Nioupin (EN)\r \r"
            "Processing Analyst:\r"
            "Elizabeth Sanchez (ES)\r \r"
            "Aliquoting Analyst:\r"
            "America Alanis (ALA)\r \r"
            "Reading Analyst:\r"
            "Cuong Du (CCD)"
        )
    elif fn == 'Text Field4': w.field_value = 'Tesamorelin 12 mg per Vial'
    elif fn == 'Text Field5': w.field_value = 'Lyophilized'
    elif fn == 'Text Field6': w.field_value = '16590773'
    elif fn == 'Text Field7':
        w.field_value = 'On 31 Aug 2026, sample ETX-260821-0259 was found to be positive for growth after Celsis Sterility Testing'
    elif fn == 'Text Field8': w.field_value = 'MICRO-SOP-44'
    elif fn == 'Text Field9': w.field_value = '03-Jan-2025'
    elif fn == 'Text Field10': w.field_value = '01'
    elif fn == 'Text Field11': w.field_value = 'Pass/Fail'
    elif fn == 'Text Field12': w.field_value = 'Kathan Parikh'
    elif fn == 'Date Field3': w.field_value = '31-Aug-2026'
    elif fn == 'Text Field13':
        w.field_value = 'Yes, analysts Elysse Nioupin, Elizabeth Sanchez, America Alanis & Cuong Du were comprehensively interviewed.'
    elif fn == 'Text Field14': w.field_value = 'Yes, Sample ID ETX-260821-0259'
    elif fn in ['Text Field15', 'Text Field16']: w.field_value = 'Yes, as per MICRO-SOP-44'
    elif fn == 'Text Field17':
        w.field_value = 'Yes, Information is available in EagleTrax under ETX-260821-0259'
    elif fn == 'Text Field18': w.field_value = 'Yes, all analysts are trained and qualified by the quality department to perform the test'
    elif fn in ['Text Field19', 'Text Field20']: w.field_value = 'Not Applicable'
    elif fn == 'Text Field21':
        w.field_value = "Yes, the sample was stored refrigerated as per client's instructions"
    elif fn.startswith('Check Box'):
        page1_yes_boxes = {
            'Check Box0', 'Check Box1', 'Check Box2',
            'Check Box4', 'Check Box7', 'Check Box10', 'Check Box13',
            'Check Box16', 'Check Box19', 'Check Box24', 'Check Box27',
            'Check Box28', 'Check Box32', 'Check Box34', 'Check Box38'
        }
        w.field_value = 'Yes' if fn in page1_yes_boxes else 'Off'
    w.update()

# Fill Page 2
page2 = doc_pdf[1]
reagents_lots = (
    "Materials and Reagents\r"
    "TSB: 07102026-1\r"
    "FTM: 07102026-2\r"
    "Tween 80: 0000606420\r \r"
    "Celsis Reagents & Kits:\r"
    "Please refer to attached packet\r \r"
    "TSA / Surface Plates: See EM logs\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: 250409\r"
    "IPA: 01600581"
)

reagents_exp = (
    "Materials and Reagents\r"
    "TSB: 08 Oct 2026\r"
    "FTM: 08 Oct 2026\r"
    "Tween 80: 01 Sep 2027\r \r"
    "Celsis Reagents & Kits:\r"
    "Please refer to attached packet\r \r"
    "TSA / Surface Plates: See EM logs\r \r"
    "Monthly Cleaning:\r"
    "H2O2 strips: Apr 2027\r"
    "IPA: Sep 2027"
)

incubator_list = (
    "Incubator E001356 (Sensor E001450)\r \r"
    "Incubator E001357 (Sensor E001449)\r \r"
    "Incubator E001034 (Sensor E001501)\r \r"
    "Incubator E001031 (Sensor E001505)"
)

incubator_cal = (
    "Jan 2027 / Feb 2027\r \r"
    "Jan 2027 / Feb 2027\r \r"
    "Aug 2027 / Feb 2027\r \r"
    "Aug 2027 / Feb 2027"
)

for w in page2.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn == 'Text Field22':
        w.field_value = reagents_lots
    elif fn == 'Text Field23':
        w.field_value = reagents_exp
    elif fn == 'Text Field24': w.field_value = 'Celsis ATP Positive Control'
    elif fn == 'Text Field25': w.field_value = '022601-1483'
    elif fn == 'Text Field26': w.field_value = 'Jan 2027'
    elif fn in ['Text Field27', 'Text Field28', 'Text Field29']: w.field_value = 'Not Applicable'
    elif fn == 'Text Field30': w.field_value = 'E002222'
    elif fn == 'Text Field31': w.field_value = 'Sep 2026'
    elif fn == 'Text Field32':
        w.field_value = (
            "E001736 (CR114) BSC E001316\r \r"
            "E001736 (CR114) BSC E001798"
        )
    elif fn == 'Text Field33':
        w.field_value = (
            "Dec 2026 / Jun 2027\r \r"
            "Dec 2026 / Jun 2027"
        )
    elif fn == 'Text Field34': w.field_value = 'E002222'
    elif fn == 'Text Field35': w.field_value = 'Sep 2026'
    elif fn in ['Text Field36', 'Text Field37', 'Text Field38', 'Text Field39']:
        w.field_value = 'Not Applicable'
    elif fn in ['Text Field40', 'Text Field41', 'Text Field42', 'Text Field45']:
        w.field_value = 'See Phase I Summary'
    elif fn == 'Text Field43':
        w.field_value = incubator_list
    elif fn == 'Text Field44':
        w.field_value = incubator_cal
    elif fn.startswith('Check Box'):
        page2_yes_boxes = {
            'Check Box42', 'Check Box43', 'Check Box48', 'Check Box51',
            'Check Box52', 'Check Box55', 'Check Box58', 'Check Box63',
            'Check Box66', 'Check Box67', 'Check Box70', 'Check Box73'
        }
        w.field_value = 'Yes' if fn in page2_yes_boxes else 'Off'
    w.update()

# Fill Page 3
page3 = doc_pdf[2]
for w in page3.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn in ['Text Field46', 'Text Field47']: w.field_value = 'Not Applicable'
    elif fn == 'Text Field48': w.field_value = 'N/A CD 31Aug2026'
    elif fn == 'Text Field49': w.field_value = text_field_49
    elif fn.startswith('Check Box'):
        w.field_value = 'Yes' if fn == 'Check Box78' else 'Off'
    w.update()

# Fill Page 4
page4 = doc_pdf[3]
for w in page4.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn == 'Text Field50': w.field_value = text_field_50
    w.update()

# Fill Page 5
page5 = doc_pdf[4]
for w in page5.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn == 'Text Field51': w.field_value = text_field_51
    w.update()

# Fill Page 6
page6 = doc_pdf[5]
for w in page6.widgets():
    fn = w.field_name
    if fn == 'Text Field57': w.field_value = '262017'
    elif fn == 'Text Field52': w.field_value = 'Not Applicable'
    elif fn == 'Text Field53': w.field_value = 'Qiyue Chen'
    elif fn == 'Text Field54': w.field_value = 'Robin Seymour'
    elif fn.startswith('Check Box'):
        if fn == 'Check Box88':
            w.field_value = 'Yes'
        elif fn in ['Check Box87', 'Check Box89', 'Check Box90', 'Check Box91', 'Check Box92']:
            w.field_value = 'Off'
    w.update()

temp_filled_pdf = os.path.join(SCRIPT_DIR, "temp_filled_262017.pdf")
doc_pdf.save(temp_filled_pdf)
doc_pdf.close()

# ==========================================
# 4. CALIBRATED AUTO-FIT FONT SIZING (RULE 11)
# ==========================================
print("\n--- [3/3] Applying Rule 11 Calibrated Font Sizes to PDF ---")

doc_fix = fitz.open(temp_filled_pdf)

calibrated_font_sizes = {
    "Text Field0": 8.5,
    "Text Field1": 8.5,
    "Text Field2": 8.5,
    "Text Field3": 6.225,
    "Text Field4": 8.5,
    "Text Field5": 8.5,
    "Text Field6": 8.5,
    "Text Field7": 8.0,
    "Text Field8": 8.5,
    "Text Field9": 8.5,
    "Text Field10": 8.5,
    "Text Field11": 8.5,
    "Text Field12": 8.5,
    "Text Field13": 4.825,
    "Text Field14": 8.5,
    "Text Field15": 9.0,
    "Text Field16": 9.0,
    "Text Field17": 6.725,
    "Text Field18": 4.825,
    "Text Field19": 9.0,
    "Text Field20": 9.0,
    "Text Field21": 5.85,
    "Text Field22": 4.35,
    "Text Field23": 4.75,
    "Text Field24": 8.5,
    "Text Field25": 8.5,
    "Text Field26": 8.5,
    "Text Field27": 8.5,
    "Text Field28": 8.5,
    "Text Field29": 8.5,
    "Text Field30": 8.5,
    "Text Field31": 8.5,
    "Text Field32": 4.825,
    "Text Field33": 4.825,
    "Text Field34": 8.5,
    "Text Field35": 8.5,
    "Text Field36": 8.5,
    "Text Field37": 8.5,
    "Text Field38": 8.5,
    "Text Field39": 8.5,
    "Text Field40": 8.5,
    "Text Field41": 8.5,
    "Text Field42": 8.5,
    "Text Field43": 7.05,
    "Text Field44": 7.05,
    "Text Field45": 8.5,
    "Text Field46": 8.5,
    "Text Field47": 8.5,
    "Text Field48": 8.5,
    "Text Field49": 9.2,
    "Text Field50": 9.2,
    "Text Field51": 9.2,
    "Text Field52": 8.5,
    "Text Field53": 8.5,
    "Text Field54": 8.5,
    "Text Field57": 8.5,
    "Date Field0": 8.5,
    "Date Field1": 8.5,
    "Date Field2": 8.5,
    "Date Field3": 8.5,
}

for page in doc_fix:
    for w in page.widgets():
        fn = w.field_name
        if fn in calibrated_font_sizes:
            w.text_fontsize = calibrated_font_sizes[fn]
            w.update()

final_pdf_scratch = os.path.join(SCRIPT_DIR, "OOS-262017 Revive Rx Pharmacy - PO Required (E00927) - Celsis.pdf")
final_pdf_desktop = os.path.join(DESKTOP_DIR, "OOS-262017 Revive Rx Pharmacy - PO Required (E00927) - Celsis.pdf")

doc_fix.save(final_pdf_scratch)
doc_fix.close()

try:
    shutil.copy2(final_pdf_scratch, final_pdf_desktop)
    print(f"Generated Final PDF: {final_pdf_desktop}")
except PermissionError:
    print(f"Notice: {final_pdf_desktop} is locked by reader, saved to {final_pdf_scratch}")

print("\n=== All OOS-262017 deliverables generated successfully! ===")
