import os, sys, json, re, io, copy, shutil
from datetime import datetime

OOS_ROOT = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents\OOS"
sys.path.insert(0, OOS_ROOT)
os.chdir(OOS_ROOT)

import docx
from docx.shared import Pt, Inches
from docx.oxml import parse_xml
from docx.opc.constants import RELATIONSHIP_TYPE
from docxtpl import DocxTemplate
from pypdf import PdfWriter, PdfReader
import win32com.client
import fitz

DOCUMENTS_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Documents"
DESKTOP_DIR = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop"
OUTPUT_DIR = os.path.join(OOS_ROOT, "scratch")

print("--- STARTING USP <71> OOS-262098 FULL REPORT GENERATION ---")

# 1. Master Dataset
data = {
    "oos_id": "262098",
    "client_name": "Solyn LLC (E75000)",
    "sample_id": "ETX-260902-0505",
    "sample_id_pure": "ETX-260902-0505",
    "sample_url": "https://etrax.eagleanalytical.com/Submission/Details/%247Ydn%24JOiYgmsnaKjbxn-g__",
    "sample_name": "GLP3R/Cagrilinitide",
    "lot_number": "2608-216",
    "dosage_form": "Liquid",
    "test_name": "USP <71> / EP 2.6.1 Sterility (Every Day Read) Test",
    "test_method": "MICRO-SOP-5",
    "sop_effective_date": "24Jul2026",
    "sop_rev": "19",
    "method_suitability": "N/A",
    "method_performed": "Membrane Filtration",
    "amount_filtered": "3 vials",
    "process_date": "04Sep26",
    "process_date_full": "04 Sep 2026",
    "before_test": "03Sep26",
    "after_test": "08Sep26",
    "test_date": "10Sep26",
    "test_date_full": "10 Sep 2026",
    "received_data": "02Sep26",
    "incubation_time": "14",
    "positive_media": "1 x 100mL TSB bottle",
    "positive_id": "ETX-260910-0290",
    "positive_id_url": "https://etrax.eagleanalytical.com/Submission/Details?id=oZa2TD1UI-0eAJOFysBJ3A__",
    "positive_org": "Microbacterium sp. PM5, Gram (+) rods",
    "prepper_initial": "ES",
    "prepper_name": "Alex Saravia",
    "analyst_initial": "ES",
    "analyst_name": "Alex Saravia",
    "reading_initial": "EN",
    "reading_name": "Elysse Nioupin",
    "writer_name": "Qiyue Chen",
    "qa_manager": "Robin Seymour",
    "qa_notified": "Kathan Parikh",
    "bsc_id": "1316",
    "cr_suit": "114",
    "cr_id": "1736",
    "smart_cr_id": "CR 114 (E001736)",
    "suit": "B",
    "bsc_location": "innermost ISO 7 room",
    "monthly_cleaning_date": "30Aug26",
    "monthly_cleaning_date_full": "30 Aug 2026",
    "ftm_lot": "2567320",
    "ftm_exp": "12/16/2026",
    "tsb_lot": "2548010",
    "tsb_exp": "04/19/2027",
    "fluid_d_lot": "685561",
    "fluid_d_exp": "10/31/2026",
}

# 2. Build Narrative Paragraphs Split Exactly across Page 3 and Page 4
# Following Approved Gold Standard

# --- PAGE 3 (Text Field 49) ---
p1 = "All analysts involved in the prepping, processing, and reading of the sample – Alex Saravia and Elysse Nioupin, were interviewed comprehensively. Their answers are recorded throughout this document."

p2 = "Upon arrival, the sample was stored in accordance with the Client’s instructions. Analysts - Alex Saravia and Elysse Nioupin - verified the integrity of the sample throughout both the preparation and processing stages. No leaks or turbidity were observed at any point, verifying the integrity of the sample."

p3 = (
    "All reagents and supplies mentioned in the material section above were stored according to the suppliers’ recommendations, "
    "and their integrity was visually verified before utilization. Moreover, all reagents and supplies had valid expiration dates. "
    "The functionality of all equipment was confirmed by reviewing data generated by our comprehensive in-house continuous monitoring system."
)

p4 = (
    "The cleanroom suite (CR 114) used for processing procedures comprises three interconnected sections: the innermost ISO 7 cleanroom (114B), "
    "which connects to the middle ISO 7 buffer room (114A), and then to the outermost ISO 8 anteroom (114). A positive air pressure system "
    "is maintained throughout the suite to ensure controlled, unidirectional airflow from 114B through 114A and into 114."
)

p5 = (
    f"The ISO 5 BSC E00{data['bsc_id']}, located in the innermost ISO 7 room, (114B), was used for sample processing steps. It was thoroughly "
    "cleaned and disinfected prior to each procedure in accordance with MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    f"Additionally, BSC E00{data['bsc_id']} was certified and approved by both the Engineering and Quality Assurance teams. Sample processing was "
    f"conducted in the ISO 5 BSC E00{data['bsc_id']} in the innermost ISO 7 room, (114B) by Alex Saravia on {data['process_date_full']} as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p6 = (
    f"On 02 Sep 2026, the sample vials for {data['sample_id_pure']} were received from the Sample Submissions team and brought into "
    "the Sterile Microbiology lab. Upon arrival, each sample vial was sprayed with an acidified bleach disinfectant, placed into "
    "pre-disinfected bins, and allowed a 10-minute contact time."
)

p7 = (
    "The secondary disinfection happened in the ISO 8 anteroom (114), where the vials were again treated with acidified bleach and provided "
    "a 10-minute contact time before processing. Subsequently, the vials were moved into innermost ISO 7 cleanroom (114B). Inside this cleanroom, "
    "the processing analyst, Alex Saravia, performed a final disinfection step, allowing an additional 10-minute contact time. Once fully disinfected, "
    f"the vials were transferred into the ISO 5 BSC E00{data['bsc_id']}."
)

p8 = (
    "Inside the BSC, each container was aseptically opened, ensuring minimal exposure to the environment. The contents of 3 vials "
    "were dispensed directly from the container into sterile canisters placed on a vacuum manifold for membrane filtration. "
    f"The sample was processed and tested as per MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test). Media bottles were "
    "transferred into incubators E001356 and E001357 to begin incubation."
)

p9 = (
    f"On {data['test_date_full']} (Day 6 of incubation), microbial growth was observed in one TSB (Tryptic Soy Broth) media bottle by reading analyst, "
    f"Elysse Nioupin, and confirmed by Microbiology Lab Supervisor, Robin Seymour. The positive TSB bottle for {data['sample_id_pure']} was submitted "
    f"for Differential Staining and Microbial Identification under {data['positive_id']}. While preliminary microscopic examination of the turbid broth "
    f"indicated presumptive Gram-negative rods, definitive molecular identification of the subcultured isolates on TSA and SDA confirmed the organism as {data['positive_org']}."
)

text_field_49 = "\r \r".join([p1, p2, p3, p4, p5, p6, p7, p8, p9])

# --- PAGE 4 (Text Field 50) ---
p10 = (
    "ISO 5 BSC Environmental Monitoring Results Evaluation:\r"
    "After reviewing the Environmental Monitoring (EM) results for the relevant testing period, no microbial growth was detected "
    "on personnel monitoring plates, settling plates, or ISO 5 BSC surface sampling plates on the date of testing (04Sep26), the preceding "
    "sampling date (03Sep26), or the subsequent sampling date (08Sep26)."
)

p11 = (
    "Cleanroom Environmental Monitoring Results Evaluation:\r"
    "No microbial growth was recovered from the weekly active surface sampling plate collected on 04 Sep 2026. However, 2 CFUs "
    "(ETX-260914-0487) were recovered from the weekly active air sampling of ISO 8 cleanroom 114 by analyst ISS. The organisms were identified as "
    "Corynebacterium ureicelerivorans and Mycobacterium grossiae. It is important to note that the environmental isolates were not identical to the microorganism "
    f"identified in test sample ({data['positive_org']}). All sample processing activities were performed within the validated ISO 5 BSC E00{data['bsc_id']} "
    "located in the innermost ISO 7 cleanroom (114B) separated by ISO 7 buffer room (114A) and ISO 8 anteroom (114). Furthermore, the test samples "
    "are transferred in disinfected and lidded containers through the layered cleanroom suite. Therefore, as the recovered organisms were different "
    "and originated outside the sample processing environment, the cleanroom environmental isolates were not considered related to the test sample contamination."
)

p12 = (
    "The absence of contamination on analyst glove plates and work-surface environmental monitoring plates collected on the date of testing indicates "
    "that there was no viable transfer of contaminants to the ISO 5 biological safety cabinet (BSC). Additionally, the lack of contamination in other samples "
    "processed during the same testing session further demonstrates that the testing environment was operating in optimal condition."
)

p13 = (
    "Therefore, considering that no viable organisms were recovered from the ISO 5 environment, personnel monitoring results were acceptable on the date "
    "of testing, and the environmental isolates were not recovered from locations or surfaces directly involved in sample preparation or testing, the "
    "environmental isolate is not considered a credible source of the contamination detected in the test sample."
)

p14 = (
    "The analysts confirmed full compliance with cleaning procedures as outlined in MICRO SOP-9 (Cleaning and Disinfecting Procedure for Microbiology) "
    "and MICRO-SOP-5 (USP <71> / EP 2.6.1 Sterility Test)."
)

p15 = (
    "Monthly cleaning and disinfection of the outermost ISO 8 Anteroom, the middle ISO 7 Buffer room, the innermost ISO 7 cleanroom, and its containing "
    f"ISO 5 BSCs for Cleanroom suite CR114 was performed on {data['monthly_cleaning_date_full']}, as per MICRO-SOP-9 (Cleaning and Disinfecting Procedure for Microbiology). "
    "During both cleaning cycles, it was documented that all H2O2 indicators passed. This confirms the efficient monthly cleaning of all three parts of Cleanroom suite CR114."
)

p16 = (
    f"Analyzing a 6-month sample history for {data['client_name']}, this specific analyte \"{data['sample_name']}\" has had no prior failures using "
    f"USP <71> / EP 2.6.1 Sterility Test during this period."
)

p17 = (
    "To assess the potential for sample-to-sample contamination contributing to the positive results, a comprehensive review was conducted of all samples "
    f"processed on the same day ({data['process_date_full']}). Sample {data['sample_id_pure']} was the 3rd sample processed in the batch. All other samples "
    "processed by the analyst and other analysts that day tested negative. These findings suggest that cross-contamination between samples is highly unlikely."
)

p18 = (
    "During the preliminary interview and investigation, a potential laboratory error was identified during the resuspension of the lyophilized sample. "
    "Consequently, there is a likelihood of a potential source of laboratory error from the processing analyst. Importantly, the same sample lot "
    "(2608-216) was previously submitted for ScanRDI Sterility Testing under ETX-260807-0602 with passing results. As part of the Phase II investigation, "
    "additional sample vials were requested to perform retesting. The remaining samples processed in the same batch on 04 Sep 2026 continued to be "
    "monitored with no additional failures. Therefore, a Phase II investigation and retesting were initiated under Form 3.100.019.F02."
)

text_field_50 = "\r \r".join([p10, p11, p12, p13, p14, p15, p16, p17, p18])

# --- PAGE 5 (Text Field 51) ---
writer_initial = "QYC"
text_field_51 = f"N/A {writer_initial} 08Oct26"

# Assemble Master Narrative for Word Template
smart_phase1_full = f"{text_field_49}\n\n{text_field_50}"

data["smart_phase1_summary"] = smart_phase1_full
data["equipment_summary"] = p5
data["narrative_summary"] = p11
data["sample_history_paragraph"] = p16
data["cross_contamination_summary"] = p17
data["smart_comment_interview"] = "Yes. During preliminary interview, a potential laboratory error was identified during resuspension of lyophilized sample."
data["smart_comment_samples"] = f"Yes, sample ID: {data['sample_id_pure']}"
data["smart_comment_records"] = f"Yes, Information is available in EagleTrax under {data['sample_id_pure']}"
data["smart_comment_storage"] = f"Yes, the sample was stored as per client's instructions. Information is available in EagleTrax Sample Location History under {data['sample_id_pure']}"
data["smart_personnel_block"] = (
    "Prepping Analyst:\nAlex Saravia (ES)\n\n"
    "Processing Analyst:\nAlex Saravia (ES)\n\n"
    "Reading Analyst:\nElysse Nioupin (EN)"
)
data["analyst_signature"] = f"Alex Saravia (Written by: {data['writer_name']})"
data["smart_incident_opening"] = f"On {data['test_date_full']}, sample {data['sample_id']} was found positive for viable microorganisms after USP <71> sterility testing."
data["usp71_id"] = f"E00{data['bsc_id']}"
data["reader_name"] = data["reading_name"]

# 3. Master Word Report Generation
out_doc_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
primary_tpl = "USP71 OOS P1 template.docx" if os.path.exists("USP71 OOS P1 template.docx") else "USP71 OOS P1 template 0.docx"
tpl_report = DocxTemplate(primary_tpl)
tpl_report.render(data)

# Read the standalone table document to insert clean tables into Master Word report
standalone_docx = os.path.join(DESKTOP_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.docx")
if not os.path.exists(standalone_docx):
    standalone_docx = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.docx")

if os.path.exists(standalone_docx):
    doc_tables_src = docx.Document(standalone_docx)
    if len(tpl_report.docx.tables) >= 3 and len(doc_tables_src.tables) >= 2:
        t2_elem = tpl_report.docx.tables[1]._element
        p2_parent = t2_elem.getparent()
        idx2 = p2_parent.index(t2_elem)
        p2_parent.remove(t2_elem)
        new_t1_elem = copy.deepcopy(doc_tables_src.tables[0]._element)
        p2_parent.insert(idx2, new_t1_elem)

        t3_elem = tpl_report.docx.tables[2]._element
        p3_parent = t3_elem.getparent()
        idx3 = p3_parent.index(t3_elem)
        p3_parent.remove(t3_elem)
        new_t2_elem = copy.deepcopy(doc_tables_src.tables[1]._element)
        p3_parent.insert(idx3, new_t2_elem)

for p in tpl_report.docx.paragraphs:
    if "Table 1:" in p.text:
        p.text = f"Table 1: Information for {data['sample_id']} under investigation"
        p.runs[0].bold = True
    elif "Table 2:" in p.text:
        p.text = f"Table 2: Environmental Monitoring from Processing Performed on {data['process_date']}"
        p.runs[0].bold = True

tpl_report.save(out_doc_report)
print("Saved Master Word Report to:", out_doc_report)

# 4. Official PDF Form (6 Pages base + Page 7 Standalone Table)
base_pdf = r"C:\Users\qchen\OneDrive - Professional Compounding Centers of America, Inc\Desktop\CORP-FORM-21 - P1 04 SEP 2026.pdf"
if not os.path.exists(base_pdf):
    base_pdf = "USP71 OOS P1 template.pdf"
print("Using base PDF form:", base_pdf)
pdf_map = {
    'Text Field57': data['oos_id'],
    'Date Field0': "04-Sep-2026",
    'Date Field1': "10-Sep-2026",
    'Date Field2': "10-Sep-2026",
    'Date Field3': "10-Sep-2026",
    'Text Field1': data['test_name'],
    'Text Field2': data['sample_id'],
    'Text Field3': data['smart_personnel_block'],
    'Text Field4': data['sample_name'],
    'Text Field5': data['dosage_form'],
    'Text Field6': data['lot_number'],
    'Text Field7': data['smart_incident_opening'],
    'Text Field8': data['test_method'],
    'Text Field9': data['sop_effective_date'],
    'Text Field10': data['sop_rev'],
    'Text Field11': "Pass/Fail",
    'Text Field12': data['qa_notified'],
    'Text Field0': data['analyst_signature'],
    'Text Field13': data['smart_comment_interview'],
    'Text Field14': data['smart_comment_samples'],
    'Text Field15': f"Yes, as per {data['test_method']}",
    'Text Field16': f"Yes, as per {data['test_method']}",
    'Text Field17': data['smart_comment_records'],
    'Text Field18': "Yes, the analysts are trained and qualified by quality to perform the test",
    'Text Field19': "Not Applicable",
    'Text Field20': "Not Applicable",
    'Text Field21': data['smart_comment_storage'],
    'Text Field22': (
        "Process Consumables:\r\n"
        "Information is available in EagleTrax Sample Consumables section\r\n \r\n"
        "Environmental Plates:\r\n"
        "TSA and Surface Plate: see attached environmental logs\r\n \r\n"
        "Monthly Cleaning:\r\n"
        "H2O2 strips and IPA: See attached monthly cleaning logs"
    ),
    'Text Field23': (
        "Process Consumables:\r\n"
        "Information is available in EagleTrax Sample Consumables section\r\n \r\n"
        "Environmental Plates:\r\n"
        "TSA and Surface Plate: see attached environmental logs\r\n \r\n"
        "Monthly Cleaning:\r\n"
        "H2O2 strips and IPA: See attached monthly cleaning logs"
    ),
    'Text Field24': "Not applicable",
    'Text Field25': "Not applicable",
    'Text Field26': "Not applicable",
    'Text Field27': "Not applicable",
    'Text Field28': "Not applicable",
    'Text Field29': "Not applicable",
    'Text Field30': f"ISO 5 BSC E00{data['bsc_id']}",
    'Text Field31': "Jun 2027",
    'Text Field32': data['smart_cr_id'],
    'Text Field33': "Dec 2026",
    'Text Field34': "Not applicable",
    'Text Field35': "Not applicable",
    'Text Field36': "Not applicable",
    'Text Field37': "Not applicable",
    'Text Field38': "Not applicable",
    'Text Field39': "Not applicable",
    'Text Field40': "See Phase I Summary",
    'Text Field41': "See Phase I Summary",
    'Text Field42': "See Phase I Summary",
    'Text Field43': (
        "Incubator E001356 (Sensor E001450)\r \r"
        "Incubator E001357 (Sensor E001449)\r \r"
        "Incubator E001034 (Sensor E001501)\r \r"
        "Incubator E001031 (Sensor E001505)"
    ),
    'Text Field44': (
        "Jan 2027 / Feb 2027\r \r"
        "Jan 2027 / Feb 2027\r \r"
        "Aug 2027 / Feb 2027\r \r"
        "Aug 2027 / Feb 2027"
    ),
    'Text Field45': "See Phase I Summary",
    'Text Field46': "Not applicable",
    'Text Field47': "Not applicable",
    'Text Field48': f"N/A {writer_initial} 08Oct26",
    'Text Field49': text_field_49,
    'Text Field50': text_field_50,
    'Text Field51': text_field_51,
    'Text Field52': 'A potential laboratory error was identified during resuspension of lyophilized sample. Initiating Phase II (Form 3.100.019.F02).',
    'Text Field53': data['writer_name'],
    'Text Field54': ""
}

# Checkboxes matching approved gold-standard
checkbox_fields = {
    'Check Box0': '/Yes',
    'Check Box1': '/Yes',
    'Check Box2': '/Yes',
    'Check Box4': '/Yes',
    'Check Box7': '/Yes',
    'Check Box10': '/Yes',
    'Check Box13': '/Yes',
    'Check Box16': '/Yes',
    'Check Box19': '/Yes',
    'Check Box24': '/Yes',
    'Check Box27': '/Yes',
    'Check Box28': '/Yes',
    'Check Box32': '/Yes',
    'Check Box34': '/Yes',
    'Check Box38': '/Yes',
    'Check Box42': '/Yes',
    'Check Box43': '/Yes',
    'Check Box48': '/Yes',
    'Check Box51': '/Yes',
    'Check Box52': '/Yes',
    'Check Box55': '/Yes',
    'Check Box60': '/Yes',
    'Check Box63': '/Yes',
    'Check Box66': '/Yes',
    'Check Box67': '/Yes',  # Environmental monitoring conforms
    'Check Box70': '/Yes',  # Controls conform
    'Check Box73': '/Yes',
    'Check Box78': '/Yes',
    'Check Box79': '/Yes',
    'Check Box87': '/Yes',  # Lab error identified
    'Check Box89': '/Yes',  # Initiate Phase II Form 3.100.019.F02
    'Check Box91': '/Yes',  # Cannot close - initiate Phase II
}
pdf_map.update(checkbox_fields)

writer = PdfWriter(clone_from=base_pdf)
while len(writer.pages) > 6:
    del writer.pages[-1]

for p in writer.pages:
    writer.update_page_form_field_values(p, pdf_map)

# Append Standalone Table PDF as Page 7
standalone_pdf = os.path.join(DESKTOP_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
if not os.path.exists(standalone_pdf):
    standalone_pdf = os.path.join(OUTPUT_DIR, f"Tables OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")

if os.path.exists(standalone_pdf):
    table_reader = PdfReader(standalone_pdf)
    for table_page in table_reader.pages:
        writer.add_page(table_page)
    print(f"Appended Tables PDF to form. Total pages: {len(writer.pages)} (Must be 7)")

out_pdf_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71.pdf")
with open(out_pdf_report, "wb") as f:
    writer.write(f)
print("Saved complete PDF Report to:", out_pdf_report)

# Calibrate font sizes in PDF fields per Rule 11 (Natural Human Typography & Acrobat '+' Elimination)
try:
    doc_fitz = fitz.open(out_pdf_report)
    font_sizes = {
        # Page 1
        'Text Field0': 8.5,
        'Date Field0': 8.5,
        'Date Field1': 8.5,
        'Date Field2': 8.5,
        'Date Field3': 8.5,
        'Text Field1': 8.5,
        'Text Field2': 8.5,
        'Text Field3': 6.225,
        'Text Field4': 8.5,
        'Text Field5': 8.5,
        'Text Field6': 8.5,
        'Text Field7': 8.0,
        'Text Field8': 8.5,
        'Text Field9': 8.5,
        'Text Field10': 8.5,
        'Text Field11': 8.5,
        'Text Field12': 8.5,
        'Text Field13': 4.825,
        'Text Field14': 8.5,
        'Text Field15': 9.0,
        'Text Field16': 9.0,
        'Text Field17': 6.725,
        'Text Field18': 4.825,
        'Text Field19': 9.0,
        'Text Field20': 9.0,
        'Text Field21': 5.85,
        
        # Page 2
        'Text Field22': 4.35,
        'Text Field23': 4.75,
        'Text Field24': 8.5,
        'Text Field25': 8.5,
        'Text Field26': 8.5,
        'Text Field27': 8.5,
        'Text Field28': 8.5,
        'Text Field29': 8.5,
        'Text Field30': 8.5,
        'Text Field31': 8.5,
        'Text Field32': 4.825,
        'Text Field33': 4.825,
        'Text Field34': 8.5,
        'Text Field35': 8.5,
        'Text Field36': 8.5,
        'Text Field37': 8.5,
        'Text Field38': 8.5,
        'Text Field39': 8.5,
        'Text Field40': 8.5,
        'Text Field41': 8.5,
        'Text Field42': 8.5,
        'Text Field43': 7.05,
        'Text Field44': 7.05,
        'Text Field45': 8.5,
        
        # Page 3
        'Text Field46': 8.5,
        'Text Field47': 8.5,
        'Text Field48': 8.5,
        'Text Field49': 8.5,
        
        # Page 4
        'Text Field50': 8.5,
        
        # Page 5
        'Text Field51': 7.8,
        
        # Page 6
        'Text Field53': 10.0,
        'Text Field57': 6.5,
    }
    for page in doc_fitz:
        for w in page.widgets():
            if w.field_name in font_sizes:
                w.text_fontsize = font_sizes[w.field_name]
                w.update()
    temp_pdf_out = out_pdf_report + ".tmp.pdf"
    doc_fitz.save(temp_pdf_out)
    doc_fitz.close()
    shutil.move(temp_pdf_out, out_pdf_report)
    print("Fine-tuned all field font sizes with PyMuPDF.")
except Exception as e:
    print(f"PyMuPDF font tuning notice: {e}")

# Save State Data (.txt / .json)
out_json_path = os.path.join(OUTPUT_DIR, f"SAVE_OOS-{data['oos_id']} {data['client_name']} - USP71.txt")
with open(out_json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
print("Saved session state JSON to:", out_json_path)

# Copy QYC named PDF
qyc_pdf_report = os.path.join(OUTPUT_DIR, f"OOS-{data['oos_id']} {data['client_name']} - USP71 - QYC.pdf")
shutil.copy2(out_pdf_report, qyc_pdf_report)

# Sync all files to Desktop and Documents safely
files_to_sync = [
    out_doc_report,
    out_pdf_report,
    qyc_pdf_report,
    out_json_path
]
for fpath in files_to_sync:
    if fpath and os.path.exists(fpath):
        for target_dir in [DOCUMENTS_DIR, DESKTOP_DIR]:
            dest = os.path.join(target_dir, os.path.basename(fpath))
            try:
                shutil.copy2(fpath, dest)
                print(f"Synced to: {dest}")
            except Exception as e:
                print(f"Notice: {dest} locked or skipped ({e})")

print("\n--- ALL MASTER OOS-262098 DELIVERABLES GENERATED SUCCESSFULLY! ---")
